-----------------------------------------------------------
----MAPFRE DGTP - MODELO DE DATOS                        ---
-----------------------------------------------------------
---Nº PETICIÓN:       RF00574406 - SD01981722
---SOLICITADA POR:    BLAZQUF
---OBJETOS AFECTADOS: A1004803, GENERICA
---PROYECTO:          TRN_TRON
---ENTORNO:           WDMD04
---REALIZADO POR:     MDALBE1
---TIPOLOGIA:         REENTRANTE
-----------------------------------------------------------

BEGIN
  BEGIN
    INSERT INTO TRON2000.TRN_COMENTARIO_TABLAS
      (NOM_TABLA,
       COD_IDIOMA,
       TXT_COMENTARIO,
       COD_USR_REVISION,
       VAL_ESTADO_COLUMNAS)
    VALUES
      ('A1004803',
       'ES',
       'TABLA DATOS POLIZA-RIESGO PROPHET',
       'SMD',
       'TOTAL');
  EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
      UPDATE TRON2000.TRN_COMENTARIO_TABLAS
         SET TXT_COMENTARIO      = 'TABLA DATOS POLIZA-RIESGO PROPHET',
             COD_USR_REVISION    = 'SMD',
             VAL_ESTADO_COLUMNAS = 'TOTAL'
       WHERE NOM_TABLA = 'A1004803'
         AND COD_IDIOMA = 'ES';
  END;
  BEGIN
    INSERT INTO TRON2000.TRN_COMENTARIO_TABLAS
      (NOM_TABLA,
       COD_IDIOMA,
       TXT_COMENTARIO,
       COD_USR_REVISION,
       VAL_ESTADO_COLUMNAS)
    VALUES
      ('A1004803',
       'EN',
       'PROPHET POLICY-RISK DATA TABLE',
       'SMD',
       'TOTAL');
  EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
      UPDATE TRON2000.TRN_COMENTARIO_TABLAS
         SET TXT_COMENTARIO      = 'PROPHET POLICY-RISK DATA TABLE',
             COD_USR_REVISION    = 'SMD',
             VAL_ESTADO_COLUMNAS = 'TOTAL'
       WHERE NOM_TABLA = 'A1004803'
         AND COD_IDIOMA = 'EN';
  END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'COD_CANAL1',
		 'ES',
		 'CODIGO CANAL1 DE DISTRIBUCION',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'CODIGO CANAL1 DE DISTRIBUCION',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'COD_CANAL1'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'COD_CANAL1', 'EN', 'DISTRIBUTION CODE CHANNEL1', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'DISTRIBUTION CODE CHANNEL1',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'COD_CANAL1'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'COD_CANAL2',
		 'ES',
		 'CODIGO CANAL2 DE DISTRIBUCION',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'CODIGO CANAL2 DE DISTRIBUCION',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'COD_CANAL2'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'COD_CANAL2', 'EN', 'DISTRIBUTION CODE CHANNEL2', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'DISTRIBUTION CODE CHANNEL2',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'COD_CANAL2'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'COD_CANAL3',
		 'ES',
		 'CODIGO CANAL3 DE DISTRIBUCION',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'CODIGO CANAL3 DE DISTRIBUCION',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'COD_CANAL3'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'COD_CANAL3', 'EN', 'DISTRIBUTION CODE CHANNEL3', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'DISTRIBUTION CODE CHANNEL3',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'COD_CANAL3'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'COD_CIA', 'ES', 'COMPAÑIA', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO = 'COMPAÑIA', COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'COD_CIA'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'COD_CIA', 'EN', 'COMPANY', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO = 'COMPANY', COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'COD_CIA'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'COD_KMODALIDAD',
		 'ES',
		 'CODIGO O INDICADOR DEL PRODUCTO',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'CODIGO O INDICADOR DEL PRODUCTO',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'COD_KMODALIDAD'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'COD_KMODALIDAD',
		 'EN',
		 'PRODUCT CODE OR INDICATOR',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'PRODUCT CODE OR INDICATOR',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'COD_KMODALIDAD'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'COD_MON', 'ES', 'MONEDA', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO = 'MONEDA', COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'COD_MON'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'COD_MON', 'EN', 'CURRENCY', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO = 'CURRENCY', COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'COD_MON'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'COD_RAMO', 'ES', 'RAMO', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO = 'RAMO', COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'COD_RAMO'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'COD_RAMO', 'EN', 'BUSINESS LINE', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO = 'BUSINESS LINE', COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'COD_RAMO'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'COD_SIS_ORIGEN', 'ES', 'ORIGEN DE DATOS (TW)', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'ORIGEN DE DATOS (TW)',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'COD_SIS_ORIGEN'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'COD_SIS_ORIGEN', 'EN', 'DATA SOURCE', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO = 'DATA SOURCE', COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'COD_SIS_ORIGEN'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'COD_SOCIEDAD', 'ES', 'SOCIEDAD', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO = 'SOCIEDAD', COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'COD_SOCIEDAD'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'COD_SOCIEDAD', 'EN', 'SOCIETY', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO = 'SOCIETY', COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'COD_SOCIEDAD'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'FEC_DESDERENOVA',
		 'ES',
		 'FECHA ULTIMA RENOVACION POR GARANTIA',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'FECHA ULTIMA RENOVACION POR GARANTIA',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'FEC_DESDERENOVA'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'FEC_DESDERENOVA',
		 'EN',
		 'LAST DATE WARRANTY RENEWAL',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'LAST DATE WARRANTY RENEWAL',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'FEC_DESDERENOVA'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'FEC_FINFINANCIA',
		 'ES',
		 'FECHA INICIO FINANCIACION POR POLIZA',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'FECHA INICIO FINANCIACION POR POLIZA',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'FEC_FINFINANCIA'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'FEC_FINFINANCIA',
		 'EN',
		 'DATE START FINANCING BY POLICY',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'DATE START FINANCING BY POLICY',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'FEC_FINFINANCIA'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'FEC_FINPAGPRIM',
		 'ES',
		 'FECHA FIN PAGO DE PRIMAS POR GARANTIA',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'FECHA FIN PAGO DE PRIMAS POR GARANTIA',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'FEC_FINPAGPRIM'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'FEC_FINPAGPRIM',
		 'EN',
		 'END DATE PAYMENT OF PREMIUMS BY GUARANTEE',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'END DATE PAYMENT OF PREMIUMS BY GUARANTEE',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'FEC_FINPAGPRIM'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'FEC_HASTARENOVA',
		 'ES',
		 'FECHA PROXIMA RENOVACION POR GARANTIA',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'FECHA PROXIMA RENOVACION POR GARANTIA',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'FEC_HASTARENOVA'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'FEC_HASTARENOVA',
		 'EN',
		 'NEXT DATE WARRANTY RENEWAL',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'NEXT DATE WARRANTY RENEWAL',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'FEC_HASTARENOVA'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('A1004803', 'FEC_INI', 'ES', 'FECHA EFECTO INICIAL POR POLIZA', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'FECHA EFECTO INICIAL POR POLIZA',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'A1004803'
		   AND NOM_COLUMNA = 'FEC_INI'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('A1004803', 'FEC_INI', 'EN', 'DATE INITIAL EFFECT PER POLICY', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'DATE INITIAL EFFECT PER POLICY',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'A1004803'
		   AND NOM_COLUMNA = 'FEC_INI'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'FEC_INIPAGPRIM',
		 'ES',
		 'FECHA INICIO PAGO DE PRIMAS POR GARANTIA',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'FECHA INICIO PAGO DE PRIMAS POR GARANTIA',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'FEC_INIPAGPRIM'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'FEC_INIPAGPRIM',
		 'EN',
		 'DATE START PAYMENT OF PREMIUMS BY GUARANTEE',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'DATE START PAYMENT OF PREMIUMS BY GUARANTEE',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'FEC_INIPAGPRIM'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'FEC_NACA6', 'ES', 'FECHA NACIMIENTO ASEGURADO 6', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'FECHA NACIMIENTO ASEGURADO 6',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'FEC_NACA6'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'FEC_NACA6', 'EN', 'DATE OF BIRTH INSURED 6', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'DATE OF BIRTH INSURED 6',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'FEC_NACA6'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'FEC_NACASEG1',
		 'ES',
		 'FECHA NACIMIENTO ASEGURADO 1',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'FECHA NACIMIENTO ASEGURADO 1',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'FEC_NACASEG1'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'FEC_NACASEG1', 'EN', 'DATE OF BIRTH INSURED 1', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'DATE OF BIRTH INSURED 1',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'FEC_NACASEG1'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'FEC_NACASEG2',
		 'ES',
		 'FECHA NACIMIENTO ASEGURADO 2',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'FECHA NACIMIENTO ASEGURADO 2',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'FEC_NACASEG2'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'FEC_NACASEG2', 'EN', 'DATE OF BIRTH INSURED 2', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'DATE OF BIRTH INSURED 2',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'FEC_NACASEG2'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'FEC_NACASEG3',
		 'ES',
		 'FECHA NACIMIENTO ASEGURADO 3',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'FECHA NACIMIENTO ASEGURADO 3',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'FEC_NACASEG3'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'FEC_NACASEG3', 'EN', 'DATE OF BIRTH INSURED 3', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'DATE OF BIRTH INSURED 3',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'FEC_NACASEG3'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'FEC_NACASEG4',
		 'ES',
		 'FECHA NACIMIENTO ASEGURADO 4',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'FECHA NACIMIENTO ASEGURADO 4',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'FEC_NACASEG4'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'FEC_NACASEG4', 'EN', 'DATE OF BIRTH INSURED 4', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'DATE OF BIRTH INSURED 4',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'FEC_NACASEG4'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'FEC_NACASEG5',
		 'ES',
		 'FECHA NACIMIENTO ASEGURADO 5',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'FECHA NACIMIENTO ASEGURADO 5',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'FEC_NACASEG5'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'FEC_NACASEG5', 'EN', 'DATE OF BIRTH INSURED 5', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'DATE OF BIRTH INSURED 5',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'FEC_NACASEG5'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'FEC_RED',
		 'ES',
		 'FECHA EFECTO REDUCCION POR POLIZA',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'FECHA EFECTO REDUCCION POR POLIZA',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'FEC_RED'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'FEC_RED', 'EN', 'DATE EFFECT REDUCTION BY POLICY', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'DATE EFFECT REDUCTION BY POLICY',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'FEC_RED'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'IDN_INT_PROC', 'ES', 'IDENTIFICADOR DE PROCESO', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'IDENTIFICADOR DE PROCESO',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'IDN_INT_PROC'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'IDN_INT_PROC', 'EN', 'PROCESS ID', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO = 'PROCESS ID', COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'IDN_INT_PROC'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'NUM_AJVALPC2',
		 'ES',
		 'AJUSTE EN PORCENTAJE APLICADO A LAS TABLAS DE VALORACION PARA ASEGURADO 2',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'AJUSTE EN PORCENTAJE APLICADO A LAS TABLAS DE VALORACION PARA ASEGURADO 2',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'NUM_AJVALPC2'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'NUM_AJVALPC2',
		 'EN',
		 'PERCENTAGE ADJUSTMENT APPLIED TO VALUATION TABLES FOR INSURED 2',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'PERCENTAGE ADJUSTMENT APPLIED TO VALUATION TABLES FOR INSURED 2',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'NUM_AJVALPC2'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'NUM_AJVALPC3',
		 'ES',
		 'AJUSTE EN PORCENTAJE APLICADO A LAS TABLAS DE VALORACION PARA ASEGURADO 3',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'AJUSTE EN PORCENTAJE APLICADO A LAS TABLAS DE VALORACION PARA ASEGURADO 3',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'NUM_AJVALPC3'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'NUM_AJVALPC3',
		 'EN',
		 'PERCENTAGE ADJUSTMENT APPLIED TO VALUATION TABLES FOR INSURED 3',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'PERCENTAGE ADJUSTMENT APPLIED TO VALUATION TABLES FOR INSURED 3',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'NUM_AJVALPC3'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'NUM_AJVALPC4',
		 'ES',
		 'AJUSTE EN PORCENTAJE APLICADO A LAS TABLAS DE VALORACION PARA ASEGURADO 4',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'AJUSTE EN PORCENTAJE APLICADO A LAS TABLAS DE VALORACION PARA ASEGURADO 4',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'NUM_AJVALPC4'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'NUM_AJVALPC4',
		 'EN',
		 'PERCENTAGE ADJUSTMENT APPLIED TO VALUATION TABLES FOR INSURED 4',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'PERCENTAGE ADJUSTMENT APPLIED TO VALUATION TABLES FOR INSURED 4',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'NUM_AJVALPC4'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'NUM_AJVALPC5',
		 'ES',
		 'AJUSTE EN PORCENTAJE APLICADO A LAS TABLAS DE VALORACION PARA ASEGURADO 5',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'AJUSTE EN PORCENTAJE APLICADO A LAS TABLAS DE VALORACION PARA ASEGURADO 5',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'NUM_AJVALPC5'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'NUM_AJVALPC5',
		 'EN',
		 'PERCENTAGE ADJUSTMENT APPLIED TO VALUATION TABLES FOR INSURED 5',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'PERCENTAGE ADJUSTMENT APPLIED TO VALUATION TABLES FOR INSURED 5',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'NUM_AJVALPC5'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'NUM_AJVALPC6',
		 'ES',
		 'AJUSTE EN PORCENTAJE APLICADO A LAS TABLAS DE VALORACION PARA ASEGURADO 6',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'AJUSTE EN PORCENTAJE APLICADO A LAS TABLAS DE VALORACION PARA ASEGURADO 6',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'NUM_AJVALPC6'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'NUM_AJVALPC6',
		 'EN',
		 'PERCENTAGE ADJUSTMENT APPLIED TO VALUATION TABLES FOR INSURED 6',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'PERCENTAGE ADJUSTMENT APPLIED TO VALUATION TABLES FOR INSURED 6',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'NUM_AJVALPC6'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'NUM_AJVALY2',
		 'ES',
		 'AJUSTE EN AÑOS APLICADO A LAS TABLAS DE VALORACION PARA ASEGURADO 2',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'AJUSTE EN AÑOS APLICADO A LAS TABLAS DE VALORACION PARA ASEGURADO 2',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'NUM_AJVALY2'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'NUM_AJVALY2',
		 'EN',
		 'ADJUSTMENT IN YEARS APPLIED TO THE VALUATION TABLES FOR INSURED 2',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'ADJUSTMENT IN YEARS APPLIED TO THE VALUATION TABLES FOR INSURED 2',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'NUM_AJVALY2'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'NUM_AJVALY3',
		 'ES',
		 'AJUSTE EN AÑOS APLICADO A LAS TABLAS DE VALORACION PARA ASEGURADO 3',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'AJUSTE EN AÑOS APLICADO A LAS TABLAS DE VALORACION PARA ASEGURADO 3',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'NUM_AJVALY3'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'NUM_AJVALY3',
		 'EN',
		 'ADJUSTMENT IN YEARS APPLIED TO THE VALUATION TABLES FOR INSURED 3',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'ADJUSTMENT IN YEARS APPLIED TO THE VALUATION TABLES FOR INSURED 3',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'NUM_AJVALY3'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'NUM_AJVALY4',
		 'ES',
		 'AJUSTE EN AÑOS APLICADO A LAS TABLAS DE VALORACION PARA ASEGURADO 4',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'AJUSTE EN AÑOS APLICADO A LAS TABLAS DE VALORACION PARA ASEGURADO 4',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'NUM_AJVALY4'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'NUM_AJVALY4',
		 'EN',
		 'ADJUSTMENT IN YEARS APPLIED TO THE VALUATION TABLES FOR INSURED 4',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'ADJUSTMENT IN YEARS APPLIED TO THE VALUATION TABLES FOR INSURED 4',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'NUM_AJVALY4'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'NUM_AJVALY5',
		 'ES',
		 'AJUSTE EN AÑOS APLICADO A LAS TABLAS DE VALORACION PARA ASEGURADO 5',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'AJUSTE EN AÑOS APLICADO A LAS TABLAS DE VALORACION PARA ASEGURADO 5',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'NUM_AJVALY5'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'NUM_AJVALY5',
		 'EN',
		 'ADJUSTMENT IN YEARS APPLIED TO THE VALUATION TABLES FOR INSURED 5',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'ADJUSTMENT IN YEARS APPLIED TO THE VALUATION TABLES FOR INSURED 5',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'NUM_AJVALY5'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'NUM_AJVALY6',
		 'ES',
		 'AJUSTE EN AÑOS APLICADO A LAS TABLAS DE VALORACION PARA ASEGURADO 6',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'AJUSTE EN AÑOS APLICADO A LAS TABLAS DE VALORACION PARA ASEGURADO 6',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'NUM_AJVALY6'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'NUM_AJVALY6',
		 'EN',
		 'ADJUSTMENT IN YEARS APPLIED TO THE VALUATION TABLES FOR INSURED 6',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'ADJUSTMENT IN YEARS APPLIED TO THE VALUATION TABLES FOR INSURED 6',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'NUM_AJVALY6'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'NUM_APLI', 'ES', 'NUMERO DE APLICACION', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'NUMERO DE APLICACION',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'NUM_APLI'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'NUM_APLI', 'EN', 'APPLICATION NUMBER', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO = 'APPLICATION NUMBER', COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'NUM_APLI'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'NUM_CERTIFICADO', 'ES', 'NUMERO DEL CERTIFICADO', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'NUMERO DEL CERTIFICADO',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'NUM_CERTIFICADO'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'NUM_CERTIFICADO', 'EN', 'CERTIFICATE NUMBER', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO = 'CERTIFICATE NUMBER', COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'NUM_CERTIFICADO'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'NUM_DUR_PRESTMO', 'ES', 'DURACION DEL PRESTAMO', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'DURACION DEL PRESTAMO',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'NUM_DUR_PRESTMO'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'NUM_DUR_PRESTMO', 'EN', 'LOAN DURATION', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO = 'LOAN DURATION', COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'NUM_DUR_PRESTMO'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'NUM_GGIM',
		 'ES',
		 'IMPORTE DE GASTO FIJO DE GESTION POR POLIZA',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'IMPORTE DE GASTO FIJO DE GESTION POR POLIZA',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'NUM_GGIM'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'NUM_GGIM',
		 'EN',
		 'FIXED MANAGEMENT EXPENSE AMOUNT PER POLICY',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'FIXED MANAGEMENT EXPENSE AMOUNT PER POLICY',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'NUM_GGIM'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'NUM_IMPGASMAX',
		 'ES',
		 'IMPORTE GASTO MAXIMO POR POLIZA',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'IMPORTE GASTO MAXIMO POR POLIZA',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'NUM_IMPGASMAX'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'NUM_IMPGASMAX',
		 'EN',
		 'AMOUNT MAXIMUM EXPENDITURE PER POLICY',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'AMOUNT MAXIMUM EXPENDITURE PER POLICY',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'NUM_IMPGASMAX'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'NUM_IMPGASMIN',
		 'ES',
		 'IMPORTE GASTO MINIMO POR POLIZA',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'IMPORTE GASTO MINIMO POR POLIZA',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'NUM_IMPGASMIN'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'NUM_IMPGASMIN',
		 'EN',
		 'AMOUNT MINIMUM EXPENDITURE PER POLICY',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'AMOUNT MINIMUM EXPENDITURE PER POLICY',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'NUM_IMPGASMIN'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'NUM_IT_PRESTMO',
		 'ES',
		 'TIPO DE INTERES ANUAL DEL PRESTAMO',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'TIPO DE INTERES ANUAL DEL PRESTAMO',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'NUM_IT_PRESTMO'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'NUM_IT_PRESTMO',
		 'EN',
		 'ANNUAL INTEREST RATE OF THE LOAN',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'ANNUAL INTEREST RATE OF THE LOAN',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'NUM_IT_PRESTMO'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'NUM_KSUBPOLIZA',
		 'ES',
		 'NIVEL INFERIOR A POLIZA EN EL QUE SE AGRUPEN PARTICIPES',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'NIVEL INFERIOR A POLIZA EN EL QUE SE AGRUPEN PARTICIPES',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'NUM_KSUBPOLIZA'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'NUM_KSUBPOLIZA',
		 'EN',
		 'LOWER LEVEL THAN POLICY IN WHICH PARTICIPANTS ARE GROUPED',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'LOWER LEVEL THAN POLICY IN WHICH PARTICIPANTS ARE GROUPED',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'NUM_KSUBPOLIZA'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'NUM_NAPORT',
		 'ES',
		 'NUMERO DE APORTACION EXTRAORDINARIA REALIZADA',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'NUMERO DE APORTACION EXTRAORDINARIA REALIZADA',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'NUM_NAPORT'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'NUM_NAPORT',
		 'EN',
		 'EXTRAORDINARY CONTRIBUTION NUMBER MADE',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'EXTRAORDINARY CONTRIBUTION NUMBER MADE',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'NUM_NAPORT'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'NUM_NPERICOMI1',
		 'ES',
		 'DURACION DE PAGO DE COMISIONES 1',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'DURACION DE PAGO DE COMISIONES 1',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'NUM_NPERICOMI1'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'NUM_NPERICOMI1',
		 'EN',
		 'DURATION OF COMMISSION PAYMENT 1',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'DURATION OF COMMISSION PAYMENT 1',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'NUM_NPERICOMI1'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'NUM_NPERICOMI2',
		 'ES',
		 'DURACION DE PAGO DE COMISIONES 2',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'DURACION DE PAGO DE COMISIONES 2',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'NUM_NPERICOMI2'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'NUM_NPERICOMI2',
		 'EN',
		 'DURATION OF COMMISSION PAYMENT 2',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'DURATION OF COMMISSION PAYMENT 2',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'NUM_NPERICOMI2'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'NUM_NPERICOMI3',
		 'ES',
		 'DURACION DE PAGO DE COMISIONES 3',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'DURACION DE PAGO DE COMISIONES 3',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'NUM_NPERICOMI3'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'NUM_NPERICOMI3',
		 'EN',
		 'DURATION OF COMMISSION PAYMENT 3',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'DURATION OF COMMISSION PAYMENT 3',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'NUM_NPERICOMI3'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'NUM_PAGOA_PRESTMO',
		 'ES',
		 'PAGO ANUAL DEL PRESTAMO',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'PAGO ANUAL DEL PRESTAMO',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'NUM_PAGOA_PRESTMO'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'NUM_PAGOA_PRESTMO', 'EN', 'ANNUAL LOAN PAYMENT', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO = 'ANNUAL LOAN PAYMENT', COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'NUM_PAGOA_PRESTMO'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'NUM_PCOASEG',
		 'ES',
		 '% DE PARTICIPACION EN COASEGURO (MAPFRE)',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = '% DE PARTICIPACION EN COASEGURO (MAPFRE)',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'NUM_PCOASEG'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'NUM_PCOASEG',
		 'EN',
		 '% SHARE IN COINSURANCE (MAPFRE)',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = '% SHARE IN COINSURANCE (MAPFRE)',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'NUM_PCOASEG'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'NUM_PGASTGESEX_ABRIDORA',
		 'ES',
		 '% GASTOS EXTERNOS ABRIDORA',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = '% GASTOS EXTERNOS ABRIDORA',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'NUM_PGASTGESEX_ABRIDORA'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'NUM_PGASTGESEX_ABRIDORA',
		 'EN',
		 '% OPENER EXTERNAL EXPENSES',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = '% OPENER EXTERNAL EXPENSES',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'NUM_PGASTGESEX_ABRIDORA'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'NUM_PGASTGESIN_ABRIDORA',
		 'ES',
		 '% GASTOS INTERNOS ABRIDORA',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = '% GASTOS INTERNOS ABRIDORA',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'NUM_PGASTGESIN_ABRIDORA'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'NUM_PGASTGESIN_ABRIDORA',
		 'EN',
		 '% OPENER INTERNAL EXPENSES',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = '% OPENER INTERNAL EXPENSES',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'NUM_PGASTGESIN_ABRIDORA'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'NUM_PGGAPROV',
		 'ES',
		 '% GASTO GESTION ANUAL SOBRE PROVISION MATEMATICA',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = '% GASTO GESTION ANUAL SOBRE PROVISION MATEMATICA',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'NUM_PGGAPROV'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'NUM_PGGAPROV',
		 'EN',
		 '% ANNUAL MANAGEMENT EXPENDITURE ON MATH PROVISION',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = '% ANNUAL MANAGEMENT EXPENDITURE ON MATH PROVISION',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'NUM_PGGAPROV'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'NUM_POLIZA', 'ES', 'POLIZA', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO = 'POLIZA', COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'NUM_POLIZA'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'NUM_POLIZA', 'EN', 'POLICY', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO = 'POLICY', COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'NUM_POLIZA'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'NUM_RIESGO', 'ES', 'RIESGO', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO = 'RIESGO', COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'NUM_RIESGO'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'NUM_RIESGO', 'EN', 'RISK', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO = 'RISK', COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'NUM_RIESGO'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'NUM_SPTO', 'ES', 'NUMERO DE SUPLEMENTO', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'NUMERO DE SUPLEMENTO',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'NUM_SPTO'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'NUM_SPTO', 'EN', 'ENDORSEMENT NUMBER', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO = 'ENDORSEMENT NUMBER', COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'NUM_SPTO'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'NUM_SPTO_APLI',
		 'ES',
		 'SUPLEMENTO DE LA APLICACION',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'SUPLEMENTO DE LA APLICACION',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'NUM_SPTO_APLI'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'NUM_SPTO_APLI', 'EN', 'ENDORSEMENT APPLICATION', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'ENDORSEMENT APPLICATION',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'NUM_SPTO_APLI'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'NUM_TIR_CIE', 'ES', 'TIR A FECHA DE VALORACION', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'TIR A FECHA DE VALORACION',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'NUM_TIR_CIE'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'NUM_TIR_CIE', 'EN', 'TIR AT VALUATION DATE', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'TIR AT VALUATION DATE',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'NUM_TIR_CIE'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'NUM_TIRI_NI', 'ES', 'TIR INICIAL CONTRATACION', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'TIR INICIAL CONTRATACION',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'NUM_TIRI_NI'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'NUM_TIRI_NI', 'EN', 'TIR INITIAL HIRING', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO = 'TIR INITIAL HIRING', COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'NUM_TIRI_NI'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'TIP_SPTO', 'ES', 'TIPO DE SUPLEMENTO', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO = 'TIPO DE SUPLEMENTO', COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TIP_SPTO'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'TIP_SPTO', 'EN', 'ENDORSEMENT TYPE', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO = 'ENDORSEMENT TYPE', COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TIP_SPTO'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'TXT_BASECALCULOGESEX',
		 'ES',
		 'BASE CALCULO % GASTOS EXTERNOS ABRIDORA',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'BASE CALCULO % GASTOS EXTERNOS ABRIDORA',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_BASECALCULOGESEX'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'TXT_BASECALCULOGESEX',
		 'EN',
		 'BASE CALCULATION% OPENER EXTERNAL EXPENSES',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'BASE CALCULATION% OPENER EXTERNAL EXPENSES',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_BASECALCULOGESEX'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'TXT_BASECALCULOGESIN',
		 'ES',
		 'BASE CALCULO % GASTOS INTERNOS ABRIDORA',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'BASE CALCULO % GASTOS INTERNOS ABRIDORA',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_BASECALCULOGESIN'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'TXT_BASECALCULOGESIN',
		 'EN',
		 'BASE CALCULATION% OPENER INTERNAL EXPENSES',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'BASE CALCULATION% OPENER INTERNAL EXPENSES',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_BASECALCULOGESIN'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'TXT_CCANAL',
		 'ES',
		 'CANAL DE DISTRIBUCION DEL PRODUCTO',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'CANAL DE DISTRIBUCION DEL PRODUCTO',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_CCANAL'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'TXT_CCANAL', 'EN', 'PRODUCT DISTRIBUTION CHANNEL', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'PRODUCT DISTRIBUTION CHANNEL',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_CCANAL'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'TXT_CCOSTE', 'ES', 'CENTRO DE COSTE (CECO)', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'CENTRO DE COSTE (CECO)',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_CCOSTE'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'TXT_CCOSTE', 'EN', 'COST CENTER (CECO)', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO = 'COST CENTER (CECO)', COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_CCOSTE'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'TXT_CFORMPAGO',
		 'ES',
		 'FRECUENCIA DE PAGO DE PRIMA SEGUN LA GARANTIA',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'FRECUENCIA DE PAGO DE PRIMA SEGUN LA GARANTIA',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_CFORMPAGO'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'TXT_CFORMPAGO',
		 'EN',
		 'FREQUENCY OF PAYMENT OF PREMIUM ACCORDING TO THE GUARANTEE',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'FREQUENCY OF PAYMENT OF PREMIUM ACCORDING TO THE GUARANTEE',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_CFORMPAGO'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'TXT_CNEGOCIO',
		 'ES',
		 'TIPO DE NEGOCIO DE LA POLIZA',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'TIPO DE NEGOCIO DE LA POLIZA',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_CNEGOCIO'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'TXT_CNEGOCIO', 'EN', 'TYPE OF POLICY PRODUCT', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'TYPE OF POLICY PRODUCT',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_CNEGOCIO'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'TXT_COD_RM',
		 'ES',
		 'INDICAR SI EL VALOR DE RESCATE ESTA AFECTO A MERCADO',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'INDICAR SI EL VALOR DE RESCATE ESTA AFECTO A MERCADO',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_COD_RM'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'TXT_COD_RM',
		 'EN',
		 'INDICATES IF THE REDEMPTION VALUE IS AFFECTED BY THE MARKET',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'INDICATES IF THE REDEMPTION VALUE IS AFFECTED BY THE MARKET',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_COD_RM'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'TXT_CSEXA6', 'ES', 'SEXO ASEGURADO 6', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO = 'SEXO ASEGURADO 6', COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_CSEXA6'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'TXT_CSEXA6', 'EN', 'SEX INSURED 6', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO = 'SEX INSURED 6', COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_CSEXA6'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'TXT_CSEXASEG1', 'ES', 'SEXO ASEGURADO 1', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO = 'SEXO ASEGURADO 1', COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_CSEXASEG1'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'TXT_CSEXASEG1', 'EN', 'SEX INSURED 1', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO = 'SEX INSURED 1', COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_CSEXASEG1'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'TXT_CSEXASEG2', 'ES', 'SEXO ASEGURADO 2', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO = 'SEXO ASEGURADO 2', COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_CSEXASEG2'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'TXT_CSEXASEG2', 'EN', 'SEX INSURED 2', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO = 'SEX INSURED 2', COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_CSEXASEG2'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'TXT_CSEXASEG3', 'ES', 'SEXO ASEGURADO 3', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO = 'SEXO ASEGURADO 3', COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_CSEXASEG3'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'TXT_CSEXASEG3', 'EN', 'SEX INSURED 3', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO = 'SEX INSURED 3', COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_CSEXASEG3'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'TXT_CSEXASEG4', 'ES', 'SEXO ASEGURADO 4', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO = 'SEXO ASEGURADO 4', COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_CSEXASEG4'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'TXT_CSEXASEG4', 'EN', 'SEX INSURED 4', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO = 'SEX INSURED 4', COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_CSEXASEG4'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'TXT_CSEXASEG5', 'ES', 'SEXO ASEGURADO 5', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO = 'SEXO ASEGURADO 5', COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_CSEXASEG5'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'TXT_CSEXASEG5', 'EN', 'SEX INSURED 5', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO = 'SEX INSURED 5', COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_CSEXASEG5'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'TXT_CSITUPOL',
		 'ES',
		 'SITUACION DE LA POLIZA EN EL MOMENTO DE VALORACION',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'SITUACION DE LA POLIZA EN EL MOMENTO DE VALORACION',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_CSITUPOL'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'TXT_CSITUPOL',
		 'EN',
		 'STATUS OF THE POLICY AT THE TIME OF VALUATION',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'STATUS OF THE POLICY AT THE TIME OF VALUATION',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_CSITUPOL'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'TXT_CTIPOAPORT',
		 'ES',
		 'PATRON DE PAGO DE LA PRIMA',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'PATRON DE PAGO DE LA PRIMA',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_CTIPOAPORT'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'TXT_CTIPOAPORT', 'EN', 'PREMIUM PAYMENT PATTERN', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'PREMIUM PAYMENT PATTERN',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_CTIPOAPORT'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'TXT_CTIPOCOASEG', 'ES', 'TIPO DE COASEGURO', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO = 'TIPO DE COASEGURO', COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_CTIPOCOASEG'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'TXT_CTIPOCOASEG', 'EN', 'COINSURANCE TYPE', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO = 'COINSURANCE TYPE', COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_CTIPOCOASEG'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'TXT_CTIPOREASEG', 'ES', 'TIPO REASEGURO', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO = 'TIPO REASEGURO', COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_CTIPOREASEG'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'TXT_CTIPOREASEG', 'EN', 'REINSURANCE TYPE', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO = 'REINSURANCE TYPE', COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_CTIPOREASEG'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'TXT_EST_CONY',
		 'ES',
		 'ESTADO DEL CONYUGE (EN CASO DE RENTAS PASIVAS O CON REVERSION)',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'ESTADO DEL CONYUGE (EN CASO DE RENTAS PASIVAS O CON REVERSION)',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_EST_CONY'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'TXT_EST_CONY',
		 'EN',
		 'SPOUSE STATUS (IN CASE OF PASSIVE INCOME OR WITH REVERSION)',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'SPOUSE STATUS (IN CASE OF PASSIVE INCOME OR WITH REVERSION)',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_EST_CONY'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'TXT_EST_H1',
		 'ES',
		 'ESTADO DEL PRIMER HIJO (EN CASO DE RENTAS PASIVAS O CON REVERSION)',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'ESTADO DEL PRIMER HIJO (EN CASO DE RENTAS PASIVAS O CON REVERSION)',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_EST_H1'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'TXT_EST_H1',
		 'EN',
		 'STATE OF THE FIRST CHILD (IN CASE OF PASSIVE INCOME OR WITH REVERSION)',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'STATE OF THE FIRST CHILD (IN CASE OF PASSIVE INCOME OR WITH REVERSION)',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_EST_H1'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'TXT_EST_H2',
		 'ES',
		 'ESTADO DEL SEGUNDO HIJO (EN CASO DE RENTAS PASIVAS O CON REVERSION)',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'ESTADO DEL SEGUNDO HIJO (EN CASO DE RENTAS PASIVAS O CON REVERSION)',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_EST_H2'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'TXT_EST_H2',
		 'EN',
		 'STATUS OF THE SECOND CHILD (IN CASE OF PASSIVE INCOME OR WITH REVERSION)',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'STATUS OF THE SECOND CHILD (IN CASE OF PASSIVE INCOME OR WITH REVERSION)',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_EST_H2'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'TXT_EST_H3',
		 'ES',
		 'ESTADO DEL TERCER HIJO (EN CASO DE RENTAS PASIVAS O CON REVERSION)',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'ESTADO DEL TERCER HIJO (EN CASO DE RENTAS PASIVAS O CON REVERSION)',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_EST_H3'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'TXT_EST_H3',
		 'EN',
		 'STATUS OF THE THIRD CHILD (IN CASE OF PASSIVE INCOME OR WITH REVERSION)',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'STATUS OF THE THIRD CHILD (IN CASE OF PASSIVE INCOME OR WITH REVERSION)',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_EST_H3'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'TXT_EST_TIT',
		 'ES',
		 'ESTADO DEL ASEGURADO TITULAR (EN CASO DE RENTAS PASIVAS O CON REVERSION)',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'ESTADO DEL ASEGURADO TITULAR (EN CASO DE RENTAS PASIVAS O CON REVERSION)',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_EST_TIT'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'TXT_EST_TIT',
		 'EN',
		 'STATUS OF THE INSURED OWNER (IN CASE OF PASSIVE INCOME OR WITH REVERSION)',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'STATUS OF THE INSURED OWNER (IN CASE OF PASSIVE INCOME OR WITH REVERSION)',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_EST_TIT'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'TXT_GAP_ACT',
		 'ES',
		 'IDENTIFICADOR DE CARTERA DE INVERSION',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'IDENTIFICADOR DE CARTERA DE INVERSION',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_GAP_ACT'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'TXT_GAP_ACT',
		 'EN',
		 'INVESTMENT PORTFOLIO IDENTIFIER',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'INVESTMENT PORTFOLIO IDENTIFIER',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_GAP_ACT'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'TXT_INDICRESCATE',
		 'ES',
		 'INDICAR SI DICHA POLIZA ESTA AFECTA A RESCATE',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'INDICAR SI DICHA POLIZA ESTA AFECTA A RESCATE',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_INDICRESCATE'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'TXT_INDICRESCATE',
		 'EN',
		 'INDICATES IF SAID POLICY IS AFFECTING REDEMPTION',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'INDICATES IF SAID POLICY IS AFFECTING REDEMPTION',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_INDICRESCATE'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'TXT_KCOASE_ORI', 'ES', 'COASEGURADORA ORIGEN', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'COASEGURADORA ORIGEN',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_KCOASE_ORI'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'TXT_KCOASE_ORI', 'EN', 'ORIGIN COINSURER', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO = 'ORIGIN COINSURER', COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_KCOASE_ORI'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'TXT_KMODEXT',
		 'ES',
		 'CODIGO DE MODALIDAD AUXILIAR',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'CODIGO DE MODALIDAD AUXILIAR',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_KMODEXT'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'TXT_KMODEXT', 'EN', 'AUXILIARY MODE CODE', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO = 'AUXILIARY MODE CODE', COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_KMODEXT'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'TXT_KPOLIZA', 'ES', 'NUMERO DE POLIZA DE SEGURO', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'NUMERO DE POLIZA DE SEGURO',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_KPOLIZA'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'TXT_KPOLIZA', 'EN', 'INSURANCE POLICY NUMBER', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'INSURANCE POLICY NUMBER',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_KPOLIZA'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'TXT_KPRODUCTO', 'ES', 'TIPOLOGIA DE PRODUCTO', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'TIPOLOGIA DE PRODUCTO',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_KPRODUCTO'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'TXT_KPRODUCTO', 'EN', 'PRODUCT TYPOLOGY', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO = 'PRODUCT TYPOLOGY', COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_KPRODUCTO'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'TXT_KSUBPRODUCTO',
		 'ES',
		 'TIPOLOGIA DE SUBPRODUCTO',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'TIPOLOGIA DE SUBPRODUCTO',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_KSUBPRODUCTO'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'TXT_KSUBPRODUCTO', 'EN', 'SUBPRODUCT TYPOLOGY', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO = 'SUBPRODUCT TYPOLOGY', COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_KSUBPRODUCTO'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'TXT_MESPAGOCOMI',
		 'ES',
		 'MES DE PAGO DE COMISIONES',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'MES DE PAGO DE COMISIONES',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_MESPAGOCOMI'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'TXT_MESPAGOCOMI',
		 'EN',
		 'COMMISSION PAYMENT MONTH',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'COMMISSION PAYMENT MONTH',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_MESPAGOCOMI'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'TXT_MONEDA_REPTNG',
		 'ES',
		 'MONEDA DE REPORTE DE INFORMACION A MAPFRE GRUPO',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'MONEDA DE REPORTE DE INFORMACION A MAPFRE GRUPO',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_MONEDA_REPTNG'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'TXT_MONEDA_REPTNG',
		 'EN',
		 'INFORMATION REPORTING CURRENCY TO MAPFRE GROUP',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'INFORMATION REPORTING CURRENCY TO MAPFRE GROUP',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_MONEDA_REPTNG'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'TXT_TABLA2',
		 'ES',
		 'TABLA BASE DE VALORACION PARA ASEGURADO 2 DE LA GARANTIA ESTABLECIDA EN EL CAMPO KGARANTIA',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'TABLA BASE DE VALORACION PARA ASEGURADO 2 DE LA GARANTIA ESTABLECIDA EN EL CAMPO KGARANTIA',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_TABLA2'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'TXT_TABLA2',
		 'EN',
		 'BASE VALUATION TABLE FOR INSURED 2 OF THE GUARANTEE ESTABLISHED IN THE KGARANTIA FIELD',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'BASE VALUATION TABLE FOR INSURED 2 OF THE GUARANTEE ESTABLISHED IN THE KGARANTIA FIELD',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_TABLA2'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'TXT_TABLA3',
		 'ES',
		 'TABLA BASE DE VALORACION PARA ASEGURADO 3 DE LA GARANTIA ESTABLECIDA EN EL CAMPO KGARANTIA',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'TABLA BASE DE VALORACION PARA ASEGURADO 3 DE LA GARANTIA ESTABLECIDA EN EL CAMPO KGARANTIA',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_TABLA3'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'TXT_TABLA3',
		 'EN',
		 'BASE VALUATION TABLE FOR INSURED 3 OF THE GUARANTEE ESTABLISHED IN THE KGARANTIA FIELD',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'BASE VALUATION TABLE FOR INSURED 3 OF THE GUARANTEE ESTABLISHED IN THE KGARANTIA FIELD',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_TABLA3'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'TXT_TABLA4',
		 'ES',
		 'TABLA BASE DE VALORACION PARA ASEGURADO 4 DE LA GARANTIA ESTABLECIDA EN EL CAMPO KGARANTIA',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'TABLA BASE DE VALORACION PARA ASEGURADO 4 DE LA GARANTIA ESTABLECIDA EN EL CAMPO KGARANTIA',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_TABLA4'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'TXT_TABLA4',
		 'EN',
		 'BASE VALUATION TABLE FOR INSURED 4 OF THE GUARANTEE ESTABLISHED IN THE KGARANTIA FIELD',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'BASE VALUATION TABLE FOR INSURED 4 OF THE GUARANTEE ESTABLISHED IN THE KGARANTIA FIELD',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_TABLA4'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'TXT_TABLA5',
		 'ES',
		 'TABLA BASE DE VALORACION PARA ASEGURADO 5 DE LA GARANTIA ESTABLECIDA EN EL CAMPO KGARANTIA',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'TABLA BASE DE VALORACION PARA ASEGURADO 5 DE LA GARANTIA ESTABLECIDA EN EL CAMPO KGARANTIA',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_TABLA5'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'TXT_TABLA5',
		 'EN',
		 'BASE VALUATION TABLE FOR INSURED 5 OF THE GUARANTEE ESTABLISHED IN THE KGARANTIA FIELD',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'BASE VALUATION TABLE FOR INSURED 5 OF THE GUARANTEE ESTABLISHED IN THE KGARANTIA FIELD',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_TABLA5'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'TXT_TABLA6',
		 'ES',
		 'TABLA BASE DE VALORACION PARA ASEGURADO 6 DE LA GARANTIA ESTABLECIDA EN EL CAMPO KGARANTIA',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'TABLA BASE DE VALORACION PARA ASEGURADO 6 DE LA GARANTIA ESTABLECIDA EN EL CAMPO KGARANTIA',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_TABLA6'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'TXT_TABLA6',
		 'EN',
		 'BASE VALUATION TABLE FOR INSURED 6 OF THE GUARANTEE ESTABLISHED IN THE KGARANTIA FIELD',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'BASE VALUATION TABLE FOR INSURED 6 OF THE GUARANTEE ESTABLISHED IN THE KGARANTIA FIELD',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_TABLA6'
		   AND COD_IDIOMA = 'EN';
	END;
END;
/