-----------------------------------------------------------
---MAPFRE DGTP - MODELO DE DATOS                        ---
-----------------------------------------------------------
---Nº PETICIÓN:       RF00573729 - SD01978888
---SOLICITADA POR:    BLAZQUF
---OBJETOS AFECTADOS: A1004802, GENERICA
---PROYECTO:          TRN_TRON
---ENTORNO:           WDMD04
---REALIZADO POR:     MDALBE1
---TIPOLOGIA:         REENTRANTE
-----------------------------------------------------------

BEGIN
  BEGIN
    INSERT INTO TRON2000.TRN_COMENTARIO_TABLAS
      (NOM_TABLA,
       COD_IDIOMA,
       TXT_COMENTARIO,
       COD_USR_REVISION,
       VAL_ESTADO_COLUMNAS)
    VALUES
      ('A1004802',
       'ES',
       'NIIF 17 CONFIGURACION ATRIBUTO GARANTIA PROPHET',
       'SMD',
       'TOTAL');
  EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
      UPDATE TRON2000.TRN_COMENTARIO_TABLAS
         SET TXT_COMENTARIO      = 'NIIF 17 CONFIGURACION ATRIBUTO GARANTIA PROPHET',
             COD_USR_REVISION    = 'SMD',
             VAL_ESTADO_COLUMNAS = 'TOTAL'
       WHERE NOM_TABLA = 'A1004802'
         AND COD_IDIOMA = 'ES';
  END;
  BEGIN
    INSERT INTO TRON2000.TRN_COMENTARIO_TABLAS
      (NOM_TABLA,
       COD_IDIOMA,
       TXT_COMENTARIO,
       COD_USR_REVISION,
       VAL_ESTADO_COLUMNAS)
    VALUES
      ('A1004802',
       'EN',
       'IFRS 17 GUARANTEE ATTRIBUTE CONFIGURATION PROPHET',
       'SMD',
       'TOTAL');
  EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
      UPDATE TRON2000.TRN_COMENTARIO_TABLAS
         SET TXT_COMENTARIO      = 'IFRS 17 GUARANTEE ATTRIBUTE CONFIGURATION PROPHET',
             COD_USR_REVISION    = 'SMD',
             VAL_ESTADO_COLUMNAS = 'TOTAL'
       WHERE NOM_TABLA = 'A1004802'
         AND COD_IDIOMA = 'EN';
  END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'COD_COB', 'ES', 'COBERTURA', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO = 'COBERTURA', COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'COD_COB'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'COD_COB', 'EN', 'COVERAGE', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO = 'COVERAGE', COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'COD_COB'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'COD_KMODALIDAD',
		 'ES',
		 'CODIGO O INDICADOR DEL PRODUCTO',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'CODIGO O INDICADOR DEL PRODUCTO',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'COD_KMODALIDAD'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'COD_KMODALIDAD',
		 'EN',
		 'PRODUCT CODE OR INDICATOR',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'PRODUCT CODE OR INDICATOR',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'COD_KMODALIDAD'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'COD_RAMO', 'ES', 'RAMO', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO = 'RAMO', COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'COD_RAMO'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'COD_RAMO', 'EN', 'BUSINESS LINE', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO = 'BUSINESS LINE', COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'COD_RAMO'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('A1004802', 'COD_SOCIEDAD', 'ES', 'CODIGO SOCIEDAD FINANCIERA', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'CODIGO SOCIEDAD FINANCIERA',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'A1004802'
		   AND NOM_COLUMNA = 'COD_SOCIEDAD'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('A1004802', 'COD_SOCIEDAD', 'EN', 'FINNACIAL SOCIETY', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO = 'FINNACIAL SOCIETY', COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'A1004802'
		   AND NOM_COLUMNA = 'COD_SOCIEDAD'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'COD_USR', 'ES', 'USUARIO QUE ACTUALIZO LA FILA', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'USUARIO QUE ACTUALIZO LA FILA',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'COD_USR'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'COD_USR', 'EN', 'USER THAT UPDATED ROW', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'USER THAT UPDATED ROW',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'COD_USR'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'FEC_ACTU',
		 'ES',
		 'FECHA DE ACTUALIZACION DE LA FILA',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'FECHA DE ACTUALIZACION DE LA FILA',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'FEC_ACTU'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'FEC_ACTU', 'EN', 'ROW UPDATE DATE', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO = 'ROW UPDATE DATE', COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'FEC_ACTU'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'NUM_AJVALPC1',
		 'ES',
		 'AJUSTE EN PORCENTAJE APLICADO A LAS TABLAS DE VALORACION',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'AJUSTE EN PORCENTAJE APLICADO A LAS TABLAS DE VALORACION',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'NUM_AJVALPC1'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'NUM_AJVALPC1',
		 'EN',
		 'PERCENTAGE ADJUSTMENT APPLIED TO THE ASSESSMENT TABLES',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'PERCENTAGE ADJUSTMENT APPLIED TO THE ASSESSMENT TABLES',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'NUM_AJVALPC1'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'NUM_AJVALY1',
		 'ES',
		 'AJUSTE EN AÑOS APLICADO A LAS TABLAS DE VALORACION',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'AJUSTE EN AÑOS APLICADO A LAS TABLAS DE VALORACION',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'NUM_AJVALY1'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'NUM_AJVALY1',
		 'EN',
		 'ADJUSTMENT IN YEARS APPLIED TO THE ASSESSMENT TABLES',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'ADJUSTMENT IN YEARS APPLIED TO THE ASSESSMENT TABLES',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'NUM_AJVALY1'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'NUM_POREVALCAP',
		 'ES',
		 'PORCENTAJE DE REVALORIZACION DEL CAPITAL',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'PORCENTAJE DE REVALORIZACION DEL CAPITAL',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'NUM_POREVALCAP'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'NUM_POREVALCAP',
		 'EN',
		 'CAPITAL APPRECIATION PERCENTAGE',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'CAPITAL APPRECIATION PERCENTAGE',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'NUM_POREVALCAP'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'NUM_PREVPRIMA',
		 'ES',
		 'PORCENTAJE DE REVALORIZACION DE LA PRIMA SEGUN LA GARANTIA',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'PORCENTAJE DE REVALORIZACION DE LA PRIMA SEGUN LA GARANTIA',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'NUM_PREVPRIMA'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'NUM_PREVPRIMA',
		 'EN',
		 'PERCENTAGE REVALUATION OF THE PREMIUM ACCORDING TO THE GUARANTEE',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'PERCENTAGE REVALUATION OF THE PREMIUM ACCORDING TO THE GUARANTEE',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'NUM_PREVPRIMA'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'NUM_TASA1', 'ES', '% TASA FIJA DE LA GARANTIA', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = '% TASA FIJA DE LA GARANTIA',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'NUM_TASA1'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'NUM_TASA1', 'EN', '% FIXED RATE OF THE GUARANTEE', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = '% FIXED RATE OF THE GUARANTEE',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'NUM_TASA1'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'TXT_CFORMAREVCAP',
		 'ES',
		 'TIPO DE REVALORIZACION DEL CAPITAL',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'TIPO DE REVALORIZACION DEL CAPITAL',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_CFORMAREVCAP'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'TXT_CFORMAREVCAP',
		 'EN',
		 'TYPE OF CAPITAL APPRECIATION',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'TYPE OF CAPITAL APPRECIATION',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_CFORMAREVCAP'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'TXT_CFORMAREVPRIM',
		 'ES',
		 'TIPO DE CRECIMIENTO DE LA PRIMA SEGUN LA GARANTIA',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'TIPO DE CRECIMIENTO DE LA PRIMA SEGUN LA GARANTIA',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_CFORMAREVPRIM'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'TXT_CFORMAREVPRIM',
		 'EN',
		 'TYPE OF PREMIUM GROWTH ACCORDING TO THE GUARANTEE',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'TYPE OF PREMIUM GROWTH ACCORDING TO THE GUARANTEE',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_CFORMAREVPRIM'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'TXT_CTIPODUR',
		 'ES',
		 'TIPO DE DURACION DE LA GARANTIA',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'TIPO DE DURACION DE LA GARANTIA',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_CTIPODUR'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'TXT_CTIPODUR', 'EN', 'TYPE OF WARRANTY DURATION', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'TYPE OF WARRANTY DURATION',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_CTIPODUR'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'TXT_CTIPOPROVI',
		 'ES',
		 'TIPO DE PROVISION LOCAL POR GARANTIA',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'TIPO DE PROVISION LOCAL POR GARANTIA',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_CTIPOPROVI'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'TXT_CTIPOPROVI',
		 'EN',
		 'TYPE OF LOCAL PROVISION FOR GUARANTEE',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'TYPE OF LOCAL PROVISION FOR GUARANTEE',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_CTIPOPROVI'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'TXT_KPRESTACION',
		 'ES',
		 'TIPO DE PRESTACION ASEGURADA DE LA GARANTIA',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'TIPO DE PRESTACION ASEGURADA DE LA GARANTIA',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_KPRESTACION'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'TXT_KPRESTACION',
		 'EN',
		 'TYPE OF GUARANTEED GUARANTEE BENEFIT',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'TYPE OF GUARANTEED GUARANTEE BENEFIT',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_KPRESTACION'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'TXT_PB', 'ES', 'INDICADOR DE PB', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO = 'INDICADOR DE PB', COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_PB'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA', 'TXT_PB', 'EN', 'PB INDICATOR', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO = 'PB INDICATOR', COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_PB'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'TXT_SPCOM',
		 'ES',
		 'INDICADOR DE GARANTIA PRINCIPAL / SECUNDARIA',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'INDICADOR DE GARANTIA PRINCIPAL / SECUNDARIA',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_SPCOM'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'TXT_SPCOM',
		 'EN',
		 'PRIMARY / SECONDARY WARRANTY INDICATOR',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'PRIMARY / SECONDARY WARRANTY INDICATOR',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_SPCOM'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'TXT_TABLA1',
		 'ES',
		 'TABLA BASE DE VALORACION DE LA GARANTIA',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'TABLA BASE DE VALORACION DE LA GARANTIA',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_TABLA1'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'TXT_TABLA1',
		 'EN',
		 'BASIS TABLE OF VALUATION OF THE GUARANTEE',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'BASIS TABLE OF VALUATION OF THE GUARANTEE',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TXT_TABLA1'
		   AND COD_IDIOMA = 'EN';
	END;
END;
/