-----------------------------------------------------------
---MAPFRE DGTP - MODELO DE DATOS                        ---
-----------------------------------------------------------
---Nº PETICIÓN:       RF00576093-SD01987131
---SOLICITADA POR:    BLAZQUF
---OBJETOS AFECTADOS: A1004807, GENERICA
---PROYECTO:          TRN_TRON
---ENTORNO:           WDMD04
---REALIZADO POR:     HLJUANJ
---TIPOLOGIA:         REENTRANTE
-----------------------------------------------------------

BEGIN

  BEGIN
    INSERT INTO TRON2000.TRN_COMENTARIO_TABLAS
      (NOM_TABLA,
       COD_IDIOMA,
       TXT_COMENTARIO,
       COD_USR_REVISION,
       VAL_ESTADO_COLUMNAS)
    VALUES
      ('A1004807',
       'ES',
       'NIIF 17 TRANSACCIONES FINANCIERAS FPSL',
       'SMD',
       'TOTAL');
  EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
      UPDATE TRON2000.TRN_COMENTARIO_TABLAS
         SET TXT_COMENTARIO      = 'NIIF 17 TRANSACCIONES FINANCIERAS FPSL',
             COD_USR_REVISION    = 'SMD',
             VAL_ESTADO_COLUMNAS = 'TOTAL'
       WHERE NOM_TABLA = 'A1004807'
         AND COD_IDIOMA = 'ES';
  END;
  BEGIN
    INSERT INTO TRON2000.TRN_COMENTARIO_TABLAS
      (NOM_TABLA,
       COD_IDIOMA,
       TXT_COMENTARIO,
       COD_USR_REVISION,
       VAL_ESTADO_COLUMNAS)
    VALUES
      ('A1004807',
       'EN',
       'IFRS 17 FPSL FINANCIAL TRANSACTIONS',
       'SMD',
       'TOTAL');
  EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
      UPDATE TRON2000.TRN_COMENTARIO_TABLAS
         SET TXT_COMENTARIO      = 'IFRS 17 FPSL FINANCIAL TRANSACTIONS',
             COD_USR_REVISION    = 'SMD',
             VAL_ESTADO_COLUMNAS = 'TOTAL'
       WHERE NOM_TABLA = 'A1004807'
         AND COD_IDIOMA = 'EN';
  END;
  
  BEGIN
    INSERT
    INTO TRON2000.TRN_COMENTARIO_COLUMNAS
      (
        NOM_TABLA,
        NOM_COLUMNA,
        COD_IDIOMA,
        TXT_COMENTARIO,
        COD_USR_REVISION
      )
      VALUES
      (
        'GENERICA',
        'COD_AGRUP_BT',
        'ES',
        'CODIGO AGRUPADOR TRANSACCION FINANCIERA',
        'SMD'
      );
  EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
    SET TXT_COMENTARIO = 'CODIGO AGRUPADOR TRANSACCION FINANCIERA',
      COD_USR_REVISION = 'SMD'
    WHERE NOM_TABLA    = 'GENERICA'
    AND NOM_COLUMNA    = 'COD_AGRUP_BT'
    AND COD_IDIOMA     = 'ES';
  END;
  BEGIN
    INSERT
    INTO TRON2000.TRN_COMENTARIO_COLUMNAS
      (
        NOM_TABLA,
        NOM_COLUMNA,
        COD_IDIOMA,
        TXT_COMENTARIO,
        COD_USR_REVISION
      )
      VALUES
      (
        'GENERICA',
        'COD_AGRUP_BT',
        'EN',
        'FINANCIAL TRANSACTION GROUPING CODE',
        'SMD'
      );
  EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
    SET TXT_COMENTARIO = 'FINANCIAL TRANSACTION GROUPING CODE',
      COD_USR_REVISION = 'SMD'
    WHERE NOM_TABLA    = 'GENERICA'
    AND NOM_COLUMNA    = 'COD_AGRUP_BT'
    AND COD_IDIOMA     = 'EN';
  END;
  BEGIN
    INSERT
    INTO TRON2000.TRN_COMENTARIO_COLUMNAS
      (
        NOM_TABLA,
        NOM_COLUMNA,
        COD_IDIOMA,
        TXT_COMENTARIO,
        COD_USR_REVISION
      )
      VALUES
      (
        'GENERICA',
        'COD_OPERACION',
        'ES',
        'CODIGO OPERACION',
        'SMD'
      );
  EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
    SET TXT_COMENTARIO = 'CODIGO OPERACION',
      COD_USR_REVISION = 'SMD'
    WHERE NOM_TABLA    = 'GENERICA'
    AND NOM_COLUMNA    = 'COD_OPERACION'
    AND COD_IDIOMA     = 'ES';
  END;
  BEGIN
    INSERT
    INTO TRON2000.TRN_COMENTARIO_COLUMNAS
      (
        NOM_TABLA,
        NOM_COLUMNA,
        COD_IDIOMA,
        TXT_COMENTARIO,
        COD_USR_REVISION
      )
      VALUES
      (
        'GENERICA',
        'COD_OPERACION',
        'EN',
        'OPERATING CODE',
        'SMD'
      );
  EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
    SET TXT_COMENTARIO = 'OPERATING CODE',
      COD_USR_REVISION = 'SMD'
    WHERE NOM_TABLA    = 'GENERICA'
    AND NOM_COLUMNA    = 'COD_OPERACION'
    AND COD_IDIOMA     = 'EN';
  END;
  BEGIN
    INSERT
    INTO TRON2000.TRN_COMENTARIO_COLUMNAS
      (
        NOM_TABLA,
        NOM_COLUMNA,
        COD_IDIOMA,
        TXT_COMENTARIO,
        COD_USR_REVISION
      )
      VALUES
      (
        'GENERICA',
        'NOM_PRG_OBTIENE_DATOS',
        'ES',
        'NOMBRE DEL PROGRAMA QUE OBTIENE LOS DATOS',
        'SMD'
      );
  EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
    SET TXT_COMENTARIO = 'NOMBRE DEL PROGRAMA QUE OBTIENE LOS DATOS',
      COD_USR_REVISION = 'SMD'
    WHERE NOM_TABLA    = 'GENERICA'
    AND NOM_COLUMNA    = 'NOM_PRG_OBTIENE_DATOS'
    AND COD_IDIOMA     = 'ES';
  END;
  BEGIN
    INSERT
    INTO TRON2000.TRN_COMENTARIO_COLUMNAS
      (
        NOM_TABLA,
        NOM_COLUMNA,
        COD_IDIOMA,
        TXT_COMENTARIO,
        COD_USR_REVISION
      )
      VALUES
      (
        'GENERICA',
        'NOM_PRG_OBTIENE_DATOS',
        'EN',
        'NAME OF THE PROGRAM THAT OBTAINS THE DATA',
        'SMD'
      );
  EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
    SET TXT_COMENTARIO = 'NAME OF THE PROGRAM THAT OBTAINS THE DATA',
      COD_USR_REVISION = 'SMD'
    WHERE NOM_TABLA    = 'GENERICA'
    AND NOM_COLUMNA    = 'NOM_PRG_OBTIENE_DATOS'
    AND COD_IDIOMA     = 'EN';
  END;
  BEGIN
    INSERT
    INTO TRON2000.TRN_COMENTARIO_COLUMNAS
      (
        NOM_TABLA,
        NOM_COLUMNA,
        COD_IDIOMA,
        TXT_COMENTARIO,
        COD_USR_REVISION
      )
      VALUES
      (
        'GENERICA',
        'COD_SUB_AGRUP_BT',
        'ES',
        'SUBCODIGO AGRUPADOR TRANSACCION FINANCIERA',
        'SMD'
      );
  EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
    SET TXT_COMENTARIO = 'SUBCODIGO AGRUPADOR TRANSACCION FINANCIERA',
      COD_USR_REVISION = 'SMD'
    WHERE NOM_TABLA    = 'GENERICA'
    AND NOM_COLUMNA    = 'COD_SUB_AGRUP_BT'
    AND COD_IDIOMA     = 'ES';
  END;
  BEGIN
    INSERT
    INTO TRON2000.TRN_COMENTARIO_COLUMNAS
      (
        NOM_TABLA,
        NOM_COLUMNA,
        COD_IDIOMA,
        TXT_COMENTARIO,
        COD_USR_REVISION
      )
      VALUES
      (
        'GENERICA',
        'COD_SUB_AGRUP_BT',
        'EN',
        'FINANCIAL TRANSACTION SUBGROUPING CODE',
        'SMD'
      );
  EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
    SET TXT_COMENTARIO = 'FINANCIAL TRANSACTION SUBGROUPING CODE',
      COD_USR_REVISION = 'SMD'
    WHERE NOM_TABLA    = 'GENERICA'
    AND NOM_COLUMNA    = 'COD_SUB_AGRUP_BT'
    AND COD_IDIOMA     = 'EN';
  END;

END;
/