-----------------------------------------------------------
---MAPFRE DGTP - MODELO DE DATOS                        ---
-----------------------------------------------------------
---Nº PETICIÓN:       RF00576093-SD01987131
---SOLICITADA POR:    BLAZQUF
---OBJETOS AFECTADOS: A1004805, GENERICA
---PROYECTO:          TRN_TRON
---ENTORNO:           WDMD04
---REALIZADO POR:     HLJUANJ
---TIPOLOGIA:         REENTRANTE
-----------------------------------------------------------

BEGIN
  BEGIN
    INSERT INTO TRON2000.TRN_COMENTARIO_TABLAS
      (NOM_TABLA,
       COD_IDIOMA,
       TXT_COMENTARIO,
       COD_USR_REVISION,
       VAL_ESTADO_COLUMNAS)
    VALUES
      ('A1004805',
       'ES',
       'NIIF 17 DEFINICION CARTERAS FPSL',
       'SMD',
       'TOTAL');
  EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
      UPDATE TRON2000.TRN_COMENTARIO_TABLAS
         SET TXT_COMENTARIO      = 'NIIF 17 DEFINICION CARTERAS FPSL',
             COD_USR_REVISION    = 'SMD',
             VAL_ESTADO_COLUMNAS = 'TOTAL'
       WHERE NOM_TABLA = 'A1004805'
         AND COD_IDIOMA = 'ES';
  END;
  BEGIN
    INSERT INTO TRON2000.TRN_COMENTARIO_TABLAS
      (NOM_TABLA,
       COD_IDIOMA,
       TXT_COMENTARIO,
       COD_USR_REVISION,
       VAL_ESTADO_COLUMNAS)
    VALUES
      ('A1004805',
       'EN',
       'IFRS 17 DEFINITION OF FPSL PORTFOLIOS',
       'SMD',
       'TOTAL');
  EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
      UPDATE TRON2000.TRN_COMENTARIO_TABLAS
         SET TXT_COMENTARIO      = 'IFRS 17 DEFINITION OF FPSL PORTFOLIOS',
             COD_USR_REVISION    = 'SMD',
             VAL_ESTADO_COLUMNAS = 'TOTAL'
       WHERE NOM_TABLA = 'A1004805'
         AND COD_IDIOMA = 'EN';
  END;
  BEGIN
    INSERT
    INTO TRON2000.TRN_COMENTARIO_COLUMNAS
      (
        NOM_TABLA,
        NOM_COLUMNA,
        COD_IDIOMA,
        TXT_COMENTARIO,
        COD_USR_REVISION
      )
      VALUES
      (
        'GENERICA',
        'COD_CARTERA',
        'ES',
        'CODIGO UNICO DE IDENTIFICACION DEL CONTRATO',
        'SMD'
      );
  EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
    SET TXT_COMENTARIO = 'CODIGO UNICO DE IDENTIFICACION DEL CONTRATO',
      COD_USR_REVISION = 'SMD'
    WHERE NOM_TABLA    = 'GENERICA'
    AND NOM_COLUMNA    = 'COD_CARTERA'
    AND COD_IDIOMA     = 'ES';
  END;
  BEGIN
    INSERT
    INTO TRON2000.TRN_COMENTARIO_COLUMNAS
      (
        NOM_TABLA,
        NOM_COLUMNA,
        COD_IDIOMA,
        TXT_COMENTARIO,
        COD_USR_REVISION
      )
      VALUES
      (
        'GENERICA',
        'COD_CARTERA',
        'EN',
        'UNIQUE CONTRACT IDENTIFICATION CODE',
        'SMD'
      );
  EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
    SET TXT_COMENTARIO = 'UNIQUE CONTRACT IDENTIFICATION CODE',
      COD_USR_REVISION = 'SMD'
    WHERE NOM_TABLA    = 'GENERICA'
    AND NOM_COLUMNA    = 'COD_CARTERA'
    AND COD_IDIOMA     = 'EN';
  END;
  BEGIN
    INSERT
    INTO TRON2000.TRN_COMENTARIO_COLUMNAS
      (
        NOM_TABLA,
        NOM_COLUMNA,
        COD_IDIOMA,
        TXT_COMENTARIO,
        COD_USR_REVISION
      )
      VALUES
      (
        'A1004805',
        'COD_COHORTE',
        'ES',
        'CODIGO DE LA UNIT OF ACCOUNT A LA QUE SE ASIGNA EL CONTRATO',
        'SMD'
      );
  EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
    SET TXT_COMENTARIO = 'CODIGO DE LA UNIT OF ACCOUNT A LA QUE SE ASIGNA EL CONTRATO',
      COD_USR_REVISION = 'SMD'
    WHERE NOM_TABLA    = 'A1004805'
    AND NOM_COLUMNA    = 'COD_COHORTE'
    AND COD_IDIOMA     = 'ES';
  END;
  BEGIN
    INSERT
    INTO TRON2000.TRN_COMENTARIO_COLUMNAS
      (
        NOM_TABLA,
        NOM_COLUMNA,
        COD_IDIOMA,
        TXT_COMENTARIO,
        COD_USR_REVISION
      )
      VALUES
      (
        'A1004805',
        'COD_COHORTE',
        'EN',
        'CODE OF THE UNIT OF ACCOUNT TO WHICH THE CONTRACT IS ASSIGNED',
        'SMD'
      );
  EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
    SET TXT_COMENTARIO = 'CODE OF THE UNIT OF ACCOUNT TO WHICH THE CONTRACT IS ASSIGNED',
      COD_USR_REVISION = 'SMD'
    WHERE NOM_TABLA    = 'A1004805'
    AND NOM_COLUMNA    = 'COD_COHORTE'
    AND COD_IDIOMA     = 'EN';
  END;
  BEGIN
    INSERT
    INTO TRON2000.TRN_COMENTARIO_COLUMNAS
      (
        NOM_TABLA,
        NOM_COLUMNA,
        COD_IDIOMA,
        TXT_COMENTARIO,
        COD_USR_REVISION
      )
      VALUES
      (
        'A1004805',
        'COD_SOCIEDAD',
        'ES',
        'CODIGO SOCIEDAD FINANCIERA',
        'SMD'
      );
  EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
    SET TXT_COMENTARIO = 'CODIGO SOCIEDAD FINANCIERA',
      COD_USR_REVISION = 'SMD'
    WHERE NOM_TABLA    = 'A1004805'
    AND NOM_COLUMNA    = 'COD_SOCIEDAD'
    AND COD_IDIOMA     = 'ES';
  END;
  BEGIN
    INSERT
    INTO TRON2000.TRN_COMENTARIO_COLUMNAS
      (
        NOM_TABLA,
        NOM_COLUMNA,
        COD_IDIOMA,
        TXT_COMENTARIO,
        COD_USR_REVISION
      )
      VALUES
      (
        'A1004805',
        'COD_SOCIEDAD',
        'EN',
        'FINNANCIALS SOCIETY',
        'SMD'
      );
  EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
    SET TXT_COMENTARIO = 'FINNANCIALS SOCIETY',
      COD_USR_REVISION = 'SMD'
    WHERE NOM_TABLA    = 'A1004805'
    AND NOM_COLUMNA    = 'COD_SOCIEDAD'
    AND COD_IDIOMA     = 'EN';
  END;
  BEGIN
    INSERT
    INTO TRON2000.TRN_COMENTARIO_COLUMNAS
      (
        NOM_TABLA,
        NOM_COLUMNA,
        COD_IDIOMA,
        TXT_COMENTARIO,
        COD_USR_REVISION
      )
      VALUES
      (
        'GENERICA',
        'COD_USR',
        'ES',
        'USUARIO QUE ACTUALIZO LA FILA',
        'SMD'
      );
  EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
    SET TXT_COMENTARIO = 'USUARIO QUE ACTUALIZO LA FILA',
      COD_USR_REVISION = 'SMD'
    WHERE NOM_TABLA    = 'GENERICA'
    AND NOM_COLUMNA    = 'COD_USR'
    AND COD_IDIOMA     = 'ES';
  END;
  BEGIN
    INSERT
    INTO TRON2000.TRN_COMENTARIO_COLUMNAS
      (
        NOM_TABLA,
        NOM_COLUMNA,
        COD_IDIOMA,
        TXT_COMENTARIO,
        COD_USR_REVISION
      )
      VALUES
      (
        'GENERICA',
        'COD_USR',
        'EN',
        'USER THAT UPDATED ROW',
        'SMD'
      );
  EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
    SET TXT_COMENTARIO = 'USER THAT UPDATED ROW',
      COD_USR_REVISION = 'SMD'
    WHERE NOM_TABLA    = 'GENERICA'
    AND NOM_COLUMNA    = 'COD_USR'
    AND COD_IDIOMA     = 'EN';
  END;
  BEGIN
    INSERT
    INTO TRON2000.TRN_COMENTARIO_COLUMNAS
      (
        NOM_TABLA,
        NOM_COLUMNA,
        COD_IDIOMA,
        TXT_COMENTARIO,
        COD_USR_REVISION
      )
      VALUES
      (
        'GENERICA',
        'FEC_ACTU',
        'ES',
        'FECHA DE ACTUALIZACION DE LA FILA',
        'SMD'
      );
  EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
    SET TXT_COMENTARIO = 'FECHA DE ACTUALIZACION DE LA FILA',
      COD_USR_REVISION = 'SMD'
    WHERE NOM_TABLA    = 'GENERICA'
    AND NOM_COLUMNA    = 'FEC_ACTU'
    AND COD_IDIOMA     = 'ES';
  END;
  BEGIN
    INSERT
    INTO TRON2000.TRN_COMENTARIO_COLUMNAS
      (
        NOM_TABLA,
        NOM_COLUMNA,
        COD_IDIOMA,
        TXT_COMENTARIO,
        COD_USR_REVISION
      )
      VALUES
      (
        'GENERICA',
        'FEC_ACTU',
        'EN',
        'ROW UPDATE DATE',
        'SMD'
      );
  EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
    SET TXT_COMENTARIO = 'ROW UPDATE DATE',
      COD_USR_REVISION = 'SMD'
    WHERE NOM_TABLA    = 'GENERICA'
    AND NOM_COLUMNA    = 'FEC_ACTU'
    AND COD_IDIOMA     = 'EN';
  END;
  BEGIN
    INSERT
    INTO TRON2000.TRN_COMENTARIO_COLUMNAS
      (
        NOM_TABLA,
        NOM_COLUMNA,
        COD_IDIOMA,
        TXT_COMENTARIO,
        COD_USR_REVISION
      )
      VALUES
      (
        'GENERICA',
        'FEC_VALIDEZ',
        'ES',
        'FECHA DE VALIDEZ',
        'SMD'
      );
  EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
    SET TXT_COMENTARIO = 'FECHA DE VALIDEZ',
      COD_USR_REVISION = 'SMD'
    WHERE NOM_TABLA    = 'GENERICA'
    AND NOM_COLUMNA    = 'FEC_VALIDEZ'
    AND COD_IDIOMA     = 'ES';
  END;
  BEGIN
    INSERT
    INTO TRON2000.TRN_COMENTARIO_COLUMNAS
      (
        NOM_TABLA,
        NOM_COLUMNA,
        COD_IDIOMA,
        TXT_COMENTARIO,
        COD_USR_REVISION
      )
      VALUES
      (
        'GENERICA',
        'FEC_VALIDEZ',
        'EN',
        'VALIDITY DATE',
        'SMD'
      );
  EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
    SET TXT_COMENTARIO = 'VALIDITY DATE',
      COD_USR_REVISION = 'SMD'
    WHERE NOM_TABLA    = 'GENERICA'
    AND NOM_COLUMNA    = 'FEC_VALIDEZ'
    AND COD_IDIOMA     = 'EN';
  END;
  BEGIN
    INSERT
    INTO TRON2000.TRN_COMENTARIO_COLUMNAS
      (
        NOM_TABLA,
        NOM_COLUMNA,
        COD_IDIOMA,
        TXT_COMENTARIO,
        COD_USR_REVISION
      )
      VALUES
      (
        'GENERICA',
        'TXT_CARTERA_INM',
        'ES',
        'CAMPO QUE INDIQUE SI LA POLIZA ESTA O NO EN UNA CARTERA INMUNIZADA',
        'SMD'
      );
  EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
    SET TXT_COMENTARIO = 'CAMPO QUE INDIQUE SI LA POLIZA ESTA O NO EN UNA CARTERA INMUNIZADA',
      COD_USR_REVISION = 'SMD'
    WHERE NOM_TABLA    = 'GENERICA'
    AND NOM_COLUMNA    = 'TXT_CARTERA_INM'
    AND COD_IDIOMA     = 'ES';
  END;
  BEGIN
    INSERT
    INTO TRON2000.TRN_COMENTARIO_COLUMNAS
      (
        NOM_TABLA,
        NOM_COLUMNA,
        COD_IDIOMA,
        TXT_COMENTARIO,
        COD_USR_REVISION
      )
      VALUES
      (
        'GENERICA',
        'TXT_CARTERA_INM',
        'EN',
        'FIELD INDICATING WHETHER OR NOT THE POLICY IS IN AN IMMUNIZED PORTFOLIO',
        'SMD'
      );
  EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
    SET TXT_COMENTARIO = 'FIELD INDICATING WHETHER OR NOT THE POLICY IS IN AN IMMUNIZED PORTFOLIO',
      COD_USR_REVISION = 'SMD'
    WHERE NOM_TABLA    = 'GENERICA'
    AND NOM_COLUMNA    = 'TXT_CARTERA_INM'
    AND COD_IDIOMA     = 'EN';
  END;
  BEGIN
    INSERT
    INTO TRON2000.TRN_COMENTARIO_COLUMNAS
      (
        NOM_TABLA,
        NOM_COLUMNA,
        COD_IDIOMA,
        TXT_COMENTARIO,
        COD_USR_REVISION
      )
      VALUES
      (
        'GENERICA',
        'TXT_MET_VAL',
        'ES',
        'CODIGO QUE IDENTIFICA EL METODO DE VALORACION DEL CONTRATO BAJO NIIF 17',
        'SMD'
      );
  EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
    SET TXT_COMENTARIO = 'CODIGO QUE IDENTIFICA EL METODO DE VALORACION DEL CONTRATO BAJO NIIF 17',
      COD_USR_REVISION = 'SMD'
    WHERE NOM_TABLA    = 'GENERICA'
    AND NOM_COLUMNA    = 'TXT_MET_VAL'
    AND COD_IDIOMA     = 'ES';
  END;
  BEGIN
    INSERT
    INTO TRON2000.TRN_COMENTARIO_COLUMNAS
      (
        NOM_TABLA,
        NOM_COLUMNA,
        COD_IDIOMA,
        TXT_COMENTARIO,
        COD_USR_REVISION
      )
      VALUES
      (
        'GENERICA',
        'TXT_MET_VAL',
        'EN',
        'CODE THAT IDENTIFIES THE METHOD OF VALUATION OF THE CONTRACT UNDER IFRS 17',
        'SMD'
      );
  EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
    SET TXT_COMENTARIO = 'CODE THAT IDENTIFIES THE METHOD OF VALUATION OF THE CONTRACT UNDER IFRS 17',
      COD_USR_REVISION = 'SMD'
    WHERE NOM_TABLA    = 'GENERICA'
    AND NOM_COLUMNA    = 'TXT_MET_VAL'
    AND COD_IDIOMA     = 'EN';
  END;
  BEGIN
    INSERT
    INTO TRON2000.TRN_COMENTARIO_COLUMNAS
      (
        NOM_TABLA,
        NOM_COLUMNA,
        COD_IDIOMA,
        TXT_COMENTARIO,
        COD_USR_REVISION
      )
      VALUES
      (
        'GENERICA',
        'TXT_ONE',
        'ES',
        'ONEROSIDAD POR UNIT OF ACCOUNT SEGUN DIRECTRICES MARCADAS POR MAPFRE GRUPO.',
        'SMD'
      );
  EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
    SET TXT_COMENTARIO = 'ONEROSIDAD POR UNIT OF ACCOUNT SEGUN DIRECTRICES MARCADAS POR MAPFRE GRUPO.',
      COD_USR_REVISION = 'SMD'
    WHERE NOM_TABLA    = 'GENERICA'
    AND NOM_COLUMNA    = 'TXT_ONE'
    AND COD_IDIOMA     = 'ES';
  END;
  BEGIN
    INSERT
    INTO TRON2000.TRN_COMENTARIO_COLUMNAS
      (
        NOM_TABLA,
        NOM_COLUMNA,
        COD_IDIOMA,
        TXT_COMENTARIO,
        COD_USR_REVISION
      )
      VALUES
      (
        'GENERICA',
        'TXT_ONE',
        'EN',
        'ONEROSITY PER UNIT OF ACCOUNT ACCORDING TO GUIDELINES SET BY MAPFRE GROUP.',
        'SMD'
      );
  EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
    SET TXT_COMENTARIO = 'ONEROSITY PER UNIT OF ACCOUNT ACCORDING TO GUIDELINES SET BY MAPFRE GROUP.',
      COD_USR_REVISION = 'SMD'
    WHERE NOM_TABLA    = 'GENERICA'
    AND NOM_COLUMNA    = 'TXT_ONE'
    AND COD_IDIOMA     = 'EN';
  END;
END;
/