-----------------------------------------------------------
---MAPFRE DGTP - MODELO DE DATOS                        ---
-----------------------------------------------------------
---Nº PETICIÓN:       RF00576093-SD01987131
---SOLICITADA POR:    BLAZQUF
---OBJETOS AFECTADOS: A1004806, GENERICA
---PROYECTO:          TRN_TRON
---ENTORNO:           WDMD04
---REALIZADO POR:     HLJUANJ
---TIPOLOGIA:         REENTRANTE
-----------------------------------------------------------

BEGIN
  BEGIN
    INSERT INTO TRON2000.TRN_COMENTARIO_TABLAS
      (NOM_TABLA,
       COD_IDIOMA,
       TXT_COMENTARIO,
       COD_USR_REVISION,
       VAL_ESTADO_COLUMNAS)
    VALUES
      ('A1004806',
       'ES',
       'NIIF 17 ASIGNACION CARTERAS FPSL',
       'SMD',
       'TOTAL');
  EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
      UPDATE TRON2000.TRN_COMENTARIO_TABLAS
         SET TXT_COMENTARIO      = 'NIIF 17 ASIGNACION CARTERAS FPSL',
             COD_USR_REVISION    = 'SMD',
             VAL_ESTADO_COLUMNAS = 'TOTAL'
       WHERE NOM_TABLA = 'A1004806'
         AND COD_IDIOMA = 'ES';
  END;
  BEGIN
    INSERT INTO TRON2000.TRN_COMENTARIO_TABLAS
      (NOM_TABLA,
       COD_IDIOMA,
       TXT_COMENTARIO,
       COD_USR_REVISION,
       VAL_ESTADO_COLUMNAS)
    VALUES
      ('A1004806',
       'EN',
       'IFRS 17 ALLOCATION OF FPSL PORTFOLIOS',
       'SMD',
       'TOTAL');
  EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
      UPDATE TRON2000.TRN_COMENTARIO_TABLAS
         SET TXT_COMENTARIO      = 'IFRS 17 ALLOCATION OF FPSL PORTFOLIOS',
             COD_USR_REVISION    = 'SMD',
             VAL_ESTADO_COLUMNAS = 'TOTAL'
       WHERE NOM_TABLA = 'A1004806'
         AND COD_IDIOMA = 'EN';
  END;
BEGIN
  INSERT
  INTO TRON2000.TRN_COMENTARIO_COLUMNAS
    (
      NOM_TABLA,
      NOM_COLUMNA,
      COD_IDIOMA,
      TXT_COMENTARIO,
      COD_USR_REVISION
    )
    VALUES
    (
      'A1004806',
      'COD_CARTERA',
      'ES',
      'DATO CON EL QUE SE IDENTIFICA LA CARTERA IFRS 17 A LA CUAL PERTENECE EL CONTRATO',
      'SMD'
    );
EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
  UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
  SET TXT_COMENTARIO = 'DATO CON EL QUE SE IDENTIFICA LA CARTERA IFRS 17 A LA CUAL PERTENECE EL CONTRATO',
    COD_USR_REVISION = 'SMD'
  WHERE NOM_TABLA    = 'A1004806'
  AND NOM_COLUMNA    = 'COD_CARTERA'
  AND COD_IDIOMA     = 'ES';
END;
BEGIN
  INSERT
  INTO TRON2000.TRN_COMENTARIO_COLUMNAS
    (
      NOM_TABLA,
      NOM_COLUMNA,
      COD_IDIOMA,
      TXT_COMENTARIO,
      COD_USR_REVISION
    )
    VALUES
    (
      'A1004806',
      'COD_CARTERA',
      'EN',
      'DATA WITH WHICH THE IFRS 17 PORTFOLIO IS IDENTIFIED TO WHICH THE CONTRACT BELONGS',
      'SMD'
    );
EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
  UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
  SET TXT_COMENTARIO = 'DATA WITH WHICH THE IFRS 17 PORTFOLIO IS IDENTIFIED TO WHICH THE CONTRACT BELONGS',
    COD_USR_REVISION = 'SMD'
  WHERE NOM_TABLA    = 'A1004806'
  AND NOM_COLUMNA    = 'COD_CARTERA'
  AND COD_IDIOMA     = 'EN';
END;
BEGIN
  INSERT
  INTO TRON2000.TRN_COMENTARIO_COLUMNAS
    (
      NOM_TABLA,
      NOM_COLUMNA,
      COD_IDIOMA,
      TXT_COMENTARIO,
      COD_USR_REVISION
    )
    VALUES
    (
      'GENERICA',
      'COD_COB',
      'ES',
      'COBERTURA',
      'SMD'
    );
EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
  UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
  SET TXT_COMENTARIO = 'COBERTURA',
    COD_USR_REVISION = 'SMD'
  WHERE NOM_TABLA    = 'GENERICA'
  AND NOM_COLUMNA    = 'COD_COB'
  AND COD_IDIOMA     = 'ES';
END;
BEGIN
  INSERT
  INTO TRON2000.TRN_COMENTARIO_COLUMNAS
    (
      NOM_TABLA,
      NOM_COLUMNA,
      COD_IDIOMA,
      TXT_COMENTARIO,
      COD_USR_REVISION
    )
    VALUES
    (
      'GENERICA',
      'COD_COB',
      'EN',
      'COVERAGE',
      'SMD'
    );
EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
  UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
  SET TXT_COMENTARIO = 'COVERAGE',
    COD_USR_REVISION = 'SMD'
  WHERE NOM_TABLA    = 'GENERICA'
  AND NOM_COLUMNA    = 'COD_COB'
  AND COD_IDIOMA     = 'EN';
END;
BEGIN
  INSERT
  INTO TRON2000.TRN_COMENTARIO_COLUMNAS
    (
      NOM_TABLA,
      NOM_COLUMNA,
      COD_IDIOMA,
      TXT_COMENTARIO,
      COD_USR_REVISION
    )
    VALUES
    (
      'GENERICA',
      'COD_KMODALIDAD',
      'ES',
      'CODIGO O INDICADOR DEL PRODUCTO',
      'SMD'
    );
EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
  UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
  SET TXT_COMENTARIO = 'CODIGO O INDICADOR DEL PRODUCTO',
    COD_USR_REVISION = 'SMD'
  WHERE NOM_TABLA    = 'GENERICA'
  AND NOM_COLUMNA    = 'COD_KMODALIDAD'
  AND COD_IDIOMA     = 'ES';
END;
BEGIN
  INSERT
  INTO TRON2000.TRN_COMENTARIO_COLUMNAS
    (
      NOM_TABLA,
      NOM_COLUMNA,
      COD_IDIOMA,
      TXT_COMENTARIO,
      COD_USR_REVISION
    )
    VALUES
    (
      'GENERICA',
      'COD_KMODALIDAD',
      'EN',
      'PRODUCT CODE OR INDICATOR',
      'SMD'
    );
EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
  UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
  SET TXT_COMENTARIO = 'PRODUCT CODE OR INDICATOR',
    COD_USR_REVISION = 'SMD'
  WHERE NOM_TABLA    = 'GENERICA'
  AND NOM_COLUMNA    = 'COD_KMODALIDAD'
  AND COD_IDIOMA     = 'EN';
END;
BEGIN
  INSERT
  INTO TRON2000.TRN_COMENTARIO_COLUMNAS
    (
      NOM_TABLA,
      NOM_COLUMNA,
      COD_IDIOMA,
      TXT_COMENTARIO,
      COD_USR_REVISION
    )
    VALUES
    (
      'GENERICA',
      'COD_RAMO',
      'ES',
      'RAMO',
      'SMD'
    );
EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
  UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
  SET TXT_COMENTARIO = 'RAMO',
    COD_USR_REVISION = 'SMD'
  WHERE NOM_TABLA    = 'GENERICA'
  AND NOM_COLUMNA    = 'COD_RAMO'
  AND COD_IDIOMA     = 'ES';
END;
BEGIN
  INSERT
  INTO TRON2000.TRN_COMENTARIO_COLUMNAS
    (
      NOM_TABLA,
      NOM_COLUMNA,
      COD_IDIOMA,
      TXT_COMENTARIO,
      COD_USR_REVISION
    )
    VALUES
    (
      'GENERICA',
      'COD_RAMO',
      'EN',
      'BUSINESS LINE',
      'SMD'
    );
EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
  UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
  SET TXT_COMENTARIO = 'BUSINESS LINE',
    COD_USR_REVISION = 'SMD'
  WHERE NOM_TABLA    = 'GENERICA'
  AND NOM_COLUMNA    = 'COD_RAMO'
  AND COD_IDIOMA     = 'EN';
END;
BEGIN
  INSERT
  INTO TRON2000.TRN_COMENTARIO_COLUMNAS
    (
      NOM_TABLA,
      NOM_COLUMNA,
      COD_IDIOMA,
      TXT_COMENTARIO,
      COD_USR_REVISION
    )
    VALUES
    (
      'GENERICA',
      'COD_RAMO_CTABLE',
      'ES',
      'RAMO CONTABLE',
      'SMD'
    );
EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
  UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
  SET TXT_COMENTARIO = 'RAMO CONTABLE',
    COD_USR_REVISION = 'SMD'
  WHERE NOM_TABLA    = 'GENERICA'
  AND NOM_COLUMNA    = 'COD_RAMO_CTABLE'
  AND COD_IDIOMA     = 'ES';
END;
BEGIN
  INSERT
  INTO TRON2000.TRN_COMENTARIO_COLUMNAS
    (
      NOM_TABLA,
      NOM_COLUMNA,
      COD_IDIOMA,
      TXT_COMENTARIO,
      COD_USR_REVISION
    )
    VALUES
    (
      'GENERICA',
      'COD_RAMO_CTABLE',
      'EN',
      'ACCOUNTING BUSINESS LINE ',
      'SMD'
    );
EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
  UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
  SET TXT_COMENTARIO = 'ACCOUNTING BUSINESS LINE ',
    COD_USR_REVISION = 'SMD'
  WHERE NOM_TABLA    = 'GENERICA'
  AND NOM_COLUMNA    = 'COD_RAMO_CTABLE'
  AND COD_IDIOMA     = 'EN';
END;
BEGIN
  INSERT
  INTO TRON2000.TRN_COMENTARIO_COLUMNAS
    (
      NOM_TABLA,
      NOM_COLUMNA,
      COD_IDIOMA,
      TXT_COMENTARIO,
      COD_USR_REVISION
    )
    VALUES
    (
      'A1004806',
      'COD_SOCIEDAD',
      'ES',
      'CODIGO SOCIEDAD FINANCIERA',
      'SMD'
    );
EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
  UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
  SET TXT_COMENTARIO = 'CODIGO SOCIEDAD FINANCIERA',
    COD_USR_REVISION = 'SMD'
  WHERE NOM_TABLA    = 'A1004806'
  AND NOM_COLUMNA    = 'COD_SOCIEDAD'
  AND COD_IDIOMA     = 'ES';
END;
BEGIN
  INSERT
  INTO TRON2000.TRN_COMENTARIO_COLUMNAS
    (
      NOM_TABLA,
      NOM_COLUMNA,
      COD_IDIOMA,
      TXT_COMENTARIO,
      COD_USR_REVISION
    )
    VALUES
    (
      'A1004806',
      'COD_SOCIEDAD',
      'EN',
      'FINNANCIALS SOCIETY',
      'SMD'
    );
EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
  UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
  SET TXT_COMENTARIO = 'FINNANCIALS SOCIETY',
    COD_USR_REVISION = 'SMD'
  WHERE NOM_TABLA    = 'A1004806'
  AND NOM_COLUMNA    = 'COD_SOCIEDAD'
  AND COD_IDIOMA     = 'EN';
END;
BEGIN
  INSERT
  INTO TRON2000.TRN_COMENTARIO_COLUMNAS
    (
      NOM_TABLA,
      NOM_COLUMNA,
      COD_IDIOMA,
      TXT_COMENTARIO,
      COD_USR_REVISION
    )
    VALUES
    (
      'GENERICA',
      'COD_USR',
      'ES',
      'USUARIO QUE ACTUALIZO LA FILA',
      'SMD'
    );
EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
  UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
  SET TXT_COMENTARIO = 'USUARIO QUE ACTUALIZO LA FILA',
    COD_USR_REVISION = 'SMD'
  WHERE NOM_TABLA    = 'GENERICA'
  AND NOM_COLUMNA    = 'COD_USR'
  AND COD_IDIOMA     = 'ES';
END;
BEGIN
  INSERT
  INTO TRON2000.TRN_COMENTARIO_COLUMNAS
    (
      NOM_TABLA,
      NOM_COLUMNA,
      COD_IDIOMA,
      TXT_COMENTARIO,
      COD_USR_REVISION
    )
    VALUES
    (
      'GENERICA',
      'COD_USR',
      'EN',
      'USER THAT UPDATED ROW',
      'SMD'
    );
EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
  UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
  SET TXT_COMENTARIO = 'USER THAT UPDATED ROW',
    COD_USR_REVISION = 'SMD'
  WHERE NOM_TABLA    = 'GENERICA'
  AND NOM_COLUMNA    = 'COD_USR'
  AND COD_IDIOMA     = 'EN';
END;
BEGIN
  INSERT
  INTO TRON2000.TRN_COMENTARIO_COLUMNAS
    (
      NOM_TABLA,
      NOM_COLUMNA,
      COD_IDIOMA,
      TXT_COMENTARIO,
      COD_USR_REVISION
    )
    VALUES
    (
      'GENERICA',
      'FEC_ACTU',
      'ES',
      'FECHA DE ACTUALIZACION DE LA FILA',
      'SMD'
    );
EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
  UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
  SET TXT_COMENTARIO = 'FECHA DE ACTUALIZACION DE LA FILA',
    COD_USR_REVISION = 'SMD'
  WHERE NOM_TABLA    = 'GENERICA'
  AND NOM_COLUMNA    = 'FEC_ACTU'
  AND COD_IDIOMA     = 'ES';
END;
BEGIN
  INSERT
  INTO TRON2000.TRN_COMENTARIO_COLUMNAS
    (
      NOM_TABLA,
      NOM_COLUMNA,
      COD_IDIOMA,
      TXT_COMENTARIO,
      COD_USR_REVISION
    )
    VALUES
    (
      'GENERICA',
      'FEC_ACTU',
      'EN',
      'ROW UPDATE DATE',
      'SMD'
    );
EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
  UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
  SET TXT_COMENTARIO = 'ROW UPDATE DATE',
    COD_USR_REVISION = 'SMD'
  WHERE NOM_TABLA    = 'GENERICA'
  AND NOM_COLUMNA    = 'FEC_ACTU'
  AND COD_IDIOMA     = 'EN';
END;
BEGIN
  INSERT
  INTO TRON2000.TRN_COMENTARIO_COLUMNAS
    (
      NOM_TABLA,
      NOM_COLUMNA,
      COD_IDIOMA,
      TXT_COMENTARIO,
      COD_USR_REVISION
    )
    VALUES
    (
      'GENERICA',
      'FEC_VALIDEZ',
      'ES',
      'FECHA DE VALIDEZ',
      'SMD'
    );
EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
  UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
  SET TXT_COMENTARIO = 'FECHA DE VALIDEZ',
    COD_USR_REVISION = 'SMD'
  WHERE NOM_TABLA    = 'GENERICA'
  AND NOM_COLUMNA    = 'FEC_VALIDEZ'
  AND COD_IDIOMA     = 'ES';
END;
BEGIN
  INSERT
  INTO TRON2000.TRN_COMENTARIO_COLUMNAS
    (
      NOM_TABLA,
      NOM_COLUMNA,
      COD_IDIOMA,
      TXT_COMENTARIO,
      COD_USR_REVISION
    )
    VALUES
    (
      'GENERICA',
      'FEC_VALIDEZ',
      'EN',
      'VALIDITY DATE',
      'SMD'
    );
EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
  UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
  SET TXT_COMENTARIO = 'VALIDITY DATE',
    COD_USR_REVISION = 'SMD'
  WHERE NOM_TABLA    = 'GENERICA'
  AND NOM_COLUMNA    = 'FEC_VALIDEZ'
  AND COD_IDIOMA     = 'EN';
END;
BEGIN
  INSERT
  INTO TRON2000.TRN_COMENTARIO_COLUMNAS
    (
      NOM_TABLA,
      NOM_COLUMNA,
      COD_IDIOMA,
      TXT_COMENTARIO,
      COD_USR_REVISION
    )
    VALUES
    (
      'GENERICA',
      'NOM_PRG_OBTIENE_DATOS',
      'ES',
      'NOMBRE DEL PROGRAMA QUE OBTIENE LOS DATOS',
      'SMD'
    );
EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
  UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
  SET TXT_COMENTARIO = 'NOMBRE DEL PROGRAMA QUE OBTIENE LOS DATOS',
    COD_USR_REVISION = 'SMD'
  WHERE NOM_TABLA    = 'GENERICA'
  AND NOM_COLUMNA    = 'NOM_PRG_OBTIENE_DATOS'
  AND COD_IDIOMA     = 'ES';
END;
BEGIN
  INSERT
  INTO TRON2000.TRN_COMENTARIO_COLUMNAS
    (
      NOM_TABLA,
      NOM_COLUMNA,
      COD_IDIOMA,
      TXT_COMENTARIO,
      COD_USR_REVISION
    )
    VALUES
    (
      'GENERICA',
      'NOM_PRG_OBTIENE_DATOS',
      'EN',
      'NAME OF THE PROGRAM THAT OBTAINS THE DATA',
      'SMD'
    );
EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
  UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
  SET TXT_COMENTARIO = 'NAME OF THE PROGRAM THAT OBTAINS THE DATA',
    COD_USR_REVISION = 'SMD'
  WHERE NOM_TABLA    = 'GENERICA'
  AND NOM_COLUMNA    = 'NOM_PRG_OBTIENE_DATOS'
  AND COD_IDIOMA     = 'EN';
END;
END;
/