-----------------------------------------------------------
---MAPFRE DGTP - MODELO DE DATOS                        ---
-----------------------------------------------------------
---Nº PETICIÓN:       RF00644148-SD02206370
---SOLICITADA POR:    BLAZQUF
---OBJETOS AFECTADOS: A1004808, GENERICA
---PROYECTO:          TRN
---ENTORNO:           WDMD04
---REALIZADO POR:     LUAZNAR
---TIPOLOGÍA:         REENTRANTE
-----------------------------------------------------------

BEGIN
 BEGIN
  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
    (NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
  VALUES
    ('GENERICA',
     'VAL_MCA_INT',
     'ES',
     'VALOR UTILIZADO POR NUCLEO PARA VALIDACIONES INTERNAS',
     'SMD');
EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
       SET TXT_COMENTARIO   = 'VALOR UTILIZADO POR NUCLEO PARA VALIDACIONES INTERNAS',
           COD_USR_REVISION = 'SMD'
     WHERE NOM_TABLA = 'GENERICA'
       AND NOM_COLUMNA = 'VAL_MCA_INT'
       AND COD_IDIOMA = 'ES';
END;
BEGIN
  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
    (NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
  VALUES
    ('GENERICA', 'VAL_MCA_INT', 'EN', 'VALUE USED BY CORE FOR INTERNAL VALIDATIONS', 'SMD');
EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
       SET TXT_COMENTARIO   = 'VALUE USED BY CORE FOR INTERNAL VALIDATIONS',
           COD_USR_REVISION = 'SMD'
     WHERE NOM_TABLA = 'GENERICA'
       AND NOM_COLUMNA = 'VAL_MCA_INT'
       AND COD_IDIOMA = 'EN';
END;

END;
/
