-----------------------------------------------------------
---MAPFRE DGTP - MODELO DE DATOS                        ---
-----------------------------------------------------------
---Nº PETICIÓN:       RF00576103-SD01987156
---SOLICITADA POR:    BLAZQUF
---OBJETOS AFECTADOS: A1004810, GENERICA
---PROYECTO:          TRN_TRON
---ENTORNO:           WDMD04
---REALIZADO POR:     VERAEST
---TIPOLOGIA:         REENTRANTE
-----------------------------------------------------------

BEGIN

  BEGIN
    INSERT INTO TRON2000.TRN_COMENTARIO_TABLAS
      (NOM_TABLA,
       COD_IDIOMA,
       TXT_COMENTARIO,
       COD_USR_REVISION,
       VAL_ESTADO_COLUMNAS)
    VALUES
      ('A1004810',
       'ES',
       'NIIF 17 TRANSACCIONES FINANCIERAS FPSL',
       'SMD',
       'TOTAL');
  EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
      UPDATE TRON2000.TRN_COMENTARIO_TABLAS
         SET TXT_COMENTARIO      = 'NIIF 17 TRANSACCIONES FINANCIERAS FPSL',
             COD_USR_REVISION    = 'SMD',
             VAL_ESTADO_COLUMNAS = 'TOTAL'
       WHERE NOM_TABLA = 'A1004810'
         AND COD_IDIOMA = 'ES';
  END;
  BEGIN
    INSERT INTO TRON2000.TRN_COMENTARIO_TABLAS
      (NOM_TABLA,
       COD_IDIOMA,
       TXT_COMENTARIO,
       COD_USR_REVISION,
       VAL_ESTADO_COLUMNAS)
    VALUES
      ('A1004810',
       'EN',
       'NIIF 17 BUSINESS TRASLATION FPSL',
       'SMD',
       'TOTAL');
  EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
      UPDATE TRON2000.TRN_COMENTARIO_TABLAS
         SET TXT_COMENTARIO      = 'NIIF 17 BUSINESS TRASLATION FPSL',
             COD_USR_REVISION    = 'SMD',
             VAL_ESTADO_COLUMNAS = 'TOTAL'
       WHERE NOM_TABLA = 'A1004810'
         AND COD_IDIOMA = 'EN';
  END;
  
BEGIN
  INSERT
  INTO TRON2000.TRN_COMENTARIO_COLUMNAS
    (
      NOM_TABLA,
      NOM_COLUMNA,
      COD_IDIOMA,
      TXT_COMENTARIO,
      COD_USR_REVISION
    )
    VALUES
    (
      'GENERICA',
      'IDN_BT',
      'ES',
      'CODIGO UNICO DE IDENTIFICACION DE LA BT',
      'SMD'
    );
EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
  UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
  SET TXT_COMENTARIO = 'CODIGO UNICO DE IDENTIFICACION DE LA BT',
    COD_USR_REVISION = 'SMD'
  WHERE NOM_TABLA    = 'GENERICA'
  AND NOM_COLUMNA    = 'IDN_BT'
  AND COD_IDIOMA     = 'ES';
END;
BEGIN
  INSERT
  INTO TRON2000.TRN_COMENTARIO_COLUMNAS
    (
      NOM_TABLA,
      NOM_COLUMNA,
      COD_IDIOMA,
      TXT_COMENTARIO,
      COD_USR_REVISION
    )
    VALUES
    (
      'GENERICA',
      'IDN_BT',
      'EN',
      'UNIQUE IDENTIFICATION CODE OF THE BT',
      'SMD'
    );
EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
  UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
  SET TXT_COMENTARIO = 'UNIQUE IDENTIFICATION CODE OF THE BT',
    COD_USR_REVISION = 'SMD'
  WHERE NOM_TABLA    = 'GENERICA'
  AND NOM_COLUMNA    = 'IDN_BT'
  AND COD_IDIOMA     = 'EN';
END;
BEGIN
  INSERT
  INTO TRON2000.TRN_COMENTARIO_COLUMNAS
    (
      NOM_TABLA,
      NOM_COLUMNA,
      COD_IDIOMA,
      TXT_COMENTARIO,
      COD_USR_REVISION
    )
    VALUES
    (
      'GENERICA',
      'IDN_BT_REF',
      'ES',
      'NUMERO EXTERNO DE REFERENCIA DE LA BT',
      'SMD'
    );
EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
  UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
  SET TXT_COMENTARIO = 'NUMERO EXTERNO DE REFERENCIA DE LA BT',
    COD_USR_REVISION = 'SMD'
  WHERE NOM_TABLA    = 'GENERICA'
  AND NOM_COLUMNA    = 'IDN_BT_REF'
  AND COD_IDIOMA     = 'ES';
END;
BEGIN
  INSERT
  INTO TRON2000.TRN_COMENTARIO_COLUMNAS
    (
      NOM_TABLA,
      NOM_COLUMNA,
      COD_IDIOMA,
      TXT_COMENTARIO,
      COD_USR_REVISION
    )
    VALUES
    (
      'GENERICA',
      'IDN_BT_REF',
      'EN',
      'EXTERNAL REFERENCE NUMBER OF THE BT',
      'SMD'
    );
EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
  UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
  SET TXT_COMENTARIO = 'EXTERNAL REFERENCE NUMBER OF THE BT',
    COD_USR_REVISION = 'SMD'
  WHERE NOM_TABLA    = 'GENERICA'
  AND NOM_COLUMNA    = 'IDN_BT_REF'
  AND COD_IDIOMA     = 'EN';
END;
BEGIN
  INSERT
  INTO TRON2000.TRN_COMENTARIO_COLUMNAS
    (
      NOM_TABLA,
      NOM_COLUMNA,
      COD_IDIOMA,
      TXT_COMENTARIO,
      COD_USR_REVISION
    )
    VALUES
    (
      'GENERICA',
      'IDN_BT_REV',
      'ES',
      'ID DE LA BT DE REVERSION',
      'SMD'
    );
EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
  UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
  SET TXT_COMENTARIO = 'ID DE LA BT DE REVERSION',
    COD_USR_REVISION = 'SMD'
  WHERE NOM_TABLA    = 'GENERICA'
  AND NOM_COLUMNA    = 'IDN_BT_REV'
  AND COD_IDIOMA     = 'ES';
END;
BEGIN
  INSERT
  INTO TRON2000.TRN_COMENTARIO_COLUMNAS
    (
      NOM_TABLA,
      NOM_COLUMNA,
      COD_IDIOMA,
      TXT_COMENTARIO,
      COD_USR_REVISION
    )
    VALUES
    (
      'GENERICA',
      'IDN_BT_REV',
      'EN',
      'BT REVERSAL ID',
      'SMD'
    );
EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
  UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
  SET TXT_COMENTARIO = 'BT REVERSAL ID',
    COD_USR_REVISION = 'SMD'
  WHERE NOM_TABLA    = 'GENERICA'
  AND NOM_COLUMNA    = 'IDN_BT_REV'
  AND COD_IDIOMA     = 'EN';
END;
BEGIN
  INSERT
  INTO TRON2000.TRN_COMENTARIO_COLUMNAS
    (
      NOM_TABLA,
      NOM_COLUMNA,
      COD_IDIOMA,
      TXT_COMENTARIO,
      COD_USR_REVISION
    )
    VALUES
    (
      'GENERICA',
      'IDN_COBERTURA',
      'ES',
      'CODIGO DE IDENTIFICACION DE LA COBERTURA',
      'SMD'
    );
EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
  UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
  SET TXT_COMENTARIO = 'CODIGO DE IDENTIFICACION DE LA COBERTURA',
    COD_USR_REVISION = 'SMD'
  WHERE NOM_TABLA    = 'GENERICA'
  AND NOM_COLUMNA    = 'IDN_COBERTURA'
  AND COD_IDIOMA     = 'ES';
END;
BEGIN
  INSERT
  INTO TRON2000.TRN_COMENTARIO_COLUMNAS
    (
      NOM_TABLA,
      NOM_COLUMNA,
      COD_IDIOMA,
      TXT_COMENTARIO,
      COD_USR_REVISION
    )
    VALUES
    (
      'GENERICA',
      'IDN_COBERTURA',
      'EN',
      'COVERAGE IDENTIFICATION CODE',
      'SMD'
    );
EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
  UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
  SET TXT_COMENTARIO = 'COVERAGE IDENTIFICATION CODE',
    COD_USR_REVISION = 'SMD'
  WHERE NOM_TABLA    = 'GENERICA'
  AND NOM_COLUMNA    = 'IDN_COBERTURA'
  AND COD_IDIOMA     = 'EN';
END;
BEGIN
  INSERT
  INTO TRON2000.TRN_COMENTARIO_COLUMNAS
    (
      NOM_TABLA,
      NOM_COLUMNA,
      COD_IDIOMA,
      TXT_COMENTARIO,
      COD_USR_REVISION
    )
    VALUES
    (
      'GENERICA',
      'IDN_FICHERO',
      'ES',
      'CODIGO IDENTIFICATIVO DEL FICHERO ENVIADO.',
      'SMD'
    );
EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
  UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
  SET TXT_COMENTARIO = 'CODIGO IDENTIFICATIVO DEL FICHERO ENVIADO.',
    COD_USR_REVISION = 'SMD'
  WHERE NOM_TABLA    = 'GENERICA'
  AND NOM_COLUMNA    = 'IDN_FICHERO'
  AND COD_IDIOMA     = 'ES';
END;
BEGIN
  INSERT
  INTO TRON2000.TRN_COMENTARIO_COLUMNAS
    (
      NOM_TABLA,
      NOM_COLUMNA,
      COD_IDIOMA,
      TXT_COMENTARIO,
      COD_USR_REVISION
    )
    VALUES
    (
      'GENERICA',
      'IDN_FICHERO',
      'EN',
      'IDENTIFICATION CODE OF THE FILE SENT.',
      'SMD'
    );
EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
  UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
  SET TXT_COMENTARIO = 'IDENTIFICATION CODE OF THE FILE SENT.',
    COD_USR_REVISION = 'SMD'
  WHERE NOM_TABLA    = 'GENERICA'
  AND NOM_COLUMNA    = 'IDN_FICHERO'
  AND COD_IDIOMA     = 'EN';
END;
BEGIN
  INSERT
  INTO TRON2000.TRN_COMENTARIO_COLUMNAS
    (
      NOM_TABLA,
      NOM_COLUMNA,
      COD_IDIOMA,
      TXT_COMENTARIO,
      COD_USR_REVISION
    )
    VALUES
    (
      'GENERICA',
      'IMP_IMPUESTO',
      'ES',
      'IMPORTE TOTAL DEL IMPUESTO',
      'SMD'
    );
EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
  UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
  SET TXT_COMENTARIO = 'IMPORTE TOTAL DEL IMPUESTO',
    COD_USR_REVISION = 'SMD'
  WHERE NOM_TABLA    = 'GENERICA'
  AND NOM_COLUMNA    = 'IMP_IMPUESTO'
  AND COD_IDIOMA     = 'ES';
END;
BEGIN
  INSERT
  INTO TRON2000.TRN_COMENTARIO_COLUMNAS
    (
      NOM_TABLA,
      NOM_COLUMNA,
      COD_IDIOMA,
      TXT_COMENTARIO,
      COD_USR_REVISION
    )
    VALUES
    (
      'GENERICA',
      'IMP_IMPUESTO',
      'EN',
      'TOTAL TAX AMOUNT',
      'SMD'
    );
EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
  UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
  SET TXT_COMENTARIO = 'TOTAL TAX AMOUNT',
    COD_USR_REVISION = 'SMD'
  WHERE NOM_TABLA    = 'GENERICA'
  AND NOM_COLUMNA    = 'IMP_IMPUESTO'
  AND COD_IDIOMA     = 'EN';
END;
BEGIN
  INSERT
  INTO TRON2000.TRN_COMENTARIO_COLUMNAS
    (
      NOM_TABLA,
      NOM_COLUMNA,
      COD_IDIOMA,
      TXT_COMENTARIO,
      COD_USR_REVISION
    )
    VALUES
    (
      'GENERICA',
      'IMP_TRANSACCION',
      'ES',
      'IMPORTE DE LA TRANSACCION',
      'SMD'
    );
EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
  UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
  SET TXT_COMENTARIO = 'IMPORTE DE LA TRANSACCION',
    COD_USR_REVISION = 'SMD'
  WHERE NOM_TABLA    = 'GENERICA'
  AND NOM_COLUMNA    = 'IMP_TRANSACCION'
  AND COD_IDIOMA     = 'ES';
END;
BEGIN
  INSERT
  INTO TRON2000.TRN_COMENTARIO_COLUMNAS
    (
      NOM_TABLA,
      NOM_COLUMNA,
      COD_IDIOMA,
      TXT_COMENTARIO,
      COD_USR_REVISION
    )
    VALUES
    (
      'GENERICA',
      'IMP_TRANSACCION',
      'EN',
      'TRANSACTION AMMOUNT',
      'SMD'
    );
EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
  UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
  SET TXT_COMENTARIO = 'TRANSACTION AMMOUNT',
    COD_USR_REVISION = 'SMD'
  WHERE NOM_TABLA    = 'GENERICA'
  AND NOM_COLUMNA    = 'IMP_TRANSACCION'
  AND COD_IDIOMA     = 'EN';
END;
BEGIN
  INSERT
  INTO TRON2000.TRN_COMENTARIO_COLUMNAS
    (
      NOM_TABLA,
      NOM_COLUMNA,
      COD_IDIOMA,
      TXT_COMENTARIO,
      COD_USR_REVISION
    )
    VALUES
    (
      'GENERICA',
      'TXT_MCA_BT_REV',
      'ES',
      'ESTE CAMPO INDICA QUE LA BT ES LA CANCELACION DE OTRA.',
      'SMD'
    );
EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
  UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
  SET TXT_COMENTARIO = 'ESTE CAMPO INDICA QUE LA BT ES LA CANCELACION DE OTRA.',
    COD_USR_REVISION = 'SMD'
  WHERE NOM_TABLA    = 'GENERICA'
  AND NOM_COLUMNA    = 'TXT_MCA_BT_REV'
  AND COD_IDIOMA     = 'ES';
END;
BEGIN
  INSERT
  INTO TRON2000.TRN_COMENTARIO_COLUMNAS
    (
      NOM_TABLA,
      NOM_COLUMNA,
      COD_IDIOMA,
      TXT_COMENTARIO,
      COD_USR_REVISION
    )
    VALUES
    (
      'GENERICA',
      'TXT_MCA_BT_REV',
      'EN',
      'THIS FIELD INDICATES THAT THE BT IS THE CANCELLATION OF ANOTHER.',
      'SMD'
    );
EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
  UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
  SET TXT_COMENTARIO = 'THIS FIELD INDICATES THAT THE BT IS THE CANCELLATION OF ANOTHER.',
    COD_USR_REVISION = 'SMD'
  WHERE NOM_TABLA    = 'GENERICA'
  AND NOM_COLUMNA    = 'TXT_MCA_BT_REV'
  AND COD_IDIOMA     = 'EN';
END;
BEGIN
  INSERT
  INTO TRON2000.TRN_COMENTARIO_COLUMNAS
    (
      NOM_TABLA,
      NOM_COLUMNA,
      COD_IDIOMA,
      TXT_COMENTARIO,
      COD_USR_REVISION
    )
    VALUES
    (
      'GENERICA',
      'TIP_BT',
      'ES',
      'CODIGO QUE INDICA EL TIPO DE BT',
      'SMD'
    );
EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
  UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
  SET TXT_COMENTARIO = 'CODIGO QUE INDICA EL TIPO DE BT',
    COD_USR_REVISION = 'SMD'
  WHERE NOM_TABLA    = 'GENERICA'
  AND NOM_COLUMNA    = 'TIP_BT'
  AND COD_IDIOMA     = 'ES';
END;
BEGIN
  INSERT
  INTO TRON2000.TRN_COMENTARIO_COLUMNAS
    (
      NOM_TABLA,
      NOM_COLUMNA,
      COD_IDIOMA,
      TXT_COMENTARIO,
      COD_USR_REVISION
    )
    VALUES
    (
      'GENERICA',
      'TIP_BT',
      'EN',
      'CODE INDICATING BT TYPE',
      'SMD'
    );
EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
  UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
  SET TXT_COMENTARIO = 'CODE INDICATING BT TYPE',
    COD_USR_REVISION = 'SMD'
  WHERE NOM_TABLA    = 'GENERICA'
  AND NOM_COLUMNA    = 'TIP_BT'
  AND COD_IDIOMA     = 'EN';
END;
BEGIN
  INSERT
  INTO TRON2000.TRN_COMENTARIO_COLUMNAS
    (
      NOM_TABLA,
      NOM_COLUMNA,
      COD_IDIOMA,
      TXT_COMENTARIO,
      COD_USR_REVISION
    )
    VALUES
    (
      'GENERICA',
      'TXT_NUM_EXTERNO',
      'ES',
      'CODIGO UNICO DE IDENTIFICACION DEL CONTRATO',
      'SMD'
    );
EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
  UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
  SET TXT_COMENTARIO = 'CODIGO UNICO DE IDENTIFICACION DEL CONTRATO',
    COD_USR_REVISION = 'SMD'
  WHERE NOM_TABLA    = 'GENERICA'
  AND NOM_COLUMNA    = 'TXT_NUM_EXTERNO'
  AND COD_IDIOMA     = 'ES';
END;
BEGIN
  INSERT
  INTO TRON2000.TRN_COMENTARIO_COLUMNAS
    (
      NOM_TABLA,
      NOM_COLUMNA,
      COD_IDIOMA,
      TXT_COMENTARIO,
      COD_USR_REVISION
    )
    VALUES
    (
      'GENERICA',
      'TXT_NUM_EXTERNO',
      'EN',
      'UNIQUE CONTRACT IDENTIFICATION CODE',
      'SMD'
    );
EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
  UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
  SET TXT_COMENTARIO = 'UNIQUE CONTRACT IDENTIFICATION CODE',
    COD_USR_REVISION = 'SMD'
  WHERE NOM_TABLA    = 'GENERICA'
  AND NOM_COLUMNA    = 'TXT_NUM_EXTERNO'
  AND COD_IDIOMA     = 'EN';
END;

END;
/