-----------------------------------------------------------
---MAPFRE DGTP - MODELO DE DATOS                        ---
-----------------------------------------------------------
---Nº PETICIÓN:       RF00644148-SD02206370
---SOLICITADA POR:    BLAZQUF
---OBJETOS AFECTADOS: A1004813, GENERICA
---PROYECTO:          TRN
---ENTORNO:           WDMD04
---REALIZADO POR:     LUAZNAR
---TIPOLOGÍA:         REENTRANTE
-----------------------------------------------------------

BEGIN
  BEGIN
    INSERT INTO TRON2000.TRN_COMENTARIO_TABLAS
      (NOM_TABLA,
       COD_IDIOMA,
       TXT_COMENTARIO,
       COD_USR_REVISION,
       VAL_ESTADO_COLUMNAS)
    VALUES
      ('A1004813',
       'ES',
       'NIIF 17 COMISIONES',
       'SMD',
       'TOTAL');
  EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
      UPDATE TRON2000.TRN_COMENTARIO_TABLAS
         SET TXT_COMENTARIO      = 'NIIF 17 COMISIONES',
             COD_USR_REVISION    = 'SMD',
             VAL_ESTADO_COLUMNAS = 'TOTAL'
       WHERE NOM_TABLA = 'A1004813'
         AND COD_IDIOMA = 'ES';
  END;
  BEGIN
    INSERT INTO TRON2000.TRN_COMENTARIO_TABLAS
      (NOM_TABLA,
       COD_IDIOMA,
       TXT_COMENTARIO,
       COD_USR_REVISION,
       VAL_ESTADO_COLUMNAS)
    VALUES
      ('A1004813',
       'EN',
       'NIIF 17 COMISSION',
       'SMD',
       'TOTAL');
  EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
      UPDATE TRON2000.TRN_COMENTARIO_TABLAS
         SET TXT_COMENTARIO      = 'NIIF 17 COMISSION',
             COD_USR_REVISION    = 'SMD',
             VAL_ESTADO_COLUMNAS = 'TOTAL'
       WHERE NOM_TABLA = 'A1004813'
         AND COD_IDIOMA = 'EN';
  END;
  BEGIN
  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
    (NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
  VALUES
    ('GENERICA', 'COD_CIA', 'ES', 'COMPAÑIA', 'SMD');
EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
       SET TXT_COMENTARIO = 'COMPAÑIA', COD_USR_REVISION = 'SMD'
     WHERE NOM_TABLA = 'GENERICA'
       AND NOM_COLUMNA = 'COD_CIA'
       AND COD_IDIOMA = 'ES';
END;
BEGIN
  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
    (NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
  VALUES
    ('GENERICA', 'COD_CIA', 'EN', 'COMPANY', 'SMD');
EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
       SET TXT_COMENTARIO = 'COMPANY', COD_USR_REVISION = 'SMD'
     WHERE NOM_TABLA = 'GENERICA'
       AND NOM_COLUMNA = 'COD_CIA'
       AND COD_IDIOMA = 'EN';
END;
BEGIN
  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
    (NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
  VALUES
    ('GENERICA', 'COD_COB', 'ES', 'COBERTURA', 'SMD');
EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
       SET TXT_COMENTARIO = 'COBERTURA', COD_USR_REVISION = 'SMD'
     WHERE NOM_TABLA = 'GENERICA'
       AND NOM_COLUMNA = 'COD_COB'
       AND COD_IDIOMA = 'ES';
END;
BEGIN
  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
    (NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
  VALUES
    ('GENERICA', 'COD_COB', 'EN', 'COVERAGE', 'SMD');
EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
       SET TXT_COMENTARIO = 'COVERAGE', COD_USR_REVISION = 'SMD'
     WHERE NOM_TABLA = 'GENERICA'
       AND NOM_COLUMNA = 'COD_COB'
       AND COD_IDIOMA = 'EN';
END;
BEGIN
  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
    (NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
  VALUES
    ('GENERICA',
     'COD_KMODALIDAD',
     'ES',
     'CODIGO O INDICADOR DEL PRODUCTO',
     'SMD');
EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
       SET TXT_COMENTARIO   = 'CODIGO O INDICADOR DEL PRODUCTO',
           COD_USR_REVISION = 'SMD'
     WHERE NOM_TABLA = 'GENERICA'
       AND NOM_COLUMNA = 'COD_KMODALIDAD'
       AND COD_IDIOMA = 'ES';
END;
BEGIN
  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
    (NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
  VALUES
    ('GENERICA',
     'COD_KMODALIDAD',
     'EN',
     'PRODUCT CODE OR INDICATOR',
     'SMD');
EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
       SET TXT_COMENTARIO   = 'PRODUCT CODE OR INDICATOR',
           COD_USR_REVISION = 'SMD'
     WHERE NOM_TABLA = 'GENERICA'
       AND NOM_COLUMNA = 'COD_KMODALIDAD'
       AND COD_IDIOMA = 'EN';
END;
BEGIN
  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
    (NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
  VALUES
    ('GENERICA',
     'IMP_COMIS_NETA_SPTO',
     'ES',
     'COMISION DEL SUPLEMENTO',
     'SMD');
EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
       SET TXT_COMENTARIO   = 'COMISION DEL SUPLEMENTO',
           COD_USR_REVISION = 'SMD'
     WHERE NOM_TABLA = 'GENERICA'
       AND NOM_COLUMNA = 'IMP_COMIS_NETA_SPTO'
       AND COD_IDIOMA = 'ES';
END;
BEGIN
  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
    (NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
  VALUES
    ('GENERICA',
     'IMP_COMIS_NETA_SPTO',
     'EN',
     'ENDORSEMENT COMMISSION',
     'SMD');
EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
       SET TXT_COMENTARIO   = 'ENDORSEMENT COMMISSION',
           COD_USR_REVISION = 'SMD'
     WHERE NOM_TABLA = 'GENERICA'
       AND NOM_COLUMNA = 'IMP_COMIS_NETA_SPTO'
       AND COD_IDIOMA = 'EN';
END;
BEGIN
  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
    (NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
  VALUES
    ('GENERICA', 'NUM_APLI', 'ES', 'NUMERO DE APLICACION', 'SMD');
EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
       SET TXT_COMENTARIO   = 'NUMERO DE APLICACION',
           COD_USR_REVISION = 'SMD'
     WHERE NOM_TABLA = 'GENERICA'
       AND NOM_COLUMNA = 'NUM_APLI'
       AND COD_IDIOMA = 'ES';
END;
BEGIN
  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
    (NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
  VALUES
    ('GENERICA', 'NUM_APLI', 'EN', 'APPLICATION NUMBER', 'SMD');
EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
       SET TXT_COMENTARIO = 'APPLICATION NUMBER', COD_USR_REVISION = 'SMD'
     WHERE NOM_TABLA = 'GENERICA'
       AND NOM_COLUMNA = 'NUM_APLI'
       AND COD_IDIOMA = 'EN';
END;
BEGIN
  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
    (NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
  VALUES
    ('GENERICA', 'NUM_POLIZA', 'ES', 'POLIZA', 'SMD');
EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
       SET TXT_COMENTARIO = 'POLIZA', COD_USR_REVISION = 'SMD'
     WHERE NOM_TABLA = 'GENERICA'
       AND NOM_COLUMNA = 'NUM_POLIZA'
       AND COD_IDIOMA = 'ES';
END;
BEGIN
  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
    (NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
  VALUES
    ('GENERICA', 'NUM_POLIZA', 'EN', 'POLICY', 'SMD');
EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
       SET TXT_COMENTARIO = 'POLICY', COD_USR_REVISION = 'SMD'
     WHERE NOM_TABLA = 'GENERICA'
       AND NOM_COLUMNA = 'NUM_POLIZA'
       AND COD_IDIOMA = 'EN';
END;
BEGIN
  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
    (NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
  VALUES
    ('GENERICA', 'NUM_SPTO', 'ES', 'NUMERO DE SUPLEMENTO', 'SMD');
EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
       SET TXT_COMENTARIO   = 'NUMERO DE SUPLEMENTO',
           COD_USR_REVISION = 'SMD'
     WHERE NOM_TABLA = 'GENERICA'
       AND NOM_COLUMNA = 'NUM_SPTO'
       AND COD_IDIOMA = 'ES';
END;
BEGIN
  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
    (NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
  VALUES
    ('GENERICA', 'NUM_SPTO', 'EN', 'ENDORSEMENT NUMBER', 'SMD');
EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
       SET TXT_COMENTARIO = 'ENDORSEMENT NUMBER', COD_USR_REVISION = 'SMD'
     WHERE NOM_TABLA = 'GENERICA'
       AND NOM_COLUMNA = 'NUM_SPTO'
       AND COD_IDIOMA = 'EN';
END;
BEGIN
  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
    (NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
  VALUES
    ('GENERICA',
     'NUM_SPTO_APLI',
     'ES',
     'SUPLEMENTO DE LA APLICACION',
     'SMD');
EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
       SET TXT_COMENTARIO   = 'SUPLEMENTO DE LA APLICACION',
           COD_USR_REVISION = 'SMD'
     WHERE NOM_TABLA = 'GENERICA'
       AND NOM_COLUMNA = 'NUM_SPTO_APLI'
       AND COD_IDIOMA = 'ES';
END;
BEGIN
  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
    (NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
  VALUES
    ('GENERICA', 'NUM_SPTO_APLI', 'EN', 'ENDORSEMENT APPLICATION', 'SMD');
EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
       SET TXT_COMENTARIO   = 'ENDORSEMENT APPLICATION',
           COD_USR_REVISION = 'SMD'
     WHERE NOM_TABLA = 'GENERICA'
       AND NOM_COLUMNA = 'NUM_SPTO_APLI'
       AND COD_IDIOMA = 'EN';
END;

END;
/
