-----------------------------------------------------------
---MAPFRE DGTP - Modelo de datos                        ---
-----------------------------------------------------------
---Nº PETICIÓN:       RF00661266 - SD02270738
---SOLICITADA POR:    PERAUL
---OBJETOS AFECTADOS: GENERICA
---PROYECTO:          TRN
---ENTORNO:           WDMD04
---REALIZADO POR:     VERAEST
---TIPOLOGÍA:         Reentrante
-----------------------------------------------------------

BEGIN
  BEGIN
    INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
      (NOM_TABLA,
       NOM_COLUMNA,
       COD_IDIOMA,
       TXT_COMENTARIO,
       COD_USR_REVISION)
    VALUES
      ('GENERICA',
       'COD_FRACC_PAGO',
       'ES',
       'PLAN DE PAGO',
       'SMD');
  EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
      UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
         SET TXT_COMENTARIO   = 'PLAN DE PAGO',
             COD_USR_REVISION = 'SMD'
       WHERE NOM_TABLA = 'GENERICA'
         AND NOM_COLUMNA = 'COD_FRACC_PAGO'
         AND COD_IDIOMA = 'ES';
  END;
  BEGIN
    INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
      (NOM_TABLA,
       NOM_COLUMNA,
       COD_IDIOMA,
       TXT_COMENTARIO,
       COD_USR_REVISION)
    VALUES
      ('GENERICA',
       'COD_FRACC_PAGO',
       'EN',
       'PAYMENT PLAN',
       'SMD');
  EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
      UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
         SET TXT_COMENTARIO   = 'PAYMENT PLAN',
             COD_USR_REVISION = 'SMD'
       WHERE NOM_TABLA = 'GENERICA'
         AND NOM_COLUMNA = 'COD_FRACC_PAGO'
         AND COD_IDIOMA = 'EN';
  END;
  BEGIN
    INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
      (NOM_TABLA,
       NOM_COLUMNA,
       COD_IDIOMA,
       TXT_COMENTARIO,
       COD_USR_REVISION)
    VALUES
      ('GENERICA',
       'COD_MON_ISO',
       'ES',
       'CODIGO DE MONEDA ESTANDARD',
       'SMD');
  EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
      UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
         SET TXT_COMENTARIO   = 'CODIGO DE MONEDA ESTANDARD',
             COD_USR_REVISION = 'SMD'
       WHERE NOM_TABLA = 'GENERICA'
         AND NOM_COLUMNA = 'COD_MON_ISO'
         AND COD_IDIOMA = 'ES';
  END;
  BEGIN
    INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
      (NOM_TABLA,
       NOM_COLUMNA,
       COD_IDIOMA,
       TXT_COMENTARIO,
       COD_USR_REVISION)
    VALUES
      ('GENERICA',
       'COD_MON_ISO',
       'EN',
       'STANDARD CURRENCY CODE',
       'SMD');
  EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
      UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
         SET TXT_COMENTARIO   = 'STANDARD CURRENCY CODE',
             COD_USR_REVISION = 'SMD'
       WHERE NOM_TABLA = 'GENERICA'
         AND NOM_COLUMNA = 'COD_MON_ISO'
         AND COD_IDIOMA = 'EN';
  END;
  BEGIN
    INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
      (NOM_TABLA,
       NOM_COLUMNA,
       COD_IDIOMA,
       TXT_COMENTARIO,
       COD_USR_REVISION)
    VALUES
      ('GENERICA',
       'COD_PRE_PAG',
       'ES',
       'INDICADOR DE SI EL PAGO DE LA PRIMA ES PREPAGABLE O POS PAGABLE',
       'SMD');
  EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
      UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
         SET TXT_COMENTARIO   = 'INDICADOR DE SI EL PAGO DE LA PRIMA ES PREPAGABLE O POS PAGABLE',
             COD_USR_REVISION = 'SMD'
       WHERE NOM_TABLA = 'GENERICA'
         AND NOM_COLUMNA = 'COD_PRE_PAG'
         AND COD_IDIOMA = 'ES';
  END;
  BEGIN
    INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
      (NOM_TABLA,
       NOM_COLUMNA,
       COD_IDIOMA,
       TXT_COMENTARIO,
       COD_USR_REVISION)
    VALUES
      ('GENERICA',
       'COD_PRE_PAG',
       'EN',
       'INDICATOR OF WHETHER THE PREMIUM PAYMENT IS PREPAYABLE OR POSTPAYABLE',
       'SMD');
  EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
      UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
         SET TXT_COMENTARIO   = 'INDICATOR OF WHETHER THE PREMIUM PAYMENT IS PREPAYABLE OR POSTPAYABLE',
             COD_USR_REVISION = 'SMD'
       WHERE NOM_TABLA = 'GENERICA'
         AND NOM_COLUMNA = 'COD_PRE_PAG'
         AND COD_IDIOMA = 'EN';
  END;
  BEGIN
    INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
      (NOM_TABLA,
       NOM_COLUMNA,
       COD_IDIOMA,
       TXT_COMENTARIO,
       COD_USR_REVISION)
    VALUES
      ('GENERICA',
       'COD_RATIO_COMBINADO',
       'ES',
       'RATIO COMBINADO USADO PARA EL CALCULO Y DETERMINACION DEL LOSS COMPONENT',
       'SMD');
  EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
      UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
         SET TXT_COMENTARIO   = 'RATIO COMBINADO USADO PARA EL CALCULO Y DETERMINACION DEL LOSS COMPONENT',
             COD_USR_REVISION = 'SMD'
       WHERE NOM_TABLA = 'GENERICA'
         AND NOM_COLUMNA = 'COD_RATIO_COMBINADO'
         AND COD_IDIOMA = 'ES';
  END;
  BEGIN
    INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
      (NOM_TABLA,
       NOM_COLUMNA,
       COD_IDIOMA,
       TXT_COMENTARIO,
       COD_USR_REVISION)
    VALUES
      ('GENERICA',
       'COD_RATIO_COMBINADO',
       'EN',
       'COMBINED RATIO USED FOR THE CALCULATION AND DETERMINATION OF THE LOSS COMPONENT',
       'SMD');
  EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
      UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
         SET TXT_COMENTARIO   = 'COMBINED RATIO USED FOR THE CALCULATION AND DETERMINATION OF THE LOSS COMPONENT',
             COD_USR_REVISION = 'SMD'
       WHERE NOM_TABLA = 'GENERICA'
         AND NOM_COLUMNA = 'COD_RATIO_COMBINADO'
         AND COD_IDIOMA = 'EN';
  END;
  BEGIN
    INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
      (NOM_TABLA,
       NOM_COLUMNA,
       COD_IDIOMA,
       TXT_COMENTARIO,
       COD_USR_REVISION)
    VALUES
      ('GENERICA',
       'FEC_EMI_TIP_REG',
       'ES',
       'FECHA DE EMISION DEL TIPO DE REGISTRO',
       'SMD');
  EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
      UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
         SET TXT_COMENTARIO   = 'FECHA DE EMISION DEL TIPO DE REGISTRO',
             COD_USR_REVISION = 'SMD'
       WHERE NOM_TABLA = 'GENERICA'
         AND NOM_COLUMNA = 'FEC_EMI_TIP_REG'
         AND COD_IDIOMA = 'ES';
  END;
  BEGIN
    INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
      (NOM_TABLA,
       NOM_COLUMNA,
       COD_IDIOMA,
       TXT_COMENTARIO,
       COD_USR_REVISION)
    VALUES
      ('GENERICA',
       'FEC_EMI_TIP_REG',
       'EN',
       'DATE OF ISSUE OF THE TYPE OF REGISTRY',
       'SMD');
  EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
      UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
         SET TXT_COMENTARIO   = 'DATE OF ISSUE OF THE TYPE OF REGISTRY',
             COD_USR_REVISION = 'SMD'
       WHERE NOM_TABLA = 'GENERICA'
         AND NOM_COLUMNA = 'FEC_EMI_TIP_REG'
         AND COD_IDIOMA = 'EN';
  END;
  BEGIN
    INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
      (NOM_TABLA,
       NOM_COLUMNA,
       COD_IDIOMA,
       TXT_COMENTARIO,
       COD_USR_REVISION)
    VALUES
      ('GENERICA',
       'IDN_FICHERO',
       'ES',
       'CODIGO IDENTIFICATIVO DEL FICHERO ENVIADO',
       'SMD');
  EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
      UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
         SET TXT_COMENTARIO   = 'CODIGO IDENTIFICATIVO DEL FICHERO ENVIADO',
             COD_USR_REVISION = 'SMD'
       WHERE NOM_TABLA = 'GENERICA'
         AND NOM_COLUMNA = 'IDN_FICHERO'
         AND COD_IDIOMA = 'ES';
  END;
  BEGIN
    INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
      (NOM_TABLA,
       NOM_COLUMNA,
       COD_IDIOMA,
       TXT_COMENTARIO,
       COD_USR_REVISION)
    VALUES
      ('GENERICA',
       'IDN_FICHERO',
       'EN',
       'IDENTIFICATION CODE OF THE FILE SENT',
       'SMD');
  EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
      UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
         SET TXT_COMENTARIO   = 'IDENTIFICATION CODE OF THE FILE SENT',
             COD_USR_REVISION = 'SMD'
       WHERE NOM_TABLA = 'GENERICA'
         AND NOM_COLUMNA = 'IDN_FICHERO'
         AND COD_IDIOMA = 'EN';
  END;
  BEGIN
    INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
      (NOM_TABLA,
       NOM_COLUMNA,
       COD_IDIOMA,
       TXT_COMENTARIO,
       COD_USR_REVISION)
    VALUES
      ('GENERICA',
       'IDN_PROB_IMPAGO',
       'ES',
       'CODIGO IDENTIFICATIVO DE PROBABILIDAD DE PAGO',
       'SMD');
  EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
      UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
         SET TXT_COMENTARIO   = 'CODIGO IDENTIFICATIVO DE PROBABILIDAD DE PAGO',
             COD_USR_REVISION = 'SMD'
       WHERE NOM_TABLA = 'GENERICA'
         AND NOM_COLUMNA = 'IDN_PROB_IMPAGO'
         AND COD_IDIOMA = 'ES';
  END;
  BEGIN
    INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
      (NOM_TABLA,
       NOM_COLUMNA,
       COD_IDIOMA,
       TXT_COMENTARIO,
       COD_USR_REVISION)
    VALUES
      ('GENERICA',
       'IDN_PROB_IMPAGO',
       'EN',
       'PROBABILITY OF PAYMENT IDENTIFICATION CODE',
       'SMD');
  EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
      UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
         SET TXT_COMENTARIO   = 'PROBABILITY OF PAYMENT IDENTIFICATION CODE',
             COD_USR_REVISION = 'SMD'
       WHERE NOM_TABLA = 'GENERICA'
         AND NOM_COLUMNA = 'IDN_PROB_IMPAGO'
         AND COD_IDIOMA = 'EN';
  END;
END;
/
