BEGIN
BEGIN
--
Insert into TRON2000.G1010030
   (COD_CAMPO, COD_IDIOMA, NOM_LISTA, FEC_ACTU, COD_INSTALACION)
 Values
   ('NIIF-17', 'EN', 'IFRS 17', SYSDATE, 'TRN');
--   
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G1010030
 SET  NOM_LISTA = 'IFRS 17', FEC_ACTU = SYSDATE, COD_INSTALACION = 'TRN'
 WHERE  COD_CAMPO = 'NIIF-17' 
   AND  COD_IDIOMA = 'EN'
;
END;
--
BEGIN
--   
Insert into TRON2000.G1010030
   (COD_CAMPO, COD_IDIOMA, NOM_LISTA, FEC_ACTU, COD_INSTALACION)
 Values
   ('NIIF-17', 'ES', 'NIIF-17', SYSDATE, 'TRN');
--  
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G1010030
 SET  NOM_LISTA = 'NIIF-17', FEC_ACTU = SYSDATE, COD_INSTALACION = 'TRN'
 WHERE  COD_CAMPO = 'NIIF-17' 
   AND  COD_IDIOMA = 'ES'
; 
END;
--
--
--
BEGIN
--
Insert into TRON2000.G1010031
   (COD_CAMPO, NUM_ORDEN, COD_VALOR, COD_IDIOMA, NOM_VALOR, 
    COD_RAMO, COD_INSTALACION)
 Values
   ('NIIF-17', 1, 'P', 'EN', 'PROPHET', 
    999, 'TRN');
--   
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G1010031
 SET  NUM_ORDEN = 1, NOM_VALOR = 'PROPHET', COD_INSTALACION = 'TRN'
 WHERE  COD_CAMPO = 'NIIF-17' 
   AND  COD_VALOR = 'P'
   AND  COD_RAMO = 999
   AND  COD_IDIOMA = 'EN'
;
END;
--
BEGIN
--
Insert into TRON2000.G1010031
   (COD_CAMPO, NUM_ORDEN, COD_VALOR, COD_IDIOMA, NOM_VALOR, 
    COD_RAMO, COD_INSTALACION)
 Values
   ('NIIF-17', 2, 'F', 'EN', 'FPSL', 
    999, 'TRN');
--   
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G1010031
 SET  NUM_ORDEN = 2, NOM_VALOR = 'FPSL', COD_INSTALACION = 'TRN'
 WHERE  COD_CAMPO = 'NIIF-17' 
   AND  COD_VALOR = 'F'
   AND  COD_RAMO = 999
   AND  COD_IDIOMA = 'EN'
;
END;
--
BEGIN
--	
	Insert into TRON2000.G1010031
   (COD_CAMPO, NUM_ORDEN, COD_VALOR, COD_IDIOMA, NOM_VALOR, 
    COD_RAMO, COD_INSTALACION)
 Values
   ('NIIF-17', 1, 'P', 'ES', 'PROPHET', 
    999, 'TRN');
--   
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G1010031
 SET  NUM_ORDEN = 1, NOM_VALOR = 'PROPHET', COD_INSTALACION = 'TRN'
 WHERE  COD_CAMPO = 'NIIF-17' 
   AND  COD_VALOR = 'P'
   AND  COD_RAMO = 999
   AND  COD_IDIOMA = 'ES'
;
END;
--
BEGIN
--	
Insert into TRON2000.G1010031
   (COD_CAMPO, NUM_ORDEN, COD_VALOR, COD_IDIOMA, NOM_VALOR, 
    COD_RAMO, COD_INSTALACION)
 Values
   ('NIIF-17', 2, 'F', 'ES', 'FPSL', 
    999, 'TRN');
--   
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G1010031
 SET  NUM_ORDEN = 2, NOM_VALOR = 'FPSL', COD_INSTALACION = 'TRN'
 WHERE  COD_CAMPO = 'NIIF-17' 
   AND  COD_VALOR = 'F'
   AND  COD_RAMO = 999
   AND  COD_IDIOMA = 'ES'
;
END;
--
END;
/
