-----------------------------------------------------------
---MAPFRE DGTP - MODELO DE DATOS                        ---
-----------------------------------------------------------
---Nº PETICIÓN:       RF00628216-SD02154737
---SOLICITADA POR:    BLAZQUEZ LOPEZ, FERNANDO
---OBJETOS AFECTADOS: A1004811
---PROYECTO:          TRN
---ENTORNO:           WDMD04
---REALIZADO POR:     RSANTO5
---TIPOLOGIA:         REENTRANTE
-----------------------------------------------------------

BEGIN
BEGIN
  INSERT
  INTO
    TRON2000.TRN_COMENTARIO_COLUMNAS
    (
      NOM_TABLA,
      NOM_COLUMNA,
      COD_IDIOMA,
      TXT_COMENTARIO,
      COD_USR_REVISION
    )
    VALUES
    (
      'GENERICA',
      'IMP_COMISION',
      'ES',
      'IMPORTE DE LA COMISION ANUAL VIGENTE A NIVEL COBERTURA',
      'SMD'
    );
EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
  UPDATE
    TRON2000.TRN_COMENTARIO_COLUMNAS
  SET
    TXT_COMENTARIO   = 'IMPORTE DE LA COMISION ANUAL VIGENTE A NIVEL COBERTURA',
    COD_USR_REVISION = 'SMD'
  WHERE
    NOM_TABLA     = 'GENERICA'
  AND NOM_COLUMNA = 'IMP_COMISION'
  AND COD_IDIOMA  = 'ES';
END;
BEGIN
  INSERT
  INTO
    TRON2000.TRN_COMENTARIO_COLUMNAS
    (
      NOM_TABLA,
      NOM_COLUMNA,
      COD_IDIOMA,
      TXT_COMENTARIO,
      COD_USR_REVISION
    )
    VALUES
    (
      'GENERICA',
      'IMP_COMISION',
      'EN',
      'AMOUNT OF THE ANNUAL COMMISION AT COVERAGE LEVEL',
      'SMD'
    );
EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
  UPDATE
    TRON2000.TRN_COMENTARIO_COLUMNAS
  SET
    TXT_COMENTARIO   = 'AMOUNT OF THE ANNUAL COMMISION AT COVERAGE LEVEL',
    COD_USR_REVISION = 'SMD'
  WHERE
    NOM_TABLA     = 'GENERICA'
  AND NOM_COLUMNA = 'IMP_COMISION'
  AND COD_IDIOMA  = 'EN';
END;
BEGIN
  INSERT
  INTO
    TRON2000.TRN_COMENTARIO_COLUMNAS
    (
      NOM_TABLA,
      NOM_COLUMNA,
      COD_IDIOMA,
      TXT_COMENTARIO,
      COD_USR_REVISION
    )
    VALUES
    (
      'A1004811',
      'IMP_PRIMA',
      'ES',
      'IMPORTE DE LA PRIMA ANUAL O UNICA VIGENTE A NIVEL COBERTURA',
      'SMD'
    );
EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
  UPDATE
    TRON2000.TRN_COMENTARIO_COLUMNAS
  SET
    TXT_COMENTARIO =
    'IMPORTE DE LA PRIMA ANUAL O UNICA VIGENTE A NIVEL COBERTURA',
    COD_USR_REVISION = 'SMD'
  WHERE
    NOM_TABLA     = 'A1004811'
  AND NOM_COLUMNA = 'IMP_PRIMA'
  AND COD_IDIOMA  = 'ES';
END;
BEGIN
  INSERT
  INTO
    TRON2000.TRN_COMENTARIO_COLUMNAS
    (
      NOM_TABLA,
      NOM_COLUMNA,
      COD_IDIOMA,
      TXT_COMENTARIO,
      COD_USR_REVISION
    )
    VALUES
    (
      'A1004811',
      'IMP_PRIMA',
      'EN',
      'AMOUNT OF THE ANNUAL OR SINGLE PREMIUM IN FORCE AT COVERAGE LEVEL',
      'SMD'
    );
EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
  UPDATE
    TRON2000.TRN_COMENTARIO_COLUMNAS
  SET
    TXT_COMENTARIO =
    'AMOUNT OF THE ANNUAL OR SINGLE PREMIUM IN FORCE AT COVERAGE LEVEL',
    COD_USR_REVISION = 'SMD'
  WHERE
    NOM_TABLA     = 'A1004811'
  AND NOM_COLUMNA = 'IMP_PRIMA'
  AND COD_IDIOMA  = 'EN';
END;


END;
/