-- MENú DE BOTONES EN LA CABECERA DE LA PANTALLA G1010130
BEGIN
   BEGIN
   --
   Insert into TRON2000.G1010130
      (COD_PGM, NUM_MENU_OPCION, COD_IDIOMA, NOM_MENU_OPCION, FEC_ACTU, 
      COD_INSTALACION)
   Values
      ('AP100360', 1, 'EN', 'OPTIONS', SYSDATE, 'TRN');
   --   
   EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN 
   UPDATE TRON2000.G1010130
   SET  NOM_MENU_OPCION = 'OPTIONS'
   WHERE  COD_PGM = 'AP100360' AND NUM_MENU_OPCION = 1 AND COD_IDIOMA = 'EN';
   END;
   --
   BEGIN
   --
   Insert into TRON2000.G1010130
      (COD_PGM, NUM_MENU_OPCION, COD_IDIOMA, NOM_MENU_OPCION, FEC_ACTU, 
      COD_INSTALACION)
   Values
      ('AP100360', 1, 'ES', 'OPCIONES', SYSDATE, 'TRN');
   --   
   EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN 
   UPDATE TRON2000.G1010130
   SET  NOM_MENU_OPCION = 'OPCIONES'
   WHERE  COD_PGM = 'AP100360' AND NUM_MENU_OPCION = 1 AND COD_IDIOMA = 'ES';
   END;
   --
END;
/