BEGIN
   BEGIN
   --
   Insert into TRON2000.G1010030
      (COD_CAMPO, COD_IDIOMA, NOM_LISTA, FEC_ACTU, COD_INSTALACION)
   Values
      ('TIP_SITU_PROC4', 'EN', 'PROCESS FPSL CONDITIONS', SYSDATE, 'TRN');
   --   
   EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN 
   UPDATE TRON2000.G1010030
   SET  NOM_LISTA = 'PROCESS FPSL CONDITIONS', FEC_ACTU = SYSDATE, COD_INSTALACION = 'TRN'
   WHERE  COD_CAMPO = 'TIP_SITU_PROC4' 
      AND  COD_IDIOMA = 'EN'
   ;
   END;
   --
   BEGIN
   --   
   Insert into TRON2000.G1010030
      (COD_CAMPO, COD_IDIOMA, NOM_LISTA, FEC_ACTU, COD_INSTALACION)
   Values
      ('TIP_SITU_PROC4', 'ES', 'SITUACIONES PROCESO FPSL', SYSDATE, 'TRN');
   --  
   EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN 
   UPDATE TRON2000.G1010030
   SET  NOM_LISTA = 'SITUACIONES PROCESO FPSL', FEC_ACTU = SYSDATE, COD_INSTALACION = 'TRN'
   WHERE  COD_CAMPO = 'TIP_SITU_PROC4' 
      AND  COD_IDIOMA = 'ES'
   ; 
   END;
   --
   --
   --
   BEGIN
   --
   Insert into TRON2000.G1010031
      (COD_CAMPO, NUM_ORDEN, COD_VALOR, COD_IDIOMA, NOM_VALOR, 
      COD_RAMO, COD_INSTALACION)
   Values
      ('TIP_SITU_PROC4', 1, '1', 'EN', 'WITHOUT PROCESSING', 
      999, 'TRN');
   --   
   EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN 
   UPDATE TRON2000.G1010031
   SET  NUM_ORDEN = 1, NOM_VALOR = 'WITHOUT PROCESSING', COD_INSTALACION = 'TRN'
   WHERE  COD_CAMPO = 'TIP_SITU_PROC4' 
      AND  COD_VALOR = '1'
      AND  COD_RAMO = 999
      AND  COD_IDIOMA = 'EN'
   ;
   END;
   --
   BEGIN
   --
   Insert into TRON2000.G1010031
      (COD_CAMPO, NUM_ORDEN, COD_VALOR, COD_IDIOMA, NOM_VALOR, 
      COD_RAMO, COD_INSTALACION)
   Values
      ('TIP_SITU_PROC4', 2, '2', 'EN', 'GENERATING DATA', 
      999, 'TRN');
   --   
   EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN 
   UPDATE TRON2000.G1010031
   SET  NUM_ORDEN = 2, NOM_VALOR = 'GENERATING DATA', COD_INSTALACION = 'TRN'
   WHERE  COD_CAMPO = 'TIP_SITU_PROC4' 
      AND  COD_VALOR = '2'
      AND  COD_RAMO = 999
      AND  COD_IDIOMA = 'EN'
   ;
   END;
   --
   BEGIN
   --
   Insert into TRON2000.G1010031
      (COD_CAMPO, NUM_ORDEN, COD_VALOR, COD_IDIOMA, NOM_VALOR, 
      COD_RAMO, COD_INSTALACION)
   Values
      ('TIP_SITU_PROC4', 3, '3', 'EN', 'DATA GENERATED', 
      999, 'TRN');
   --   
   EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN 
   UPDATE TRON2000.G1010031
   SET  NUM_ORDEN = 3, NOM_VALOR = 'DATA GENERATED', COD_INSTALACION = 'TRN'
   WHERE  COD_CAMPO = 'TIP_SITU_PROC4' 
      AND  COD_VALOR = '3'
      AND  COD_RAMO = 999
      AND  COD_IDIOMA = 'EN'
   ;
   END;
   --
   BEGIN
   --
   Insert into TRON2000.G1010031
      (COD_CAMPO, NUM_ORDEN, COD_VALOR, COD_IDIOMA, NOM_VALOR, 
      COD_RAMO, COD_INSTALACION)
   Values
      ('TIP_SITU_PROC4', 4, '4', 'EN', 'DATA GENERATION ERROR', 
      999, 'TRN');
   --   
   EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN 
   UPDATE TRON2000.G1010031
   SET  NUM_ORDEN = 4, NOM_VALOR = 'DATA GENERATION ERROR', COD_INSTALACION = 'TRN'
   WHERE  COD_CAMPO = 'TIP_SITU_PROC4' 
      AND  COD_VALOR = '4'
      AND  COD_RAMO = 999
      AND  COD_IDIOMA = 'EN'
   ;
   END;
   --
   BEGIN
   --
   Insert into TRON2000.G1010031
      (COD_CAMPO, NUM_ORDEN, COD_VALOR, COD_IDIOMA, NOM_VALOR, 
      COD_RAMO, COD_INSTALACION)
   Values
      ('TIP_SITU_PROC4', 5, '5', 'EN', 'EXTRACTING FILES', 
      999, 'TRN');
   --   
   EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN 
   UPDATE TRON2000.G1010031
   SET  NUM_ORDEN = 5, NOM_VALOR = 'EXTRACTING FILES', COD_INSTALACION = 'TRN'
   WHERE  COD_CAMPO = 'TIP_SITU_PROC4' 
      AND  COD_VALOR = '5'
      AND  COD_RAMO = 999
      AND  COD_IDIOMA = 'EN'
   ;
   END;
   --
   BEGIN
   --	
   Insert into TRON2000.G1010031
      (COD_CAMPO, NUM_ORDEN, COD_VALOR, COD_IDIOMA, NOM_VALOR, 
      COD_RAMO, COD_INSTALACION)
   Values
      ('TIP_SITU_PROC4', 6, '6', 'EN', 'FILE GENERATED', 
      999, 'TRN');
   --   
   EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN 
   UPDATE TRON2000.G1010031
   SET  NUM_ORDEN = 6, NOM_VALOR = 'FILE GENERATED', COD_INSTALACION = 'TRN'
   WHERE  COD_CAMPO = 'TIP_SITU_PROC4' 
      AND  COD_VALOR = '6'
      AND  COD_RAMO = 999
      AND  COD_IDIOMA = 'EN'
   ;
   END;
   --
   BEGIN
   --	
   Insert into TRON2000.G1010031
      (COD_CAMPO, NUM_ORDEN, COD_VALOR, COD_IDIOMA, NOM_VALOR, 
      COD_RAMO, COD_INSTALACION)
   Values
      ('TIP_SITU_PROC4', 7, '7', 'EN', 'FILE GENERATION ERROR', 
      999, 'TRN');
   --   
   EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN 
   UPDATE TRON2000.G1010031
   SET  NUM_ORDEN = 7, NOM_VALOR = 'FILE GENERATION ERROR', COD_INSTALACION = 'TRN'
   WHERE  COD_CAMPO = 'TIP_SITU_PROC4' 
      AND  COD_VALOR = '7'
      AND  COD_RAMO = 999
      AND  COD_IDIOMA = 'EN'
   ;
   END;
   --
   BEGIN
   --	
   Insert into TRON2000.G1010031
      (COD_CAMPO, NUM_ORDEN, COD_VALOR, COD_IDIOMA, NOM_VALOR, 
      COD_RAMO, COD_INSTALACION)
   Values
      ('TIP_SITU_PROC4', 8, '8', 'EN', 'HISTORIFYING', 
      999, 'TRN');
   --  
   EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN 
   UPDATE TRON2000.G1010031
   SET  NUM_ORDEN = 8, NOM_VALOR = 'HISTORIFYING', COD_INSTALACION = 'TRN'
   WHERE  COD_CAMPO = 'TIP_SITU_PROC4' 
      AND  COD_VALOR = '8'
      AND  COD_RAMO = 999
      AND  COD_IDIOMA = 'EN'
   ; 
   END;
   --
   BEGIN
   --	
   Insert into TRON2000.G1010031
      (COD_CAMPO, NUM_ORDEN, COD_VALOR, COD_IDIOMA, NOM_VALOR, 
      COD_RAMO, COD_INSTALACION)
   Values
      ('TIP_SITU_PROC4', 9, '9', 'EN', 'COMPLETE HISTORIFICATION', 
      999, 'TRN');
   --   
   EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN 
   UPDATE TRON2000.G1010031
   SET  NUM_ORDEN = 9, NOM_VALOR = 'COMPLETE HISTORIFICATION', COD_INSTALACION = 'TRN'
   WHERE  COD_CAMPO = 'TIP_SITU_PROC4' 
      AND  COD_VALOR = '9'
      AND  COD_RAMO = 999
      AND  COD_IDIOMA = 'EN'
   ; 
   END;
   --
   BEGIN
   --	
   Insert into TRON2000.G1010031
      (COD_CAMPO, NUM_ORDEN, COD_VALOR, COD_IDIOMA, NOM_VALOR, 
      COD_RAMO, COD_INSTALACION)
   Values
      ('TIP_SITU_PROC4', 10, '10', 'EN', 'ERROR HISTORIFICATION', 
      999, 'TRN');
   --   
   EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN 
   UPDATE TRON2000.G1010031
   SET  NUM_ORDEN = 10, NOM_VALOR = 'ERROR HISTORIFICATION', COD_INSTALACION = 'TRN'
   WHERE  COD_CAMPO = 'TIP_SITU_PROC4' 
      AND  COD_VALOR = '10'
      AND  COD_RAMO = 999
      AND  COD_IDIOMA = 'EN'
   ;
   END;
   --
   BEGIN
   --	
      Insert into TRON2000.G1010031
      (COD_CAMPO, NUM_ORDEN, COD_VALOR, COD_IDIOMA, NOM_VALOR, 
      COD_RAMO, COD_INSTALACION)
   Values
      ('TIP_SITU_PROC4', 1, '1', 'ES', 'SIN PROCESAR', 
      999, 'TRN');
   --   
   EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN 
   UPDATE TRON2000.G1010031
   SET  NUM_ORDEN = 1, NOM_VALOR = 'SIN PROCESAR', COD_INSTALACION = 'TRN'
   WHERE  COD_CAMPO = 'TIP_SITU_PROC4' 
      AND  COD_VALOR = '1'
      AND  COD_RAMO = 999
      AND  COD_IDIOMA = 'ES'
   ;
   END;
   --
   BEGIN
   --	
   Insert into TRON2000.G1010031
      (COD_CAMPO, NUM_ORDEN, COD_VALOR, COD_IDIOMA, NOM_VALOR, 
      COD_RAMO, COD_INSTALACION)
   Values
      ('TIP_SITU_PROC4', 2, '2', 'ES', 'GENERANDO DATOS', 
      999, 'TRN');
   --   
   EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN 
   UPDATE TRON2000.G1010031
   SET  NUM_ORDEN = 2, NOM_VALOR = 'GENERANDO DATOS', COD_INSTALACION = 'TRN'
   WHERE  COD_CAMPO = 'TIP_SITU_PROC4' 
      AND  COD_VALOR = '2'
      AND  COD_RAMO = 999
      AND  COD_IDIOMA = 'ES'
   ;
   END;
   --
   BEGIN
   --	
   Insert into TRON2000.G1010031
      (COD_CAMPO, NUM_ORDEN, COD_VALOR, COD_IDIOMA, NOM_VALOR, 
      COD_RAMO, COD_INSTALACION)
   Values
      ('TIP_SITU_PROC4', 3, '3', 'ES', 'DATOS GENERADOS', 
      999, 'TRN');
   --   
   EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN 
   UPDATE TRON2000.G1010031
   SET  NUM_ORDEN = 3, NOM_VALOR = 'DATOS GENERADOS', COD_INSTALACION = 'TRN'
   WHERE  COD_CAMPO = 'TIP_SITU_PROC4' 
      AND  COD_VALOR = '3'
      AND  COD_RAMO = 999
      AND  COD_IDIOMA = 'ES'
   ;
   END;
   --
   BEGIN
   --	
   Insert into TRON2000.G1010031
      (COD_CAMPO, NUM_ORDEN, COD_VALOR, COD_IDIOMA, NOM_VALOR, 
      COD_RAMO, COD_INSTALACION)
   Values
      ('TIP_SITU_PROC4', 4, '4', 'ES', 'ERROR GENERACION DE DATOS', 
      999, 'TRN');
   --   
   EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN 
   UPDATE TRON2000.G1010031
   SET  NUM_ORDEN = 4, NOM_VALOR = 'ERROR GENERACION DE DATOS', COD_INSTALACION = 'TRN'
   WHERE  COD_CAMPO = 'TIP_SITU_PROC4' 
      AND  COD_VALOR = '4'
      AND  COD_RAMO = 999
      AND  COD_IDIOMA = 'ES'
   ;
   END;
   --
   BEGIN
   --	
   Insert into TRON2000.G1010031
      (COD_CAMPO, NUM_ORDEN, COD_VALOR, COD_IDIOMA, NOM_VALOR, 
      COD_RAMO, COD_INSTALACION)
   Values
      ('TIP_SITU_PROC4', 5, '5', 'ES', 'EXTRAYENDO FICHEROS', 
      999, 'TRN');
   --   
   EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN 
   UPDATE TRON2000.G1010031
   SET  NUM_ORDEN = 5, NOM_VALOR = 'EXTRAYENDO FICHEROS', COD_INSTALACION = 'TRN'
   WHERE  COD_CAMPO = 'TIP_SITU_PROC4' 
      AND  COD_VALOR = '5'
      AND  COD_RAMO = 999
      AND  COD_IDIOMA = 'ES'
   ;
   END;
   --
   BEGIN
   --	
   Insert into TRON2000.G1010031
      (COD_CAMPO, NUM_ORDEN, COD_VALOR, COD_IDIOMA, NOM_VALOR, 
      COD_RAMO, COD_INSTALACION)
   Values
      ('TIP_SITU_PROC4', 6, '6', 'ES', 'FICHERO GENERADO', 
      999, 'TRN');
   --   
   EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN 
   UPDATE TRON2000.G1010031
   SET  NUM_ORDEN = 6, NOM_VALOR = 'FICHERO GENERADO', COD_INSTALACION = 'TRN'
   WHERE  COD_CAMPO = 'TIP_SITU_PROC4' 
      AND  COD_VALOR = '6'
      AND  COD_RAMO = 999
      AND  COD_IDIOMA = 'ES'
   ;
   END;
   --
   BEGIN
   --	
   Insert into TRON2000.G1010031
      (COD_CAMPO, NUM_ORDEN, COD_VALOR, COD_IDIOMA, NOM_VALOR, 
      COD_RAMO, COD_INSTALACION)
   Values
      ('TIP_SITU_PROC4', 7, '7', 'ES', 'ERROR GENERACION FICHERO', 
      999, 'TRN');
   --   
   EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN 
   UPDATE TRON2000.G1010031
   SET  NUM_ORDEN = 7, NOM_VALOR = 'ERROR GENERACION FICHERO', COD_INSTALACION = 'TRN'
   WHERE  COD_CAMPO = 'TIP_SITU_PROC4' 
      AND  COD_VALOR = '7'
      AND  COD_RAMO = 999
      AND  COD_IDIOMA = 'ES'
   ;
   END;
   --
   BEGIN
   --	
   Insert into TRON2000.G1010031
      (COD_CAMPO, NUM_ORDEN, COD_VALOR, COD_IDIOMA, NOM_VALOR, 
      COD_RAMO, COD_INSTALACION)
   Values
      ('TIP_SITU_PROC4', 8, '8', 'ES', 'HISTORIFICANDO', 
      999, 'TRN');
   --   
   EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN 
   UPDATE TRON2000.G1010031
   SET  NUM_ORDEN = 8, NOM_VALOR = 'HISTORIFICANDO', COD_INSTALACION = 'TRN'
   WHERE  COD_CAMPO = 'TIP_SITU_PROC4' 
      AND  COD_VALOR = '8'
      AND  COD_RAMO = 999
      AND  COD_IDIOMA = 'ES'
   ;
   END;
   --
   BEGIN
   --	
   Insert into TRON2000.G1010031
      (COD_CAMPO, NUM_ORDEN, COD_VALOR, COD_IDIOMA, NOM_VALOR, 
      COD_RAMO, COD_INSTALACION)
   Values
      ('TIP_SITU_PROC4', 9, '9', 'ES', 'HISTORIFICACION COMPLETA', 
      999, 'TRN');	
   --   
   EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN 
   UPDATE TRON2000.G1010031
   SET  NUM_ORDEN = 9, NOM_VALOR = 'HISTORIFICACION COMPLETA', COD_INSTALACION = 'TRN'
   WHERE  COD_CAMPO = 'TIP_SITU_PROC4' 
      AND  COD_VALOR = '9'
      AND  COD_RAMO = 999
      AND  COD_IDIOMA = 'ES'
   ;
   END;
   --
   BEGIN
   --	
   Insert into TRON2000.G1010031
      (COD_CAMPO, NUM_ORDEN, COD_VALOR, COD_IDIOMA, NOM_VALOR, 
      COD_RAMO, COD_INSTALACION)
   Values
      ('TIP_SITU_PROC4', 10, '10', 'ES', 'ERROR HISTORIFICACION', 
      999, 'TRN');	
   --   
   EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN 
   UPDATE TRON2000.G1010031
   SET  NUM_ORDEN = 10, NOM_VALOR = 'ERROR HISTORIFICACION', COD_INSTALACION = 'TRN'
   WHERE  COD_CAMPO = 'TIP_SITU_PROC4' 
      AND  COD_VALOR = '10'
      AND  COD_RAMO = 999
      AND  COD_IDIOMA = 'ES'
   ;
   END;
END;
/
