-----------------------------------------------------------
---MAPFRE DGTP - MODELO DE DATOS                        ---
-----------------------------------------------------------
---Nº PETICIÓN:       RF00949825-SD03358017
---SOLICITADA POR:    FPEIROG
---OBJETOS AFECTADOS: A1004805, GENERICA
---PROYECTO:          NIIF17
---ENTORNO:           WDMD04
---REALIZADO POR:     RSANTO5
---TIPOLOGIA:         REENTRANTE
-----------------------------------------------------------

BEGIN
BEGIN
    DELETE FROM TRON2000.TRN_COMENTARIO_COLUMNAS
      WHERE NOM_TABLA = 'A1004805'
       AND NOM_COLUMNA = 'COD_COHORTE'
       AND COD_IDIOMA = 'ES';
END;
BEGIN
    DELETE FROM TRON2000.TRN_COMENTARIO_COLUMNAS
     WHERE NOM_TABLA = 'A1004805'
       AND NOM_COLUMNA = 'COD_COHORTE'
       AND COD_IDIOMA = 'EN';
END;
BEGIN
  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
    (NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
  VALUES
    ('A1004805',
     'COD_CARTERA',
     'ES',
     'DATO CON EL QUE SE IDENTIFICA EL CODIGO DE LA CARTERA',
     'SMD');
EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
       SET TXT_COMENTARIO   = 'DATO CON EL QUE SE IDENTIFICA EL CODIGO DE LA CARTERA',
           COD_USR_REVISION = 'SMD'
     WHERE NOM_TABLA = 'A1004805'
       AND NOM_COLUMNA = 'COD_CARTERA'
       AND COD_IDIOMA = 'ES';
END;
BEGIN
  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
    (NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
  VALUES
    ('A1004805',
     'COD_CARTERA',
     'EN',
     'DATA WITH WHICH THE PORTFOLIO CODE IS IDENTIFIED',
     'SMD');
EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
       SET TXT_COMENTARIO   = 'DATA WITH WHICH THE PORTFOLIO CODE IS IDENTIFIED',
           COD_USR_REVISION = 'SMD'
     WHERE NOM_TABLA = 'A1004805'
       AND NOM_COLUMNA = 'COD_CARTERA'
       AND COD_IDIOMA = 'EN';
END;
BEGIN
  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
    (NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
  VALUES
    ('GENERICA',
     'COD_COHORTE',
     'ES',
     'DATO CON EL QUE SE IDENTIFICA EL AÑO DE EMISION O DE RENOVACION DEL CONTRATO FPSL',
     'SMD');
EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
       SET TXT_COMENTARIO   = 'DATO CON EL QUE SE IDENTIFICA EL AÑO DE EMISION O DE RENOVACION DEL CONTRATO FPSL',
           COD_USR_REVISION = 'SMD'
     WHERE NOM_TABLA = 'GENERICA'
       AND NOM_COLUMNA = 'COD_COHORTE'
       AND COD_IDIOMA = 'ES';
END;
BEGIN
  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
    (NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
  VALUES
    ('GENERICA',
     'COD_COHORTE',
     'EN',
     'DATA WITH WHICH THE YEAR OF ISSUE OR RENEWAL OF THE FPSL CONTRACT IS IDENTIFIED',
     'SMD');
EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
       SET TXT_COMENTARIO   = 'DATA WITH WHICH THE YEAR OF ISSUE OR RENEWAL OF THE FPSL CONTRACT IS IDENTIFIED',
           COD_USR_REVISION = 'SMD'
     WHERE NOM_TABLA = 'GENERICA'
       AND NOM_COLUMNA = 'COD_COHORTE'
       AND COD_IDIOMA = 'EN';
END;
BEGIN
  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
    (NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
  VALUES
    ('GENERICA',
     'TXT_MET_VAL',
     'ES',
     'CODIGO QUE IDENTIFICA EL METODO DE VALORACION DEL CONTRATO BAJO NIIF 17',
     'SMD');
EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
       SET TXT_COMENTARIO   = 'CODIGO QUE IDENTIFICA EL METODO DE VALORACION DEL CONTRATO BAJO NIIF 17',
           COD_USR_REVISION = 'SMD'
     WHERE NOM_TABLA = 'GENERICA'
       AND NOM_COLUMNA = 'TXT_MET_VAL'
       AND COD_IDIOMA = 'ES';
END;
BEGIN
  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
    (NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
  VALUES
    ('GENERICA',
     'TXT_MET_VAL',
     'EN',
     'CODE THAT IDENTIFIES THE METHOD OF VALUATION OF THE CONTRACT UNDER IFRS 17',
     'SMD');
EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
       SET TXT_COMENTARIO   = 'CODE THAT IDENTIFIES THE METHOD OF VALUATION OF THE CONTRACT UNDER IFRS 17',
           COD_USR_REVISION = 'SMD'
     WHERE NOM_TABLA = 'GENERICA'
       AND NOM_COLUMNA = 'TXT_MET_VAL'
       AND COD_IDIOMA = 'EN';
END;
BEGIN
  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
    (NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
  VALUES
    ('GENERICA',
     'TXT_LIC_LRC',
     'ES',
     'CAMPO QUE INDICA SI LA PROVISION DE PASIVO ES POR COBERTURA RESTANTE (LRC) O POR PRESTACIONES INCURRIDAS (LIC)',
     'SMD');
EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
       SET TXT_COMENTARIO   = 'CAMPO QUE INDICA SI LA PROVISION DE PASIVO ES POR COBERTURA RESTANTE (LRC) O POR PRESTACIONES INCURRIDAS (LIC)',
           COD_USR_REVISION = 'SMD'
     WHERE NOM_TABLA = 'GENERICA'
       AND NOM_COLUMNA = 'TXT_LIC_LRC'
       AND COD_IDIOMA = 'ES';
END;
BEGIN
  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
    (NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
  VALUES
    ('GENERICA',
     'TXT_LIC_LRC',
     'EN',
     'FIELD THAT INDICATES IF THE LIABILITY PROVISION IS FOR REMAINING COVERAGE (LRC) OR FOR INCURRED BENEFITS (LIC)',
     'SMD');
EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
       SET TXT_COMENTARIO   = 'FIELD THAT INDICATES IF THE LIABILITY PROVISION IS FOR REMAINING COVERAGE (LRC) OR FOR INCURRED BENEFITS (LIC)',
           COD_USR_REVISION = 'SMD'
     WHERE NOM_TABLA = 'GENERICA'
       AND NOM_COLUMNA = 'TXT_LIC_LRC'
       AND COD_IDIOMA = 'EN';
END;
END;
/
