-----------------------------------------------------------
---MAPFRE DGTP - MODELO DE DATOS                        ---
-----------------------------------------------------------
---Nº PETICIÓN:       RF00953661 - SD03370362
---SOLICITADA POR:    FPEIROG
---OBJETOS AFECTADOS: A1004808,GENERICA
---PROYECTO:          NIIF17
---ENTORNO:           WDMD04
---REALIZADO POR:     MDALBE1
---TIPOLOGIA:         REENTRANTE
-----------------------------------------------------------

BEGIN
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('A1004808',
		 'NUM_CERTIFICADOS',
		 'ES',
		 'RIESGOS QUE COMPONEN LA POLIZA EXCEPTO EN POLIZAS COLECTIVAS (EN LAS QUE SE REPORTA UN UNICO CONTRATO FPSL CON EL NUMERO TOTAL)',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'RIESGOS QUE COMPONEN LA POLIZA EXCEPTO EN POLIZAS COLECTIVAS (EN LAS QUE SE REPORTA UN UNICO CONTRATO FPSL CON EL NUMERO TOTAL)',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'A1004808'
		   AND NOM_COLUMNA = 'NUM_CERTIFICADOS'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('A1004808',
		 'NUM_CERTIFICADOS',
		 'EN',
		 'RISKS THAT COMPOSE THE POLICY EXCEPT IN GROUP POLICIES (IN WHICH A SINGLE FPSL CONTRACT WITH THE TOTAL NUMBER IS REPORTED)',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'RISKS THAT COMPOSE THE POLICY EXCEPT IN GROUP POLICIES (IN WHICH A SINGLE FPSL CONTRACT WITH THE TOTAL NUMBER IS REPORTED)',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'A1004808'
		   AND NOM_COLUMNA = 'NUM_CERTIFICADOS'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'COD_COHORTE',
		 'ES',
		 'DATO CON EL QUE SE IDENTIFICA EL AÑO DE EMISION O DE RENOVACION DEL CONTRATO FPSL',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'DATO CON EL QUE SE IDENTIFICA EL AÑO DE EMISION O DE RENOVACION DEL CONTRATO FPSL',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'COD_COHORTE'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'COD_COHORTE',
		 'EN',
		 'DATA WITH WHICH THE YEAR OF ISSUE OR RENEWAL OF THE FPSL CONTRACT IS IDENTIFIED',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'DATA WITH WHICH THE YEAR OF ISSUE OR RENEWAL OF THE FPSL CONTRACT IS IDENTIFIED',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'COD_COHORTE'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('A1004808',
		 'COD_CARTERA',
		 'ES',
		 'DATO CON EL QUE SE IDENTIFICA EL CODIGO DE LA CARTERA',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'DATO CON EL QUE SE IDENTIFICA EL CODIGO DE LA CARTERA',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'A1004808'
		   AND NOM_COLUMNA = 'COD_CARTERA'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('A1004808',
		 'COD_CARTERA',
		 'EN',
		 'DATA WITH WHICH THE PORTFOLIO CODE IS IDENTIFIED',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'DATA WITH WHICH THE PORTFOLIO CODE IS IDENTIFIED',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'A1004808'
		   AND NOM_COLUMNA = 'COD_CARTERA'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('A1004808',
		 'TXT_ONE',
		 'ES',
		 'ONEROSIDAD POR UOA SEGUN DIRECTRICES MARCADAS POR MAPFRE GRUPO',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'ONEROSIDAD POR UOA SEGUN DIRECTRICES MARCADAS POR MAPFRE GRUPO',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'A1004808'
		   AND NOM_COLUMNA = 'TXT_ONE'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('A1004808',
		 'TXT_ONE',
		 'EN',
		 'ONEROSITY BY UOA ACCORDING TO GUIDELINES SET BY MAPFRE GRUPO',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'ONEROSITY BY UOA ACCORDING TO GUIDELINES SET BY MAPFRE GRUPO',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'A1004808'
		   AND NOM_COLUMNA = 'TXT_ONE'
		   AND COD_IDIOMA = 'EN';
	END;
END;
/