-----------------------------------------------------------
---MAPFRE DGTP - MODELO DE DATOS                        ---
-----------------------------------------------------------
---Nº PETICIÓN:       RF00953562 - SD03370044
---SOLICITADA POR:    FPEIROG
---OBJETOS AFECTADOS: A1004814, GENERICA
---PROYECTO:          NIIF17
---ENTORNO:           WDMD04
---REALIZADO POR:     MDALBE1
---TIPOLOGIA:         REENTRANTE
-----------------------------------------------------------

BEGIN
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('A1004814', 'FEC_REGISTRO', 'ES', 'FECHA DE REGISTRO', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO = 'FECHA DE REGISTRO', COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'A1004814'
		   AND NOM_COLUMNA = 'FEC_REGISTRO'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('A1004814', 'FEC_REGISTRO', 'EN', 'REGISTRATION DATE', 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO = 'REGISTRATION DATE', COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'A1004814'
		   AND NOM_COLUMNA = 'FEC_REGISTRO'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'TIP_PATRON',
		 'ES',
		 'CAMPO QUE IDENTIFICA LA TIPOLOGIA DEL PATRON',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'CAMPO QUE IDENTIFICA LA TIPOLOGIA DEL PATRON',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TIP_PATRON'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'TIP_PATRON',
		 'EN',
		 'FIELD THAT IDENTIFIES THE TYPOLOGY OF THE PATTERN',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'FIELD THAT IDENTIFIES THE TYPOLOGY OF THE PATTERN',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'TIP_PATRON'
		   AND COD_IDIOMA = 'EN';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'NUM_PROB_INCUMPLIMIENTO',
		 'ES',
		 'PROBABILIDAD DE INCUMPLIMIENTO QUE SE APLICA A CADA ENTRADA DE LA TABLA DE PERIODIFICACIONES',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'PROBABILIDAD DE INCUMPLIMIENTO QUE SE APLICA A CADA ENTRADA DE LA TABLA DE PERIODIFICACIONES',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'NUM_PROB_INCUMPLIMIENTO'
		   AND COD_IDIOMA = 'ES';
	END;
	BEGIN
	  INSERT INTO TRON2000.TRN_COMENTARIO_COLUMNAS
		(NOM_TABLA, NOM_COLUMNA, COD_IDIOMA, TXT_COMENTARIO, COD_USR_REVISION)
	  VALUES
		('GENERICA',
		 'NUM_PROB_INCUMPLIMIENTO',
		 'EN',
		 'PROBABILITY OF NON-COMPLIANCE THAT APPLIES TO EACH ENTRY OF THE PERIODIFICATION TABLE',
		 'SMD');
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
		UPDATE TRON2000.TRN_COMENTARIO_COLUMNAS
		   SET TXT_COMENTARIO   = 'PROBABILITY OF NON-COMPLIANCE THAT APPLIES TO EACH ENTRY OF THE PERIODIFICATION TABLE',
			   COD_USR_REVISION = 'SMD'
		 WHERE NOM_TABLA = 'GENERICA'
		   AND NOM_COLUMNA = 'NUM_PROB_INCUMPLIMIENTO'
		   AND COD_IDIOMA = 'EN';
	END;
END;
/