CREATE UNIQUE INDEX "TRON2000"."PK_A1004809" ON
    "TRON2000"."A1004809" (
        "COD_CIA",
        "NUM_POLIZA",
        "COD_RAMO",
        "NUM_SPTO",
        "NUM_APLI",
        "NUM_SPTO_APLI",
        "NUM_RIESGO",
        "NUM_PERIODO",
        "COD_COB",
        "MCA_REASEGURO"
    )
        PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
            STORAGE ( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT )
        TABLESPACE "DATOS";