-----------------------------------------------------------
---MAPFRE DGTP - MODELO DE DATOS                        ---
-----------------------------------------------------------
---Nº PETICIÓN:       RF00573729 - SD01978888
---SOLICITADA POR:    BLAZQUF
---OBJETOS AFECTADOS: A1004802
---PROYECTO:          TRN_TRON
---ENTORNO:           WDMD04
---REALIZADO POR:     MDALBE1
---TIPOLOGIA:         REENTRANTE
-----------------------------------------------------------

DECLARE
    -- Cursor de comprobacion
    CURSOR c_valida IS
    SELECT COUNT(1)
    FROM all_tables
    WHERE owner = 'TRON2000'
    AND table_name = 'A1004802';
    --
    l_valida INTEGER;
    --
BEGIN
    -- Realizamos la comprobacion
    OPEN c_valida;
    FETCH c_valida  INTO l_valida;
    CLOSE c_valida;
    --
    -- Si el resultado de la operacion solicitada ya existe no se hace nada
    IF l_valida <> 1 THEN
        --
        EXECUTE IMMEDIATE 'CREATE TABLE TRON2000.A1004802(
        COD_SOCIEDAD VARCHAR2(4) NOT NULL,
        COD_RAMO NUMBER(3) NOT NULL,
        COD_KMODALIDAD VARCHAR2(5) NOT NULL,
        COD_COB NUMBER(4) NOT NULL,
        TXT_KPRESTACION VARCHAR2(80),
        TXT_SPCOM VARCHAR2(80),
        TXT_PB VARCHAR2(80),
        TXT_CTIPOPROVI VARCHAR2(80),
        TXT_CTIPODUR VARCHAR2(80),
        TXT_CFORMAREVPRIM VARCHAR2(80),
        NUM_PREVPRIMA NUMBER,
        TXT_CFORMAREVCAP VARCHAR2(80),
        NUM_POREVALCAP NUMBER,
        TXT_TABLA1 VARCHAR2(80),
        NUM_TASA1 NUMBER,
        NUM_AJVALY1 NUMBER,
        NUM_AJVALPC1 NUMBER,
        COD_USR VARCHAR2(8),
        FEC_ACTU DATE
        )';
        EXECUTE IMMEDIATE 'COMMENT ON TABLE TRON2000.A1004802 IS ''NIIF 17 CONFIGURACION ATRIBUTO GARANTIA PROPHET''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004802.COD_SOCIEDAD IS ''CODIGO SOCIEDAD FINANCIERA''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004802.COD_RAMO IS ''RAMO''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004802.COD_KMODALIDAD IS ''CODIGO O INDICADOR DEL PRODUCTO''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004802.COD_COB IS ''COBERTURA''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004802.TXT_KPRESTACION IS ''TIPO DE PRESTACION ASEGURADA DE LA GARANTIA''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004802.TXT_SPCOM IS ''INDICADOR DE GARANTIA PRINCIPAL / SECUNDARIA''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004802.TXT_PB IS ''INDICADOR DE PB''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004802.TXT_CTIPOPROVI IS ''TIPO DE PROVISION LOCAL POR GARANTIA''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004802.TXT_CTIPODUR IS ''TIPO DE DURACION DE LA GARANTIA''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004802.TXT_CFORMAREVPRIM IS ''TIPO DE CRECIMIENTO DE LA PRIMA SEGUN LA GARANTIA''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004802.NUM_PREVPRIMA IS ''PORCENTAJE DE REVALORIZACION DE LA PRIMA SEGUN LA GARANTIA''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004802.TXT_CFORMAREVCAP IS ''TIPO DE REVALORIZACION DEL CAPITAL''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004802.NUM_POREVALCAP IS ''PORCENTAJE DE REVALORIZACION DEL CAPITAL''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004802.TXT_TABLA1 IS ''TABLA BASE DE VALORACION DE LA GARANTIA ''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004802.NUM_TASA1 IS ''% TASA FIJA DE LA GARANTIA''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004802.NUM_AJVALY1 IS ''AJUSTE EN AÑOS APLICADO A LAS TABLAS DE VALORACION''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004802.NUM_AJVALPC1 IS ''AJUSTE EN PORCENTAJE APLICADO A LAS TABLAS DE VALORACION''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004802.COD_USR IS ''USUARIO QUE ACTUALIZO LA FILA''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004802.FEC_ACTU IS ''FECHA DE ACTUALIZACION DE LA FILA''';
        EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX TRON2000.PK_A1004802 ON TRON2000.A1004802(COD_SOCIEDAD ASC,COD_RAMO ASC,COD_KMODALIDAD ASC,COD_COB ASC)';
        EXECUTE IMMEDIATE 'ALTER TABLE TRON2000.A1004802
            ADD CONSTRAINT PK_A1004802
            PRIMARY KEY(COD_SOCIEDAD,COD_RAMO,COD_KMODALIDAD,COD_COB)
            USING INDEX TRON2000.PK_A1004802';
        --
    END IF;
    --
END;
/