-----------------------------------------------------------
---MAPFRE DGTP - Modelo de datos                        ---
-----------------------------------------------------------
---Nº PETICIÓN:       RF00573729 - SD01978888
---SOLICITADA POR:    BLAZQUF
---OBJETOS AFECTADOS: A1004800
---PROYECTO:          TRN
---ENTORNO:           WDMD04
---REALIZADO POR:     VERAEST
---TIPOLOGÍA:         Reentrante
-----------------------------------------------------------

DECLARE
    -- Cursor de comprobacion
    CURSOR c_valida IS
      SELECT COUNT(1)
        FROM all_tables
       WHERE owner = 'TRON2000'
         AND table_name = 'A1004800';
    --
    l_valida INTEGER;
    --
BEGIN
  -- Realizamos la comprobacion
  OPEN c_valida;
  FETCH c_valida  INTO l_valida;
  CLOSE c_valida;
  --
  -- Si el resultado de la operacion solicitada ya existe no se hace nada
  IF l_valida <> 1 THEN
    --
    EXECUTE IMMEDIATE 'CREATE TABLE TRON2000.A1004800(
    IDN_INT_PROC NUMBER NOT NULL,
    COD_PROC VARCHAR2(10) NOT NULL,
    TXT_ALIAS_PROC VARCHAR2(30) NOT NULL,
    FEC_DESDE_PROC DATE NOT NULL,
    FEC_HASTA_PROC DATE NOT NULL,
    TIP_SITU_PROC VARCHAR2(3),
    MCA_ENVIADO VARCHAR2(1) NOT NULL,
    COD_USR VARCHAR2(8),
    FEC_ACTU DATE
    )';
    --
    EXECUTE IMMEDIATE 'COMMENT ON TABLE TRON2000.A1004800 IS ''PROCESOS NIIF 17''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004800.IDN_INT_PROC IS ''IDENTIFICADOR DE PROCESO''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004800.COD_PROC IS ''CODIGO DEL PROCESO''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004800.TXT_ALIAS_PROC IS ''ALIAS PROCESOS''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004800.FEC_DESDE_PROC IS ''FECHA DESDE LA QUE SE EXTRAE LA INFORMACION''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004800.FEC_HASTA_PROC IS ''FECHA HASTA LA QUE SE EXTRAE LA INFORMACION''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004800.TIP_SITU_PROC IS ''1. SIN PROCESAR  2. EN PROCESO 3. TERMINACION NORMAL 4. TERMINACION ANORMAL''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004800.MCA_ENVIADO IS ''SI SE HA ENVIADO LA INFORMACION''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004800.COD_USR IS ''USUARIO QUE ACTUALIZO LA FILA''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004800.FEC_ACTU IS ''FECHA DE ACTUALIZACION DE LA FILA''';
    EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX TRON2000.PK_A1004800 ON TRON2000.A1004800 (IDN_INT_PROC ASC)';
    EXECUTE IMMEDIATE 'ALTER TABLE TRON2000.A1004800
          ADD CONSTRAINT PK_A1004800
          PRIMARY KEY(IDN_INT_PROC)
          USING INDEX TRON2000.PK_A1004800';
      --
  END IF;
--
END;
/