-----------------------------------------------------------
---MAPFRE DGTP - Modelo de datos                        ---
-----------------------------------------------------------
---Nº PETICIÓN:       RF00576093-SD01987131
---SOLICITADA POR:    BLAZQUEZ LOPEZ, FERNANDO
---OBJETOS AFECTADOS: A1004805
---PROYECTO:          TRN
---ENTORNO:           WDMD04
---REALIZADO POR:     HLJUANJ
---TIPOLOGIA:         Reentrante
-----------------------------------------------------------

DECLARE
  -- Cursor de comprobacion
  CURSOR c_valida IS
  SELECT COUNT(1)
  FROM all_tables
 WHERE owner = 'TRON2000'
   AND table_name = 'A1004805';
  --
  l_valida INTEGER;
  --
BEGIN
  -- Realizamos la comprobacion
  OPEN c_valida;
  FETCH c_valida  INTO l_valida;
  CLOSE c_valida;
  --
  -- Si el resultado de la operacion solicitada ya existe no se hace nada
  IF l_valida <> 1 THEN
  --
EXECUTE IMMEDIATE 'CREATE TABLE TRON2000.A1004805
(
COD_SOCIEDAD                   VARCHAR2(4) NOT NULL,
COD_CARTERA                    VARCHAR2(6) NOT NULL,
FEC_VALIDEZ                    DATE NOT NULL,
COD_COHORTE                    VARCHAR2(4) NOT NULL,
TXT_ONE                        VARCHAR2(1) NOT NULL,
TXT_MET_VAL                    VARCHAR2(3) NOT NULL,
TXT_CARTERA_INM                VARCHAR2(80),
COD_USR                        VARCHAR2(8) NOT NULL,
FEC_ACTU                       DATE NOT NULL
)';
EXECUTE IMMEDIATE 'COMMENT ON TABLE TRON2000.A1004805 IS ''NIIF 17 DEFINICION CARTERAS FPSL''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004805.COD_SOCIEDAD IS ''CODIGO SOCIEDAD FINANCIERA''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004805.COD_CARTERA IS ''CODIGO UNICO DE IDENTIFICACION DEL CONTRATO''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004805.FEC_VALIDEZ IS ''FECHA DE VALIDEZ''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004805.COD_COHORTE IS ''CODIGO DE LA UNIT OF ACCOUNT A LA QUE SE ASIGNA EL CONTRATO''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004805.TXT_ONE IS ''ONEROSIDAD POR UNIT OF ACCOUNT SEGUN DIRECTRICES MARCADAS POR MAPFRE GRUPO.''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004805.TXT_MET_VAL IS ''CODIGO QUE IDENTIFICA EL METODO DE VALORACION DEL CONTRATO BAJO NIIF 17''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004805.TXT_CARTERA_INM IS ''CAMPO QUE INDIQUE SI LA POLIZA ESTA O NO EN UNA CARTERA INMUNIZADA ''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004805.COD_USR IS ''USUARIO QUE ACTUALIZO LA FILA''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004805.FEC_ACTU IS ''FECHA DE ACTUALIZACION DE LA FILA''';
EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX TRON2000.PK_A1004805 ON TRON2000.A1004805
      (COD_SOCIEDAD ASC,COD_CARTERA ASC,FEC_VALIDEZ ASC)';
EXECUTE IMMEDIATE 'ALTER TABLE TRON2000.A1004805
      ADD CONSTRAINT PK_A1004805
      PRIMARY KEY(COD_SOCIEDAD,COD_CARTERA,FEC_VALIDEZ)
      USING INDEX TRON2000.PK_A1004805';
  --
  END IF;
--
END;
/