-----------------------------------------------------------
---MAPFRE DGTP - Modelo de datos                        ---
-----------------------------------------------------------
---Nº PETICIÓN:       RF00576093-SD01987131
---SOLICITADA POR:    BLAZQUEZ LOPEZ, FERNANDO
---OBJETOS AFECTADOS: A1004807
---PROYECTO:          TRN
---ENTORNO:           WDMD04
---REALIZADO POR:     HLJUANJ
---TIPOLOGÍA:         Reentrante
-----------------------------------------------------------

DECLARE
  -- Cursor de comprobacion
  CURSOR c_valida IS
  SELECT COUNT(1)
  FROM all_tables
 WHERE owner = 'TRON2000'
   AND table_name = 'A1004807';
  --
  l_valida INTEGER;
  --
BEGIN
  -- Realizamos la comprobacion
  OPEN c_valida;
  FETCH c_valida  INTO l_valida;
  CLOSE c_valida;
  --
  -- Si el resultado de la operacion solicitada ya existe no se hace nada
  IF l_valida <> 1 THEN
  --
EXECUTE IMMEDIATE 'CREATE TABLE TRON2000.A1004807
(
COD_SIS_ORIGEN                 VARCHAR2(80) NOT NULL,
COD_SOCIEDAD                   VARCHAR2(4) NOT NULL,
COD_AGRUP_BT                   VARCHAR2(80) NOT NULL,
COD_SUB_AGRUP_BT               VARCHAR2(80) NOT NULL,
COD_OPERACION                  VARCHAR2(80) NOT NULL,
FEC_VALIDEZ                    DATE NOT NULL,
TIP_IMP                        VARCHAR2(1) NOT NULL,
NOM_PRG_OBTIENE_DATOS          VARCHAR2(80) NOT NULL,
COD_USR                        VARCHAR2(8) NOT NULL,
FEC_ACTU                       DATE NOT NULL
)';
EXECUTE IMMEDIATE 'COMMENT ON TABLE TRON2000.A1004807 IS ''NIIF 17 TRANSACCIONES FINANCIERAS FPSL''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004807.COD_SIS_ORIGEN IS ''ORIGEN DE DATOS (TW)''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004807.COD_SOCIEDAD IS ''CÓDIGO SOCIEDAD FINANCIERA''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004807.COD_AGRUP_BT IS ''CODIGO AGRUPADOR TRANSACCION FINANCIERA''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004807.COD_SUB_AGRUP_BT IS ''SUBCODIGO AGRUPADOR TRANSACCION FINANCIERA''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004807.COD_OPERACION IS ''CODIGO OPERACIÓN''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004807.FEC_VALIDEZ IS ''FECHA DE VALIDEZ''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004807.TIP_IMP IS ''TIPO DE IMPORTE CONTABLE (DEBE / HABER)''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004807.NOM_PRG_OBTIENE_DATOS IS ''NOMBRE DEL PROGRAMA QUE OBTIENE LOS DATOS''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004807.COD_USR IS ''USUARIO QUE ACTUALIZO LA FILA''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004807.FEC_ACTU IS ''FECHA DE ACTUALIZACION DE LA FILA''';
EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX TRON2000.PK_A1004807 ON TRON2000.A1004807
      (COD_SIS_ORIGEN ASC,COD_SOCIEDAD ASC,COD_AGRUP_BT ASC,COD_SUB_AGRUP_BT ASC,COD_OPERACION ASC,FEC_VALIDEZ ASC)';
EXECUTE IMMEDIATE 'ALTER TABLE TRON2000.A1004807
      ADD CONSTRAINT PK_A1004807
      PRIMARY KEY(COD_SIS_ORIGEN,COD_SOCIEDAD,COD_AGRUP_BT,COD_SUB_AGRUP_BT,COD_OPERACION,FEC_VALIDEZ)
      USING INDEX TRON2000.PK_A1004807';
  --
  END IF;
--
END;
/