-----------------------------------------------------------
---MAPFRE DGTP - Modelo de datos                        ---
-----------------------------------------------------------
---Nº PETICION:       RF00576103-SD01987156
---SOLICITADA POR:    BLAZQUEZ LOPEZ, FERNANDO
---OBJETOS AFECTADOS: A1004808
---PROYECTO:          TRN
---ENTORNO:           WDMD04
---REALIZADO POR:     MDALBE1
---TIPOLOGIA:         Reentrante
-----------------------------------------------------------

DECLARE
  -- Cursor de comprobacion
  CURSOR c_valida IS
  SELECT COUNT(1)
  FROM all_tables
 WHERE owner = 'TRON2000'
   AND table_name = 'A1004808';
  --
  l_valida INTEGER;
  --
BEGIN
  -- Realizamos la comprobacion
  OPEN c_valida;
  FETCH c_valida  INTO l_valida;
  CLOSE c_valida;
  --
  -- Si el resultado de la operacion solicitada ya existe no se hace nada
  IF l_valida <> 1 THEN
  --
EXECUTE IMMEDIATE 'CREATE TABLE TRON2000.A1004808(
COD_CIA NUMBER(2) NOT NULL,
NUM_POLIZA VARCHAR2(13) NOT NULL,
COD_RAMO NUMBER(3) NOT NULL,
NUM_SPTO NUMBER NOT NULL,
NUM_APLI NUMBER NOT NULL,
NUM_SPTO_APLI NUMBER NOT NULL,
IDN_INT_PROC NUMBER NOT NULL,
COD_SIS_ORIGEN VARCHAR2(80) NOT NULL,
TXT_NUM_EXTERNO VARCHAR2(40) NOT NULL,
FEC_REGISTRO DATE,
TXT_EST_CONTRATO VARCHAR2(3),
TXT_MET_VAL VARCHAR2(3),
FEC_EFEC_CONTRATO DATE,
FEC_FIN DATE,
COD_SOCIEDAD VARCHAR2(4),
COD_INTER_CIA VARCHAR2(10),
TXT_CTO_COSTE VARCHAR2(10),
COD_CANAL3 VARCHAR2(4),
COD_SEGMENTO VARCHAR2(4),
COD_COHORTE VARCHAR2(4),
COD_CARTERA VARCHAR2(6),
COD_ONEROSIDAD VARCHAR2(1),
TXT_UOA VARCHAR2(80)
)';
EXECUTE IMMEDIATE 'COMMENT ON TABLE TRON2000.A1004808 IS ''NIIF 17 DATOS CONTRATO FPSL''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004808.COD_CIA IS ''COMPAÑIA''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004808.NUM_POLIZA IS ''POLIZA''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004808.COD_RAMO IS ''RAMO''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004808.NUM_SPTO IS ''NUMERO DE SUPLEMENTO''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004808.NUM_APLI IS ''NUMERO DE APLICACION''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004808.NUM_SPTO_APLI IS ''SUPLEMENTO DE LA APLICACION''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004808.IDN_INT_PROC IS ''IDENTIFICADOR DE PROCESO''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004808.COD_SIS_ORIGEN IS ''ORIGEN DE DATOS (TW)''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004808.TXT_NUM_EXTERNO IS ''CODIGO UNICO DE IDENTIFICACION DEL CONTRATO''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004808.FEC_REGISTRO IS ''FECHA REGISTRO ENTRADA O SALIDA ''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004808.TXT_EST_CONTRATO IS ''DESCRIBE SI UNA POLIZA ESTA VIGENTE O FINALIZADA''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004808.TXT_MET_VAL IS ''CODIGO QUE IDENTIFICA EL METODO DE VALORACION DEL CONTRATO BAJO NIIF 17''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004808.FEC_EFEC_CONTRATO IS ''FECHA DE EFECTO DEL CONTRATO''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004808.FEC_FIN IS ''FECHA FIN''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004808.COD_SOCIEDAD IS ''CODIGO SOCIEDAD FINANCIERA''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004808.COD_INTER_CIA IS ''CODIGO DE LA SOCIEDAD DEL GRUPO MAPFRE CON LA QUE SE REALIZA EL CONTRATO (SOCIEDAD GL).''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004808.TXT_CTO_COSTE IS ''CODIGO QUE IDENTIFICA EL CENTRO EN EL QUE SE IMPUTARAN LOS COSTES ASOCIADOS AL CONTRATO.''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004808.COD_CANAL3 IS ''CODIGO CANAL3 DE DISTRIBUCION''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004808.COD_SEGMENTO IS ''CODIGO QUE IDENTIFICA EL SEGMENTO OPERATIVO EN EL QUE SE GESTIONA EL CONTRATO.''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004808.COD_COHORTE IS ''DATO CON EL QUE SE IDENTIFICA EL AÑO DE EMISION O DE RENOVACION DEL CONTRATO.''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004808.COD_CARTERA IS ''CODIGO UNICO DE IDENTIFICACION DEL CONTRATO''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004808.COD_ONEROSIDAD IS ''DATO QUE REFLEJARA SI EL CONTRATO ES ONEROSO O NO ONEROSO EN FUNCION DEL PRODUCTO/RAMO, U OTRO CRITERIO EN CASO DE QUE CON ESTOS VALORES NO FUERA SUFICIENTE.''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004808.TXT_UOA IS ''CODIGO DE LA UNIT OF ACCOUNT A LA QUE SE ASIGNA EL CONTRATO''';
EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX TRON2000.PK_A1004808 ON TRON2000.A1004808
       (COD_CIA ASC,NUM_POLIZA ASC,COD_RAMO ASC,NUM_SPTO ASC,NUM_APLI ASC,NUM_SPTO_APLI ASC)';
EXECUTE IMMEDIATE 'ALTER TABLE TRON2000.A1004808
      ADD CONSTRAINT PK_A1004808
      PRIMARY KEY(COD_CIA,NUM_POLIZA,COD_RAMO,NUM_SPTO,NUM_APLI,NUM_SPTO_APLI)
      USING INDEX TRON2000.PK_A1004808';
  --
  END IF;
--
END;
/