-----------------------------------------------------------
---MAPFRE DGTP - Modelo de datos                        ---
-----------------------------------------------------------
---Nº PETICION:       RF00576103-SD01987156
---SOLICITADA POR:    BLAZQUEZ LOPEZ, FERNANDO
---OBJETOS AFECTADOS: A1004811
---PROYECTO:          TRN
---ENTORNO:           WDMD04
---REALIZADO POR:     MDALBE1
---TIPOLOGIA:         Reentrante
-----------------------------------------------------------

DECLARE
  -- Cursor de comprobacion
  CURSOR c_valida IS
  SELECT COUNT(1)
  FROM all_tables
 WHERE owner = 'TRON2000'
   AND table_name = 'A1004811';
  --
  l_valida INTEGER;
  --
BEGIN
  -- Realizamos la comprobacion
  OPEN c_valida;
  FETCH c_valida  INTO l_valida;
  CLOSE c_valida;
  --
  -- Si el resultado de la operacion solicitada ya existe no se hace nada
  IF l_valida <> 1 THEN
  --
EXECUTE IMMEDIATE 'CREATE TABLE TRON2000.A1004811(
COD_CIA NUMBER(2) NOT NULL,
NUM_POLIZA VARCHAR2(13) NOT NULL,
COD_RAMO NUMBER(3) NOT NULL,
NUM_SPTO NUMBER NOT NULL,
NUM_APLI NUMBER NOT NULL,
NUM_SPTO_APLI NUMBER NOT NULL,
NUM_RIESGO NUMBER(7) NOT NULL,
NUM_PERIODO NUMBER NOT NULL,
COD_COB NUMBER(4) NOT NULL,
COD_COHORTE VARCHAR2(4) NOT NULL,
COD_CARTERA VARCHAR2(6) NOT NULL,
NUM_SECU NUMBER(4) NOT NULL,
NUM_ORDEN NUMBER,
IDN_INT_PROC NUMBER NOT NULL,
COD_SIS_ORIGEN VARCHAR2(80) NOT NULL,
TIP_REGISTRO VARCHAR2(3),
TXT_NUM_EXTERNO VARCHAR2(40),
FEC_EFEC_CONTRATO DATE,
FEC_FIN DATE,
IDN_COBERTURA VARCHAR2(20),
IDN_PRIMA NUMBER,
TXT_MET_VAL VARCHAR2(3)
)';
EXECUTE IMMEDIATE 'COMMENT ON TABLE TRON2000.A1004811 IS ''NIIF 17 PRIMAS CONTRATO PAA FPSL''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004811.COD_CIA IS ''COMPAÑIA''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004811.NUM_POLIZA IS ''POLIZA''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004811.COD_RAMO IS ''RAMO''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004811.NUM_SPTO IS ''NUMERO DE SUPLEMENTO''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004811.NUM_APLI IS ''NUMERO DE APLICACION''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004811.NUM_SPTO_APLI IS ''SUPLEMENTO DE LA APLICACION''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004811.NUM_RIESGO IS ''RIESGO''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004811.NUM_PERIODO IS ''PERIODO (PARA POLIZAS MULTIANUALES)''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004811.COD_COB IS ''COBERTURA''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004811.COD_COHORTE IS ''DATO CON EL QUE SE IDENTIFICA EL AÑO DE EMISION O DE RENOVACION DEL CONTRATO.''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004811.COD_CARTERA IS ''CODIGO UNICO DE IDENTIFICACION DEL CONTRATO''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004811.NUM_SECU IS ''SECUENCIA''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004811.NUM_ORDEN IS ''ORDEN SECUENCIAL DE CADA COBERTURA DENTRO DE UN MISMO CONTRATO''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004811.IDN_INT_PROC IS ''IDENTIFICADOR DE PROCESO''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004811.COD_SIS_ORIGEN IS ''ORIGEN DE DATOS (TW)''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004811.TIP_REGISTRO IS ''TIPO DE REGISTRO''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004811.TXT_NUM_EXTERNO IS ''CODIGO UNICO DE IDENTIFICACION DEL CONTRATO''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004811.FEC_EFEC_CONTRATO IS ''FECHA DE EFECTO DEL CONTRATO''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004811.FEC_FIN IS ''FECHA FIN''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004811.IDN_COBERTURA IS ''CODIGO DE IDENTIFICACION DE LA COBERTURA''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004811.IDN_PRIMA IS ''IMPORTE DE LA PRIMA ANUAL O UNICA VIGENTE A NIVEL COBERTURA''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN TRON2000.A1004811.TXT_MET_VAL IS ''CODIGO QUE IDENTIFICA EL METODO DE VALORACION DEL CONTRATO BAJO NIIF 17''';
EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX TRON2000.PK_A1004811 ON TRON2000.A1004811
       (COD_CIA ASC,NUM_POLIZA ASC,COD_RAMO ASC,NUM_SPTO ASC,NUM_APLI ASC,NUM_SPTO_APLI ASC,NUM_RIESGO ASC,NUM_PERIODO ASC,COD_COB ASC,COD_COHORTE ASC,COD_CARTERA ASC)';
EXECUTE IMMEDIATE 'ALTER TABLE TRON2000.A1004811
      ADD CONSTRAINT PK_A1004811
      PRIMARY KEY(COD_CIA,NUM_POLIZA,COD_RAMO,NUM_SPTO,NUM_APLI,NUM_SPTO_APLI,NUM_RIESGO,NUM_PERIODO,COD_COB,COD_COHORTE,COD_CARTERA)
      USING INDEX TRON2000.PK_A1004811';
  --
  END IF;
--
END;
/