CREATE TABLE "TRON2000"."A1004814" (
    "COD_CIA"                  NUMBER(2, 0)        NOT NULL ENABLE,
    "NUM_POLIZA"               VARCHAR2(13 BYTE)        NOT NULL ENABLE,
    "COD_RAMO"                 NUMBER(3, 0)        NOT NULL ENABLE,
    "NUM_SPTO"                 NUMBER        NOT NULL ENABLE,
    "NUM_APLI"                 NUMBER        NOT NULL ENABLE,
    "NUM_SPTO_APLI"            NUMBER        NOT NULL ENABLE,
    "NUM_RIESGO"               NUMBER(7, 0)        NOT NULL ENABLE,
    "NUM_PERIODO"              NUMBER        NOT NULL ENABLE,
    "COD_COB"                  NUMBER(4, 0)        NOT NULL ENABLE,
    "COD_COHORTE"              VARCHAR2(4 BYTE)        NOT NULL ENABLE,
    "COD_CARTERA"              VARCHAR2(6 BYTE)        NOT NULL ENABLE,
    "TIP_REGISTRO_PAA"         VARCHAR2(5 BYTE)        NOT NULL ENABLE,
    "ID_CONTRATO_ORIG"         VARCHAR2(20 BYTE),
    "ID_GRANUALIDAD"           VARCHAR2(9 BYTE),
    "COD_NIVEL_GRANULA"        VARCHAR2(1 BYTE),
    "TIP_PATRON"               VARCHAR2(2 BYTE)        NOT NULL ENABLE,
    "NUM_POLIZA_SUBYACENTE"    VARCHAR2(20 BYTE),
    "TIP_APLICACION"           VARCHAR2(1 BYTE),
    "FEC_REGISTRO"             DATE DEFAULT NULL        NOT NULL ENABLE,
    "NUM_PROB_INCUMPLIMIENTO"  NUMBER DEFAULT NULL        NOT NULL ENABLE
)
SEGMENT CREATION DEFERRED
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING TABLESPACE "DATOS";

CREATE UNIQUE INDEX "TRON2000"."PK_A1004814" ON
    "TRON2000"."A1004814" (
        "COD_CIA",
        "NUM_POLIZA",
        "NUM_SPTO",
        "NUM_APLI",
        "NUM_SPTO_APLI",
        "NUM_RIESGO",
        "NUM_PERIODO",
        "COD_COB",
        "COD_COHORTE",
        "COD_CARTERA",
        "TIP_REGISTRO_PAA"
    )
        PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS TABLESPACE "DATOS";

ALTER TABLE "TRON2000"."A1004814"
    ADD CONSTRAINT "PK_A1004814" PRIMARY KEY ( "COD_CIA",
                                               "NUM_POLIZA",
                                               "NUM_SPTO",
                                               "NUM_APLI",
                                               "NUM_SPTO_APLI",
                                               "NUM_RIESGO",
                                               "NUM_PERIODO",
                                               "COD_COB",
                                               "COD_COHORTE",
                                               "COD_CARTERA",
                                               "TIP_REGISTRO_PAA" )
        USING INDEX "TRON2000"."PK_A1004814"
    ENABLE;

COMMENT ON COLUMN "TRON2000"."A1004814"."COD_CIA" IS
    'COMPANIA';

COMMENT ON COLUMN "TRON2000"."A1004814"."NUM_POLIZA" IS
    'POLIZA';

COMMENT ON COLUMN "TRON2000"."A1004814"."COD_RAMO" IS
    'RAMO';

COMMENT ON COLUMN "TRON2000"."A1004814"."NUM_SPTO" IS
    'NUMERO DE SUPLEMENTO';

COMMENT ON COLUMN "TRON2000"."A1004814"."NUM_APLI" IS
    'NUMERO DE APLICACION';

COMMENT ON COLUMN "TRON2000"."A1004814"."NUM_SPTO_APLI" IS
    'SUPLEMENTO DE LA APLICACION';

COMMENT ON COLUMN "TRON2000"."A1004814"."NUM_RIESGO" IS
    'RIESGO';

COMMENT ON COLUMN "TRON2000"."A1004814"."NUM_PERIODO" IS
    'PERIODO (PARA POLIZAS MULTIANUALES)';

COMMENT ON COLUMN "TRON2000"."A1004814"."COD_COB" IS
    'COBERTURA';

COMMENT ON COLUMN "TRON2000"."A1004814"."COD_COHORTE" IS
    'DATO CON EL QUE SE IDENTIFICA EL AÑO DE EMISION O DE RENOVACION DEL CONTRATO.';

COMMENT ON COLUMN "TRON2000"."A1004814"."COD_CARTERA" IS
    'DATO CON EL QUE SE IDENTIFICA LA CARTERA IFRS 17 A LA CUAL PERTENECE EL CONTRATO';

COMMENT ON COLUMN "TRON2000"."A1004814"."TIP_REGISTRO_PAA" IS
    'TIPO DE REGISTRO PRIMAS CONTRATO';

COMMENT ON COLUMN "TRON2000"."A1004814"."ID_CONTRATO_ORIG" IS
    'IDENTIFICADOR CONTRATO ORIGINAL';

COMMENT ON COLUMN "TRON2000"."A1004814"."ID_GRANUALIDAD" IS
    'IDENTIFICADOR GRANUALIDAD';

COMMENT ON COLUMN "TRON2000"."A1004814"."COD_NIVEL_GRANULA" IS
    'NIVEL GRANUALIDAD';

COMMENT ON COLUMN "TRON2000"."A1004814"."TIP_PATRON" IS
    'CAMPO QUE IDENTIFICA LA TIPOLOGIA DEL PATRON';

COMMENT ON COLUMN "TRON2000"."A1004814"."NUM_POLIZA_SUBYACENTE" IS
    'NUMERO DE POLIZA SUBYACENTE';

COMMENT ON COLUMN "TRON2000"."A1004814"."TIP_APLICACION" IS
    'TIPOLOGIA DE LA APLICACION';

COMMENT ON COLUMN "TRON2000"."A1004814"."FEC_REGISTRO" IS
    'FECHA DE REGISTRO';

COMMENT ON COLUMN "TRON2000"."A1004814"."NUM_PROB_INCUMPLIMIENTO" IS
    'PROBABILIDAD DE INCUMPLIMIENTO QUE SE APLICA A CADA ENTRADA DE LA TABLA DE PERIODIFICACIONES';

COMMENT ON TABLE "TRON2000"."A1004814" IS
    'NIIF 17 COMISIONES II';

GRANT DELETE ON "TRON2000"."A1004814" TO "ROL_TRON2000_ALL";

GRANT INSERT ON "TRON2000"."A1004814" TO "ROL_TRON2000_ALL";

GRANT SELECT ON "TRON2000"."A1004814" TO "ROL_TRON2000_ALL";

GRANT UPDATE ON "TRON2000"."A1004814" TO "ROL_TRON2000_ALL";

GRANT SELECT ON "TRON2000"."A1004814" TO "ROL_TRON2000_SEL";

GRANT DELETE ON "TRON2000"."A1004814" TO "NWT_DL";

GRANT INSERT ON "TRON2000"."A1004814" TO "NWT_DL";

GRANT SELECT ON "TRON2000"."A1004814" TO "NWT_DL";

GRANT UPDATE ON "TRON2000"."A1004814" TO "NWT_DL";

GRANT REFERENCES ON "TRON2000"."A1004814" TO "NWT_DL";

GRANT DELETE ON "TRON2000"."A1004814" TO "NWT_DM_APP";

GRANT INSERT ON "TRON2000"."A1004814" TO "NWT_DM_APP";

GRANT SELECT ON "TRON2000"."A1004814" TO "NWT_DM_APP";

GRANT UPDATE ON "TRON2000"."A1004814" TO "NWT_DM_APP";

GRANT REFERENCES ON "TRON2000"."A1004814" TO "NWT_DM_APP";

GRANT SELECT ON "TRON2000"."A1004814" TO "NWT_IL";