CREATE TABLE "TRON2000"."A1004811" (
    "COD_CIA"              NUMBER(2, 0)        NOT NULL ENABLE,
    "NUM_POLIZA"           VARCHAR2(13 BYTE)        NOT NULL ENABLE,
    "COD_RAMO"             NUMBER(3, 0)        NOT NULL ENABLE,
    "NUM_SPTO"             NUMBER        NOT NULL ENABLE,
    "NUM_APLI"             NUMBER        NOT NULL ENABLE,
    "NUM_SPTO_APLI"        NUMBER        NOT NULL ENABLE,
    "NUM_RIESGO"           NUMBER(7, 0)        NOT NULL ENABLE,
    "NUM_PERIODO"          NUMBER        NOT NULL ENABLE,
    "COD_COB"              NUMBER(4, 0)        NOT NULL ENABLE,
    "COD_COHORTE"          VARCHAR2(4 BYTE)        NOT NULL ENABLE,
    "COD_CARTERA"          VARCHAR2(6 BYTE)        NOT NULL ENABLE,
    "NUM_SECU"             NUMBER(4, 0)        NOT NULL ENABLE,
    "NUM_ORDEN"            NUMBER,
    "IDN_INT_PROC"         NUMBER        NOT NULL ENABLE,
    "COD_SIS_ORIGEN"       VARCHAR2(80 BYTE)        NOT NULL ENABLE,
    "TIP_REGISTRO_PAA"     VARCHAR2(5 BYTE),
    "TXT_NUM_EXTERNO"      VARCHAR2(40 BYTE),
    "FEC_EFEC_CONTRATO"    DATE,
    "FEC_FIN"              DATE,
    "IDN_COBERTURA"        VARCHAR2(20 BYTE),
    "IMP_PRIMA"            NUMBER,
    "TXT_MET_VAL"          VARCHAR2(7 BYTE),
    "IMP_COMISION"         NUMBER,
    "FEC_EMI_TIP_REG"      DATE,
    "COD_MON_ISO"          VARCHAR2(3 BYTE),
    "COD_FRACC_PAGO"       VARCHAR2(5 BYTE),
    "COD_PRE_PAG"          NUMBER(1, 0),
    "COD_RATIO_COMBINADO"  NUMBER,
    "IDN_FICHERO"          VARCHAR2(20 BYTE),
    "IDN_PROB_IMPAGO"      VARCHAR2(4 BYTE)
)
SEGMENT CREATION DEFERRED
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING TABLESPACE "DATOS";

CREATE UNIQUE INDEX "TRON2000"."PK_A1004811" ON
    "TRON2000"."A1004811" (
        "COD_CIA",
        "NUM_POLIZA",
        "COD_RAMO",
        "NUM_SPTO",
        "NUM_APLI",
        "NUM_SPTO_APLI",
        "NUM_RIESGO",
        "NUM_PERIODO",
        "COD_COB",
        "COD_COHORTE",
        "COD_CARTERA"
    )
        PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS TABLESPACE "DATOS";

ALTER TABLE "TRON2000"."A1004811"
    ADD CONSTRAINT "PK_A1004811" PRIMARY KEY ( "COD_CIA",
                                               "NUM_POLIZA",
                                               "COD_RAMO",
                                               "NUM_SPTO",
                                               "NUM_APLI",
                                               "NUM_SPTO_APLI",
                                               "NUM_RIESGO",
                                               "NUM_PERIODO",
                                               "COD_COB",
                                               "COD_COHORTE",
                                               "COD_CARTERA" )
        USING INDEX "TRON2000"."PK_A1004811"
    ENABLE;

COMMENT ON COLUMN "TRON2000"."A1004811"."COD_CIA" IS
    'COMPAÑIA';

COMMENT ON COLUMN "TRON2000"."A1004811"."NUM_POLIZA" IS
    'POLIZA';

COMMENT ON COLUMN "TRON2000"."A1004811"."COD_RAMO" IS
    'RAMO';

COMMENT ON COLUMN "TRON2000"."A1004811"."NUM_SPTO" IS
    'NUMERO DE SUPLEMENTO';

COMMENT ON COLUMN "TRON2000"."A1004811"."NUM_APLI" IS
    'NUMERO DE APLICACION';

COMMENT ON COLUMN "TRON2000"."A1004811"."NUM_SPTO_APLI" IS
    'SUPLEMENTO DE LA APLICACION';

COMMENT ON COLUMN "TRON2000"."A1004811"."NUM_RIESGO" IS
    'RIESGO';

COMMENT ON COLUMN "TRON2000"."A1004811"."NUM_PERIODO" IS
    'PERIODO (PARA POLIZAS MULTIANUALES)';

COMMENT ON COLUMN "TRON2000"."A1004811"."COD_COB" IS
    'COBERTURA';

COMMENT ON COLUMN "TRON2000"."A1004811"."COD_COHORTE" IS
    'DATO CON EL QUE SE IDENTIFICA EL AÑO DE EMISION O DE RENOVACION DEL CONTRATO.';

COMMENT ON COLUMN "TRON2000"."A1004811"."COD_CARTERA" IS
    'CODIGO UNICO DE IDENTIFICACION DEL CONTRATO';

COMMENT ON COLUMN "TRON2000"."A1004811"."NUM_SECU" IS
    'SECUENCIA';

COMMENT ON COLUMN "TRON2000"."A1004811"."NUM_ORDEN" IS
    'ORDEN SECUENCIAL DE CADA COBERTURA DENTRO DE UN MISMO CONTRATO';

COMMENT ON COLUMN "TRON2000"."A1004811"."IDN_INT_PROC" IS
    'IDENTIFICADOR DE PROCESO';

COMMENT ON COLUMN "TRON2000"."A1004811"."COD_SIS_ORIGEN" IS
    'ORIGEN DE DATOS (TW)';

COMMENT ON COLUMN "TRON2000"."A1004811"."TIP_REGISTRO_PAA" IS
    'TIPO DE REGISTRO PRIMAS CONTRATO';

COMMENT ON COLUMN "TRON2000"."A1004811"."TXT_NUM_EXTERNO" IS
    'CODIGO UNICO DE IDENTIFICACION DEL CONTRATO';

COMMENT ON COLUMN "TRON2000"."A1004811"."FEC_EFEC_CONTRATO" IS
    'FECHA DE EFECTO DEL CONTRATO';

COMMENT ON COLUMN "TRON2000"."A1004811"."FEC_FIN" IS
    'FECHA FIN';

COMMENT ON COLUMN "TRON2000"."A1004811"."IDN_COBERTURA" IS
    'CODIGO DE IDENTIFICACION DE LA COBERTURA';

COMMENT ON COLUMN "TRON2000"."A1004811"."IMP_PRIMA" IS
    'IMPORTE DE LA PRIMA ANUAL O UNICA VIGENTE A NIVEL COBERTURA';

COMMENT ON COLUMN "TRON2000"."A1004811"."TXT_MET_VAL" IS
    'CODIGO QUE IDENTIFICA EL METODO DE VALORACION DEL CONTRATO BAJO NIIF 17';

COMMENT ON COLUMN "TRON2000"."A1004811"."IMP_COMISION" IS
    'IMPORTE DE LA COMISION ANUAL VIGENTE A NIVEL COBERTURA';

COMMENT ON COLUMN "TRON2000"."A1004811"."FEC_EMI_TIP_REG" IS
    'FECHA DE EMISION DEL TIPO DE REGISTRO';

COMMENT ON COLUMN "TRON2000"."A1004811"."COD_MON_ISO" IS
    'CODIGO DE MONEDA ESTANDARD';

COMMENT ON COLUMN "TRON2000"."A1004811"."COD_FRACC_PAGO" IS
    'PLAN DE PAGO';

COMMENT ON COLUMN "TRON2000"."A1004811"."COD_PRE_PAG" IS
    'INDICADOR DE SI EL PAGO DE LA PRIMA ES PREPAGABLE O POS PAGABLE';

COMMENT ON COLUMN "TRON2000"."A1004811"."COD_RATIO_COMBINADO" IS
    'RATIO COMBINADO USADO PARA EL CALCULO Y DETERMINACION DEL LOSS COMPONENT';

COMMENT ON COLUMN "TRON2000"."A1004811"."IDN_FICHERO" IS
    'CODIGO IDENTIFICATIVO DEL FICHERO ENVIADO';

COMMENT ON COLUMN "TRON2000"."A1004811"."IDN_PROB_IMPAGO" IS
    'CODIGO IDENTIFICATIVO DE PROBABILIDAD DE PAGO';

COMMENT ON TABLE "TRON2000"."A1004811" IS
    'NIIF 17 PRIMAS CONTRATO PAA FPSL';

GRANT DELETE ON "TRON2000"."A1004811" TO "ROL_TRON2000_ALL";

GRANT INSERT ON "TRON2000"."A1004811" TO "ROL_TRON2000_ALL";

GRANT SELECT ON "TRON2000"."A1004811" TO "ROL_TRON2000_ALL";

GRANT UPDATE ON "TRON2000"."A1004811" TO "ROL_TRON2000_ALL";

GRANT SELECT ON "TRON2000"."A1004811" TO "ROL_TRON2000_SEL";

GRANT DELETE ON "TRON2000"."A1004811" TO "NWT_DL";

GRANT INSERT ON "TRON2000"."A1004811" TO "NWT_DL";

GRANT SELECT ON "TRON2000"."A1004811" TO "NWT_DL";

GRANT UPDATE ON "TRON2000"."A1004811" TO "NWT_DL";

GRANT REFERENCES ON "TRON2000"."A1004811" TO "NWT_DL";

GRANT DELETE ON "TRON2000"."A1004811" TO "NWT_DM_APP";

GRANT INSERT ON "TRON2000"."A1004811" TO "NWT_DM_APP";

GRANT SELECT ON "TRON2000"."A1004811" TO "NWT_DM_APP";

GRANT UPDATE ON "TRON2000"."A1004811" TO "NWT_DM_APP";

GRANT REFERENCES ON "TRON2000"."A1004811" TO "NWT_DM_APP";

GRANT SELECT ON "TRON2000"."A1004811" TO "NWT_IL";